import fs from 'fs';
import path from 'path';

const nouns = [
  { w: 'プール', r: 'プール', rom: 'puuru', m: 'piscina' },
  { w: '来月', r: 'らいげつ', rom: 'raigetsu', m: 'mês que vem' },
  { w: '来年', r: 'らいねん', rom: 'rainen', m: 'ano que vem' },
  { w: '来週', r: 'らいしゅう', rom: 'raishuu', m: 'semana que vem' },
  { w: 'ラジオ', r: 'ラジオ', rom: 'rajio', m: 'rádio' },
  { w: '零', r: 'れい', rom: 'rei', m: 'zero' },
  { w: '冷蔵庫', r: 'れいぞうこ', rom: 'reizouko', m: 'geladeira' },
  { w: 'レコード', r: 'レコード', rom: 'rekoodo', m: 'disco de vinil; gravação' },
  { w: '練習', r: 'れんしゅう', rom: 'renshuu', m: 'prática; exercício' },
  { w: 'レストラン', r: 'レストラン', rom: 'resutoran', m: 'restaurante' },
  { w: '六', r: 'ろく', rom: 'roku', m: 'seis; 6' },
  { w: '廊下', r: 'ろうか', rom: 'rouka', m: 'corredor' },
  { w: '旅行', r: 'りょこう', rom: 'ryokou', m: 'viagem' },
  { w: '料理', r: 'りょうり', rom: 'ryouri', m: 'culinária; prato (comida)' },
  { w: '両親', r: 'りょうしん', rom: 'ryoushin', m: 'pais (ambos os pais)' },
  { w: '留学生', r: 'りゅうがくせい', rom: 'ryuugakusei', m: 'estudante de intercâmbio' },
  { w: '財布', r: 'さいふ', rom: 'saifu', m: 'carteira' },
  { w: '魚', r: 'さかな', rom: 'sakana', m: 'peixe' },
  { w: '先', r: 'さき', rom: 'saki', m: 'frente; antes; anterior' },
  { w: '作文', r: 'さくぶん', rom: 'sakubun', m: 'redação; composição' },
  { w: '三', r: 'さん', rom: 'san', m: 'três; 3' },
  { w: '散歩', r: 'さんぽ', rom: 'sanpo', m: 'passeio; caminhada' },
  { w: '再来年', r: 'さらいねん', rom: 'sarainen', m: 'ano seguinte ao próximo (daqui a dois anos)' },
  { w: '砂糖', r: 'さとう', rom: 'satou', m: 'açúcar' },
  { w: '背', r: 'せ', rom: 'se', m: 'estatura; costas' },
  { w: '背広', r: 'せびろ', rom: 'sebiro', m: 'terno de negócios' },
  { w: 'セーター', r: 'セーター', rom: 'seetaa', m: 'suéter' },
  { w: '生徒', r: 'せいと', rom: 'seito', m: 'aluno' },
  { w: '石鹸', r: 'せっけん', rom: 'sekken', m: 'sabonete' },
  { w: '千', r: 'せん', rom: 'sen', m: 'mil; 1.000' },
  { w: '先月', r: 'せんげつ', rom: 'sengetsu', m: 'mês passado' },
  { w: '先生', r: 'せんせい', rom: 'sensei', m: 'professor; mestre' },
  { w: '先週', r: 'せんしゅう', rom: 'senshuu', m: 'semana passada' },
  { w: '洗濯', r: 'せんたく', rom: 'sentaku', m: 'lavagem de roupa' },
  { w: '写真', r: 'しゃしん', rom: 'shashin', m: 'fotografia; foto' },
  { w: 'シャツ', r: 'シャツ', rom: 'shatsu', m: 'camisa' },
  { w: 'シャワー', r: 'シャワー', rom: 'shawaa', m: 'chuveiro; ducha' },
  { w: '四', r: 'し', rom: 'shi', m: 'quatro; 4' },
  { w: '七', r: 'しち', rom: 'shichi', m: 'sete; 7' },
  { w: '仕事', r: 'しごと', rom: 'shigoto', m: 'trabalho; emprego' },
  { w: '新聞', r: 'しんぶん', rom: 'shinbun', m: 'jornal' },
  { w: '塩', r: 'しお', rom: 'shio', m: 'sal' },
  { w: '白', r: 'しろ', rom: 'shiro', m: 'branco' },
  { w: '下', r: 'した', rom: 'shita', m: 'embaixo; sob; inferior' },
  { w: '質問', r: 'しつもん', rom: 'shitsumon', m: 'pergunta' },
  { w: '食堂', r: 'しょくどう', rom: 'shokudou', m: 'refeitório; cantina' },
  { w: '醤油', r: 'しょうゆ', rom: 'shouyu', m: 'molho de soja (shoyu)' },
  { w: '宿題', r: 'しゅくだい', rom: 'shukudai', m: 'lição de casa' },
  { w: 'そば', r: 'そば', rom: 'soba', m: 'perto; ao lado' },
  { w: '空', r: 'そら', rom: 'sora', m: 'céu' },
  { w: '外', r: 'そと', rom: 'soto', m: 'fora; exterior' },
  { w: '掃除', r: 'そうじ', rom: 'souji', m: 'limpeza' },
  { w: '水曜日', r: 'すいようび', rom: 'suiyoubi', m: 'quarta-feira' },
  { w: 'スカート', r: 'スカート', rom: 'sukaato', m: 'saia' },
  { w: '好き', r: 'すき', rom: 'suki', m: 'gostar; favorito' },
  { w: '少し', r: 'すこし', rom: 'sukoshi', m: 'um pouco' },
  { w: 'スポーツ', r: 'スポーツ', rom: 'supootsu', m: 'esporte' },
  { w: 'スプーン', r: 'スプーン', rom: 'supuun', m: 'colher' },
  { w: 'スリッパ', r: 'スリッパ', rom: 'surippa', m: 'pantufas; chinelos' },
  { w: 'ストーブ', r: 'ストーブ', rom: 'sutoobu', m: 'aquecedor' },
  { w: 'たばこ', r: 'たばこ', rom: 'tabako', m: 'cigarro; tabaco' },
  { w: '食べ物', r: 'たべもの', rom: 'tabemono', m: 'comida; alimento' },
  { w: '大変', r: 'たいへん', rom: 'taihen', m: 'muito; difícil; terrível' },
  { w: '大切', r: 'たいせつ', rom: 'taisetsu', m: 'importante; precioso' },
  { w: '大使館', r: 'たいしかん', rom: 'taishikan', m: 'embaixada' },
  { w: '沢山', r: 'たくさん', rom: 'takusan', m: 'muito; muitos' },
  { w: 'タクシー', r: 'タクシー', rom: 'takushii', m: 'táxi' },
  { w: '卵', r: 'たまご', rom: 'tamago', m: 'ovo' },
  { w: '誕生日', r: 'たんじょうび', rom: 'tanjoubi', m: 'aniversário' },
  { w: '縦', r: 'たて', rom: 'tate', m: 'comprimento; altura; vertical' },
  { w: '建物', r: 'たてもの', rom: 'tatemono', m: 'prédio; edifício' },
  { w: '手', r: 'て', rom: 'te', m: 'mão; braço' },
  { w: 'テーブル', r: 'テーブル', rom: 'teeburu', m: 'mesa' },
  { w: 'テープ', r: 'テープ', rom: 'teepu', m: 'fita (tape)' },
  { w: 'テープレコーダー', r: 'テープレコーダー', rom: 'teepu rekoodaa', m: 'gravador de fita' },
  { w: '手紙', r: 'てがみ', rom: 'tegami', m: 'carta' },
  { w: '天気', r: 'てんき', rom: 'tenki', m: 'clima; tempo' },
  { w: 'テレビ', r: 'テレビ', rom: 'terebi', m: 'televisão; TV' },
  { w: 'テスト', r: 'テスト', rom: 'tesuto', m: 'prova; teste' },
  { w: '戸', r: 'と', rom: 'to', m: 'porta (estilo japonês)' },
  { w: 'トイレ', r: 'トイレ', rom: 'toire', m: 'banheiro; toalete' },
  { w: '時計', r: 'とけい', rom: 'tokei', m: 'relógio' },
  { w: '時', r: 'とき', rom: 'toki', m: 'tempo; momento; quando' },
  { w: '時々', r: 'ときどき', rom: 'tokidoki', m: 'às vezes' },
  { w: '所', r: 'ところ', rom: 'tokoro', m: 'lugar; local' },
  { w: '友達', r: 'ともだち', rom: 'tomodachi', m: 'amigo' },
  { w: '隣', r: 'となり', rom: 'tonari', m: 'ao lado; vizinho' },
  { w: '十日', r: 'とおか', rom: 'tooka', m: 'dia 10 (do mês); dez dias' },
  { w: '鳥', r: 'とり', rom: 'tori', m: 'pássaro; ave' },
  { w: '鶏肉', r: 'とりにく', rom: 'toriniku', m: 'carne de frango' },
  { w: '年', r: 'とし', rom: 'toshi', m: 'ano; idade' },
  { w: '図書館', r: 'としょかん', rom: 'toshokan', m: 'biblioteca' },
  { w: '次', r: 'つぎ', rom: 'tsugi', m: 'próximo; seguinte' },
  { w: '一日', r: 'ついたち', rom: 'tsuitachi', m: 'primeiro dia do mês' },
  { w: '机', r: 'つくえ', rom: 'tsukue', m: 'mesa; escrivaninha' },
  { w: '上', r: 'うえ', rom: 'ue', m: 'em cima; acima; sobre' },
  { w: '海', r: 'うみ', rom: 'umi', m: 'mar; oceano' },
  { w: '後ろ', r: 'うしろ', rom: 'ushiro', m: 'atrás' },
  { w: '歌', r: 'うた', rom: 'uta', m: 'música; canção' },
  { w: '上着', r: 'うわぎ', rom: 'uwagi', m: 'casaco; jaqueta' }
];

const examples = {
  'プール': { jp: 'プールで泳ぎます。', r: 'プールで およぎます。', rom: 'puuru de oyogimasu.', pt: 'Eu nado na piscina.' },
  '来月': { jp: '来月、日本へ行きます。', r: 'らいげつ、にほんへ いきます。', rom: 'raigetsu, nihon e ikimasu.', pt: 'Mês que vem vou para o Japão.' },
  '来年': { jp: '来年は大学生になります。', r: 'らいねんは だいがくせいに なります。', rom: 'rainen wa daigakusei ni narimasu.', pt: 'Ano que vem serei universitário.' },
  '来週': { jp: '来週の月曜日は休みです。', r: 'らいしゅうの げつようびは やすみです。', rom: 'raishuu no getsuyoubi wa yasumi desu.', pt: 'A segunda-feira da semana que vem é folga.' },
  'ラジオ': { jp: 'ラジオで音楽を聞きます。', r: 'ラジオで おんがくを ききます。', rom: 'rajio de ongaku o kikimasu.', pt: 'Ouço música no rádio.' },
  '零': { jp: '今日の気温は零度です。', r: 'きょうの きおんは れいどです。', rom: 'kyou no kion wa reido desu.', pt: 'A temperatura de hoje é zero grau.' },
  '冷蔵庫': { jp: 'ジュースを冷蔵庫に入れます。', r: 'ジュースを れいぞうこに いれます。', rom: 'juusu o reizouko ni iremasu.', pt: 'Vou colocar o suco na geladeira.' },
  'レコード': { jp: '古いレコードを買いました。', r: 'ふるい レコードを かいました。', rom: 'furui rekoodo o kaimashita.', pt: 'Comprei um disco de vinil antigo.' },
  '練習': { jp: '漢字の練習をします。', r: 'かんじの れんしゅうを します。', rom: 'kanji no renshuu o shimasu.', pt: 'Vou praticar os kanjis.' },
  'レストラン': { jp: 'レストランで晩ご飯を食べます。', r: 'レストランで ばんごはんを たべます。', rom: 'resutoran de bangohan o tabemasu.', pt: 'Vou jantar no restaurante.' },
  '六': { jp: '鉛筆が六本あります。', r: 'えんぴつが ろっぽん あります。', rom: 'enpitsu ga roppon arimasu.', pt: 'Há seis lápis.' },
  '廊下': { jp: '廊下を走らないでください。', r: 'ろうかを はしらないでください。', rom: 'rouka o hashiranaide kudasai.', pt: 'Por favor, não corra no corredor.' },
  '旅行': { jp: '家族と旅行に行きました。', r: 'かぞくと りょこうに いきました。', rom: 'kazoku to ryokou ni ikimashita.', pt: 'Fui viajar com minha família.' },
  '料理': { jp: '母の料理は美味しいです。', r: 'ははの りょうりは おいしいです。', rom: 'haha no ryouri wa oishii desu.', pt: 'A comida (prato) da minha mãe é gostosa.' },
  '両親': { jp: '両親に手紙を書きました。', r: 'りょうしんに てがみを かきました。', rom: 'ryoushin ni tegami o kakimashita.', pt: 'Escrevi uma carta para meus pais.' },
  '留学生': { jp: '私のクラスには留学生がいます。', r: 'わたしの クラスには りゅうがくせいが います。', rom: 'watashi no kurasu ni wa ryuugakusei ga imasu.', pt: 'Na minha classe há estudantes de intercâmbio.' },
  '財布': { jp: '財布を忘れました。', r: 'さいふを わすれました。', rom: 'saifu o wasuremashita.', pt: 'Esqueci minha carteira.' },
  '魚': { jp: '魚を焼きます。', r: 'さかなを やきます。', rom: 'sakana o yakimasu.', pt: 'Assar o peixe.' },
  '先': { jp: 'お先に失礼します。', r: 'おさきに しつれいします。', rom: 'osaki ni shitsureishimasu.', pt: 'Com licença, vou na frente (embora).' },
  '作文': { jp: '日本語で作文を書きました。', r: 'にほんごで さくぶんを かきました。', rom: 'nihongo de sakubun o kakimashita.', pt: 'Escrevi uma redação em japonês.' },
  '三': { jp: 'りんごが三個あります。', r: 'りんごが さんこ あります。', rom: 'ringo ga sanko arimasu.', pt: 'Há três maçãs.' },
  '散歩': { jp: '公園を散歩します。', r: 'こうえんを さんぽします。', rom: 'kouen o sanposhimasu.', pt: 'Faço um passeio pelo parque.' },
  '再来年': { jp: '再来年、大学を卒業します。', r: 'さらいねん、だいがくを そつぎょうします。', rom: 'sarainen, daigaku o sotsugyoushimasu.', pt: 'Vou me formar na universidade no ano seguinte ao próximo.' },
  '砂糖': { jp: 'コーヒーに砂糖を入れます。', r: 'コーヒーに さとうを いれます。', rom: 'koohii ni satou o iremasu.', pt: 'Colocar açúcar no café.' },
  '背': { jp: '彼は背が高いです。', r: 'かれは せが たかいです。', rom: 'kare wa se ga takai desu.', pt: 'Ele é alto (tem estatura alta).' },
  '背広': { jp: '仕事で背広を着ます。', r: 'しごとで せびろを きます。', rom: 'shigoto de sebiro o kimasu.', pt: 'Uso terno de negócios no trabalho.' },
  'セーター': { jp: '寒いのでセーターを着ます。', r: 'さむいので セーターを きます。', rom: 'samui node seetaa o kimasu.', pt: 'Visto o suéter porque está frio.' },
  '生徒': { jp: '先生が生徒に教えます。', r: 'せんせいが せいとに おしえます。', rom: 'sensei ga seito ni oshiemasu.', pt: 'O professor ensina aos alunos.' },
  '石鹸': { jp: '石鹸で手を洗います。', r: 'せっけんで てを あらいます。', rom: 'sekken de te o araimasu.', pt: 'Lavar as mãos com sabonete.' },
  '千': { jp: '千円貸してください。', r: 'せんえん かしてください。', rom: 'senen kashite kudasai.', pt: 'Me empreste mil ienes, por favor.' },
  '先月': { jp: '先月、京都へ行きました。', r: 'せんげつ、きょうとへ いきました。', rom: 'sengetsu, kyouto e ikimashita.', pt: 'Fui a Quioto no mês passado.' },
  '先生': { jp: '先生、質問があります。', r: 'せんせい、しつもんが あります。', rom: 'sensei, shitsumon ga arimasu.', pt: 'Professor, tenho uma pergunta.' },
  '先週': { jp: '先週は忙しかったです。', r: 'せんしゅうは いそがしかったです。', rom: 'senshuu wa isogashikatta desu.', pt: 'A semana passada foi corrida.' },
  '洗濯': { jp: '週末に洗濯をします。', r: 'しゅうまつに せんたくを します。', rom: 'shuumatsu ni sentaku o shimasu.', pt: 'Vou lavar a roupa no fim de semana.' },
  '写真': { jp: '海で写真を撮りました。', r: 'うみで しゃしんを とりました。', rom: 'umi de shashin o torimashita.', pt: 'Tirei fotos no mar.' },
  'シャツ': { jp: '白いシャツを着ています。', r: 'しろい シャツを きています。', rom: 'shiroi shatsu o kiteimasu.', pt: 'Estou vestindo uma camisa branca.' },
  'シャワー': { jp: '朝、シャワーを浴びます。', r: 'あさ、シャワーを あびます。', rom: 'asa, shawaa o abimasu.', pt: 'Tomo uma ducha de manhã.' },
  '四': { jp: '四月から大学が始まります。', r: 'しがつから だいがくが はじまります。', rom: 'shigatsu kara daigaku ga hajimarimasu.', pt: 'A universidade começa em abril.' },
  '七': { jp: '七時に起きます。', r: 'しちじに おきます。', rom: 'shichiji ni okimasu.', pt: 'Acordo às sete horas.' },
  '仕事': { jp: '仕事は八時半からです。', r: 'しごとは はちじはんからです。', rom: 'shigoto wa hachijihan kara desu.', pt: 'O trabalho começa às 8 e meia.' },
  '新聞': { jp: '毎朝新聞を読みます。', r: 'まいあさ しんぶんを よみます。', rom: 'maiasa shinbun o yomimasu.', pt: 'Toda manhã eu leio o jornal.' },
  '塩': { jp: 'スープに塩を入れます。', r: 'スープに しおを いれます。', rom: 'suupu ni shio o iremasu.', pt: 'Colocar sal na sopa.' },
  '白': { jp: '白い花が咲いています。', r: 'しろい はなが さいています。', rom: 'shiroi hana ga saiteimasu.', pt: 'Flores brancas estão desabrochando.' },
  '下': { jp: '机の下に猫がいます。', r: 'つくえの したに ねこが います。', rom: 'tsukue no shita ni neko ga imasu.', pt: 'O gato está embaixo da mesa.' },
  '質問': { jp: '質問してもいいですか。', r: 'しつもんしても いいですか。', rom: 'shitsumon shite mo ii desu ka.', pt: 'Posso fazer uma pergunta?' },
  '食堂': { jp: '会社の食堂で昼ご飯を食べます。', r: 'かいしゃの しょくどうで ひるごはんを たべます。', rom: 'kaisha no shokudou de hirugohan o tabemasu.', pt: 'Almoço no refeitório da empresa.' },
  '醤油': { jp: '寿司に醤油をつけます。', r: 'すしに しょうゆを つけます。', rom: 'sushi ni shouyu o tsukemasu.', pt: 'Colocar molho de soja (shoyu) no sushi.' },
  '宿題': { jp: '家に帰って宿題をします。', r: 'いえに かえって しゅくだいを します。', rom: 'ie ni kaette shukudai o shimasu.', pt: 'Vou voltar para casa e fazer a lição de casa.' },
  'そば': { jp: '駅のそばに住んでいます。', r: 'えきの そばに すんでいます。', rom: 'eki no soba ni sundeimasu.', pt: 'Moro perto da estação.' },
  '空': { jp: '空が青いです。', r: 'そらが あおいです。', rom: 'sora ga aoi desu.', pt: 'O céu está azul.' },
  '外': { jp: '外は雨が降っています。', r: 'そとは あめが ふっています。', rom: 'soto wa ame ga futteimasu.', pt: 'Lá fora está chovendo.' },
  '掃除': { jp: '部屋を掃除します。', r: 'へやを そうじします。', rom: 'heya o soujishimasu.', pt: 'Fazer a limpeza do quarto.' },
  '水曜日': { jp: '水曜日は図書館が休みです。', r: 'すいようびは としょかんが やすみです。', rom: 'suiyoubi wa toshokan ga yasumi desu.', pt: 'A biblioteca fecha (é folga) nas quartas-feiras.' },
  'スカート': { jp: '新しいスカートを買いました。', r: 'あたらしい スカートを かいました。', rom: 'atarashii sukaato o kaimashita.', pt: 'Comprei uma saia nova.' },
  '好き': { jp: '私はりんごが好きです。', r: 'わたしは りんごが すきです。', rom: 'watashi wa ringo ga suki desu.', pt: 'Eu gosto de maçã.' },
  '少し': { jp: '少し待ってください。', r: 'すこし まってください。', rom: 'sukoshi matte kudasai.', pt: 'Por favor, espere um pouco.' },
  'スポーツ': { jp: '休日はスポーツをします。', r: 'きゅうじつは スポーツを します。', rom: 'kyuujitsu wa supootsu o shimasu.', pt: 'Nos feriados eu pratico esportes.' },
  'スプーン': { jp: 'スプーンでスープを飲みます。', r: 'スプーンで スープを のみます。', rom: 'supuun de suupu o nomimasu.', pt: 'Tomo a sopa com a colher.' },
  'スリッパ': { jp: 'スリッパを履いてください。', r: 'スリッパを はいてください。', rom: 'surippa o haite kudasai.', pt: 'Por favor, calce as pantufas.' },
  'ストーブ': { jp: '寒いからストーブをつけます。', r: 'さむいから ストーブを つけます。', rom: 'samui kara sutoobu o tsukemasu.', pt: 'Vou ligar o aquecedor porque está frio.' },
  'たばこ': { jp: 'たばこを吸ってもいいですか。', r: 'たばこを すっても いいですか。', rom: 'tabako o sutte mo ii desu ka.', pt: 'Posso fumar cigarro?' },
  '食べ物': { jp: '好きな食べ物は何ですか。', r: 'すきな たべものは なんですか。', rom: 'suki na tabemono wa nan desu ka.', pt: 'Qual é a sua comida favorita?' },
  '大変': { jp: '今日の仕事は大変でした。', r: 'きょうの しごとは たいへんでした。', rom: 'kyou no shigoto wa taihen deshita.', pt: 'O trabalho de hoje foi muito difícil/cansativo.' },
  '大切': { jp: '家族は私にとって大切です。', r: 'かぞくは わたしにとって たいせつです。', rom: 'kazoku wa watashi ni totte taisetsu desu.', pt: 'A família é muito importante para mim.' },
  '大使館': { jp: '大使館へビザを取りに行きます。', r: 'たいしかんへ ビザを とりに いきます。', rom: 'taishikan e biza o tori ni ikimasu.', pt: 'Vou à embaixada pegar o visto.' },
  '沢山': { jp: '人がたくさんいます。', r: 'ひとが たくさん います。', rom: 'hito ga takusan imasu.', pt: 'Há muitas pessoas.' },
  'タクシー': { jp: 'タクシーで帰ります。', r: 'タクシーで かえります。', rom: 'takushii de kaerimasu.', pt: 'Vou voltar de táxi.' },
  '卵': { jp: '卵を二つ買いました。', r: 'たまごを ふたつ かいました。', rom: 'tamago o futatsu kaimashita.', pt: 'Comprei dois ovos.' },
  '誕生日': { jp: '明日は私の誕生日です。', r: 'あしたは わたしの たんじょうびです。', rom: 'ashita wa watashi no tanjoubi desu.', pt: 'Amanhã é meu aniversário.' },
  '縦': { jp: '縦に線を引いてください。', r: 'たてに せんを ひいてください。', rom: 'tate ni sen o hiite kudasai.', pt: 'Por favor, desenhe uma linha vertical.' },
  '建物': { jp: 'あそこに高い建物があります。', r: 'あそこに たかい たてものが あります。', rom: 'asoko ni takai tatemono ga arimasu.', pt: 'Há um prédio alto ali.' },
  '手': { jp: '手を洗ってください。', r: 'てを あらってください。', rom: 'te o aratte kudasai.', pt: 'Lave as mãos, por favor.' },
  'テーブル': { jp: 'テーブルの上にりんごがあります。', r: 'テーブルの うえに りんごが あります。', rom: 'teeburu no ue ni ringo ga arimasu.', pt: 'Há uma maçã em cima da mesa.' },
  'テープ': { jp: 'テープで紙を貼ります。', r: 'テープで かみを はります。', rom: 'teepu de kami o harimasu.', pt: 'Colo o papel com fita adesiva.' },
  'テープレコーダー': { jp: '授業をテープレコーダーで録音します。', r: 'じゅぎょうを テープレコーダーで ろくおんします。', rom: 'jugyou o teepu rekoodaa de rokuon shimasu.', pt: 'Vou gravar a aula com um gravador de fita.' },
  '手紙': { jp: '友達に手紙を書きます。', r: 'ともだちに てがみを かきます。', rom: 'tomodachi ni tegami o kakimasu.', pt: 'Escrevo uma carta para um amigo.' },
  '天気': { jp: '明日の天気はどうですか。', r: 'あしたの てんきは どうですか。', rom: 'ashita no tenki wa dou desu ka.', pt: 'Como estará o tempo amanhã?' },
  'テレビ': { jp: '毎晩テレビを見ます。', r: 'まいばん テレビを みます。', rom: 'maiban terebi o mimasu.', pt: 'Assisto televisão toda noite.' },
  'テスト': { jp: '明日、日本語のテストがあります。', r: 'あした、にほんごの テストが あります。', rom: 'ashita, nihongo no tesuto ga arimasu.', pt: 'Amanhã terei prova de japonês.' },
  '戸': { jp: '戸を閉めてください。', r: 'とを しめてください。', rom: 'to o shimete kudasai.', pt: 'Feche a porta, por favor.' },
  'トイレ': { jp: 'トイレはどこですか。', r: 'トイレは どこですか。', rom: 'toire wa doko desu ka.', pt: 'Onde fica o banheiro?' },
  '時計': { jp: '新しい時計を買いました。', r: 'あたらしい とけいを かいました。', rom: 'atarashii tokei o kaimashita.', pt: 'Comprei um relógio novo.' },
  '時': { jp: '子供の時、よくここで遊びました。', r: 'こどもの とき、よく ここで あそびました。', rom: 'kodomo no toki, yoku koko de asobimashita.', pt: 'Quando era criança, eu brincava muito aqui.' },
  '時々': { jp: '時々映画を見に行きます。', r: 'ときどき えいがを みに いきます。', rom: 'tokidoki eiga o mini ikimasu.', pt: 'Às vezes vou ver um filme.' },
  '所': { jp: 'ここは静かな所です。', r: 'ここは しずかな ところです。', rom: 'koko wa shizuka na tokoro desu.', pt: 'Aqui é um lugar tranquilo.' },
  '友達': { jp: '友達と遊園地に行きました。', r: 'ともだちと ゆうえんちに いきました。', rom: 'tomodachi to yuuenchi ni ikimashita.', pt: 'Fui ao parque de diversões com um amigo.' },
  '隣': { jp: '私の隣に座ってください。', r: 'わたしの となりに すわってください。', rom: 'watashi no tonari ni suwatte kudasai.', pt: 'Por favor, sente-se ao meu lado.' },
  '十日': { jp: '四月十日に日本へ来ました。', r: 'しがつ とおかに にほんへ きました。', rom: 'shigatsu tooka ni nihon e kimashita.', pt: 'Vim ao Japão no dia 10 de abril.' },
  '鳥': { jp: '空に鳥が飛んでいます。', r: 'そらに とりが とんでいます。', rom: 'sora ni tori ga tondeimasu.', pt: 'Há pássaros voando no céu.' },
  '鶏肉': { jp: '鶏肉を焼いて食べました。', r: 'とりにくを やいて たべました。', rom: 'toriniku o yaite tabemashita.', pt: 'Assei e comi carne de frango.' },
  '年': { jp: '年はいくつですか。', r: 'としは いくつですか。', rom: 'toshi wa ikutsu desu ka.', pt: 'Qual é a sua idade? (Quantos anos?)' },
  '図書館': { jp: '図書館で本を借ります。', r: 'としょかんで ほんを かります。', rom: 'toshokan de hon o karimasu.', pt: 'Peguei um livro emprestado na biblioteca.' },
  '次': { jp: '次の駅で降ります。', r: 'つぎの えきで おります。', rom: 'tsugi no eki de orimasu.', pt: 'Vou descer na próxima estação.' },
  '一日': { jp: '今日から五月一日です。', r: 'きょうから ごがつ ついたちです。', rom: 'kyou kara gogatsu tsuitachi desu.', pt: 'Hoje é dia 1º de maio.' },
  '机': { jp: '机の上に本があります。', r: 'つくえの うえに ほんが あります。', rom: 'tsukue no ue ni hon ga arimasu.', pt: 'Há um livro em cima da mesa.' },
  '上': { jp: 'テレビの上に時計があります。', r: 'テレビの うえに とけいが あります。', rom: 'terebi no ue ni tokei ga arimasu.', pt: 'Há um relógio em cima da televisão.' },
  '海': { jp: '夏は海で泳ぎたいです。', r: 'なつは うみで およぎたいです。', rom: 'natsu wa umi de oyogitai desu.', pt: 'No verão quero nadar no mar.' },
  '後ろ': { jp: '私の後ろに人がいます。', r: 'わたしの うしろに ひとが います。', rom: 'watashi no ushiro ni hito ga imasu.', pt: 'Há uma pessoa atrás de mim.' },
  '歌': { jp: '一緒に歌を歌いましょう。', r: 'いっしょに うたを うたいましょう。', rom: 'issho ni uta o utaimashou.', pt: 'Vamos cantar uma música juntos.' },
  '上着': { jp: '上着を脱いでください。', r: 'うわぎを ぬいでください。', rom: 'uwagi o nuide kudasai.', pt: 'Tire o casaco, por favor.' }
};

const filePath = path.join(process.cwd(), 'src/data/vocabN5.ts');
let fileContent = fs.readFileSync(filePath, 'utf8');

const newObjects = nouns.map((n, i) => {
  const ex = examples[n.w] || {
    jp: "Exemplo",
    reading: "...",
    rom: "...",
    pt: "..."
  };
  
  const safePt = ex.pt.replace(/'/g, "\\'");

  return "  {\n" +
    "    id: 'n5_noun_batch4_" + Date.now() + "_" + i + "',\n" +
    "    word: '" + n.w + "',\n" +
    "    reading: '" + n.r + "',\n" +
    "    romaji: '" + n.rom + "',\n" +
    "    meaningPt: '" + n.m + "',\n" +
    "    category: 'substantivo',\n" +
    "    jlpt: 'N5',\n" +
    "    categoryLabelPt: 'Substantivo N5',\n" +
    "    exampleSentence: {\n" +
    "      jp: '" + ex.jp + "',\n" +
    "      reading: '" + ex.r + "',\n" +
    "      romaji: '" + ex.rom + "',\n" +
    "      meaningPt: '" + safePt + "'\n" +
    "    }\n" +
    "  }";
}).join(',\n');

fileContent = fileContent.replace(
  /export const VOCAB_N5: VocabItem\[\] = \[/,
  "export const VOCAB_N5: VocabItem[] = [\n" + newObjects + ",\n"
);

fs.writeFileSync(filePath, fileContent, 'utf8');
console.log('Added 100 more N5 Nouns to vocabN5.ts successfully!');
