import fs from 'fs';
import path from 'path';

const nouns = [
  { w: '一生懸命', r: 'いっしょうけんめい', rom: 'isshoukenmei', m: 'com todo o esforço; muito arduamente' },
  { w: '糸', r: 'いと', rom: 'ito', m: 'fio; linha' },
  { w: 'ジャム', r: 'ジャム', rom: 'jamu', m: 'geleia' },
  { w: '字', r: 'じ', rom: 'ji', m: 'caractere; letra' },
  { w: '時代', r: 'じだい', rom: 'jidai', m: 'época; era; período' },
  { w: '事故', r: 'じこ', rom: 'jiko', m: 'acidente' },
  { w: '事務所', r: 'じむしょ', rom: 'jimusho', m: 'escritório' },
  { w: '神社', r: 'じんじゃ', rom: 'jinja', m: 'santuário xintoísta' },
  { w: '人口', r: 'じんこう', rom: 'jinkou', m: 'população' },
  { w: '人生', r: 'じんせい', rom: 'jinsei', m: 'vida humana' },
  { w: '地震', r: 'じしん', rom: 'jishin', m: 'terremoto' },
  { w: '辞典', r: 'じてん', rom: 'jiten', m: 'dicionário (referência)' },
  { w: '自由', r: 'じゆう', rom: 'jiyuu', m: 'liberdade' },
  { w: '女性', r: 'じょせい', rom: 'josei', m: 'mulher; sexo feminino' },
  { w: '準備', r: 'じゅんび', rom: 'junbi', m: 'preparação' },
  { w: '十分', r: 'じゅうぶん', rom: 'juubun', m: 'suficiente; bastante' },
  { w: '柔道', r: 'じゅうどう', rom: 'juudou', m: 'judô' },
  { w: '住所', r: 'じゅうしょ', rom: 'juusho', m: 'endereço' },
  { w: 'カーテン', r: 'カーテン', rom: 'kaaten', m: 'cortina' },
  { w: '壁', r: 'かべ', rom: 'kabe', m: 'parede' },
  { w: '課長', r: 'かちょう', rom: 'kachou', m: 'chefe de seção; gerente' },
  { w: '帰り', r: 'かえり', rom: 'kaeri', m: 'retorno; volta' },
  { w: '科学', r: 'かがく', rom: 'kagaku', m: 'ciência' },
  { w: '鏡', r: 'かがみ', rom: 'kagami', m: 'espelho' },
  { w: '海岸', r: 'かいがん', rom: 'kaigan', m: 'litoral; costa' },
  { w: '会議', r: 'かいぎ', rom: 'kaigi', m: 'reunião; conferência' },
  { w: '会議室', r: 'かいぎしつ', rom: 'kaigishitsu', m: 'sala de reunião' },
  { w: '会場', r: 'かいじょう', rom: 'kaijou', m: 'local de evento; salão' },
  { w: '会話', r: 'かいわ', rom: 'kaiwa', m: 'conversa; conversação' },
  { w: '火事', r: 'かじ', rom: 'kaji', m: 'incêndio' },
  { w: '格好', r: 'かっこう', rom: 'kakkou', m: 'aparência; forma' },
  { w: '髪', r: 'かみ', rom: 'kami', m: 'cabelo' },
  { w: '家内', r: 'かない', rom: 'kanai', m: 'minha esposa; dentro de casa' },
  { w: '看護婦', r: 'かんごふ', rom: 'kangofu', m: 'enfermeira (feminino)' },
  { w: '関係', r: 'かんけい', rom: 'kankei', m: 'relação; relacionamento' },
  { w: '簡単', r: 'かんたん', rom: 'kantan', m: 'simples; fácil' },
  { w: '形', r: 'かたち', rom: 'katachi', m: 'forma; formato' },
  { w: '代わり', r: 'かわり', rom: 'kawari', m: 'em vez de; substituto' },
  { w: '毛', r: 'け', rom: 'ke', m: 'pelo; cabelo; lã' },
  { w: 'ケーキ', r: 'ケーキ', rom: 'keeki', m: 'bolo' },
  { w: '怪我', r: 'けが', rom: 'kega', m: 'ferimento; lesão' },
  { w: '計画', r: 'けいかく', rom: 'keikaku', m: 'plano; projeto' },
  { w: '経験', r: 'けいけん', rom: 'keiken', m: 'experiência' },
  { w: '警察', r: 'けいさつ', rom: 'keisatsu', m: 'polícia' },
  { w: '経済', r: 'けいざい', rom: 'keizai', m: 'economia; finanças' },
  { w: '見物', r: 'けんぶつ', rom: 'kenbutsu', m: 'turismo; passeio para ver coisas' },
  { w: '喧嘩', r: 'けんか', rom: 'kenka', m: 'briga; discussão' },
  { w: '研究', r: 'けんきゅう', rom: 'kenkyuu', m: 'pesquisa; estudo' },
  { w: '研究室', r: 'けんきゅうしつ', rom: 'kenkyuushitsu', m: 'laboratório; sala de pesquisa' },
  { w: '消しゴム', r: 'けしゴム', rom: 'keshigomu', m: 'borracha (de apagar)' },
  { w: '景色', r: 'けしき', rom: 'keshiki', m: 'paisagem; cenário' },
  { w: '気', r: 'き', rom: 'ki', m: 'espírito; mente; energia' },
  { w: '気分', r: 'きぶん', rom: 'kibun', m: 'humor; sensação' },
  { w: '機会', r: 'きかい', rom: 'kikai', m: 'oportunidade; chance' },
  { w: '危険', r: 'きけん', rom: 'kiken', m: 'perigo' },
  { w: '気持ち', r: 'きもち', rom: 'kimochi', m: 'sentimento; emoção' },
  { w: '着物', r: 'きもの', rom: 'kimono', m: 'quimono; roupa' },
  { w: '近所', r: 'きんじょ', rom: 'kinjo', m: 'vizinhança; bairro' },
  { w: '絹', r: 'きぬ', rom: 'kinu', m: 'seda' },
  { w: '季節', r: 'きせつ', rom: 'kisetsu', m: 'estação do ano' },
  { w: '汽車', r: 'きしゃ', rom: 'kisha', m: 'trem a vapor' },
  { w: '規則', r: 'きそく', rom: 'kisoku', m: 'regra; regulamento' },
  { w: '子', r: 'こ', rom: 'ko', m: 'criança; filhote' },
  { w: '心', r: 'こころ', rom: 'kokoro', m: 'coração; mente' },
  { w: '国際', r: 'こくさい', rom: 'kokusai', m: 'internacional' },
  { w: '米', r: 'こめ', rom: 'kome', m: 'arroz cru' },
  { w: '今度', r: 'こんど', rom: 'kondo', m: 'desta vez; próxima vez' },
  { w: 'この間', r: 'このあいだ', rom: 'kono aida', m: 'outro dia; recentemente' },
  { w: 'このごろ', r: 'このごろ', rom: 'kono goro', m: 'ultimamente; atualmente' },
  { w: 'コンピュータ', r: 'コンピュータ', rom: 'konpyuuta', m: 'computador' },
  { w: 'コンサート', r: 'コンサート', rom: 'konsaato', m: 'concerto (musical)' },
  { w: '今夜', r: 'こんや', rom: 'konya', m: 'esta noite' },
  { w: '故障', r: 'こしょう', rom: 'koshou', m: 'falha; defeito (quebra)' },
  { w: '答え', r: 'こたえ', rom: 'kotae', m: 'resposta' },
  { w: '小鳥', r: 'ことり', rom: 'kotori', m: 'passarinho' },
  { w: '校長', r: 'こうちょう', rom: 'kouchou', m: 'diretor de escola' },
  { w: '講堂', r: 'こうどう', rom: 'koudou', m: 'auditório' },
  { w: '郊外', r: 'こうがい', rom: 'kougai', m: 'subúrbio; periferia' },
  { w: '講義', r: 'こうぎ', rom: 'kougi', m: 'palestra; aula universitária' },
  { w: '工業', r: 'こうぎょう', rom: 'kougyou', m: 'indústria' },
  { w: '工場', r: 'こうじょう', rom: 'koujou', m: 'fábrica' },
  { w: '高校', r: 'こうこう', rom: 'koukou', m: 'ensino médio' },
  { w: '高校生', r: 'こうこうせい', rom: 'koukousei', m: 'estudante do ensino médio' },
  { w: '公務員', r: 'こうむいん', rom: 'koumuin', m: 'funcionário público' },
  { w: '高等学校', r: 'こうとうがっこう', rom: 'koutougakkou', m: 'escola de ensino médio' },
  { w: '交通', r: 'こうつう', rom: 'koutsuu', m: 'trânsito; transporte' },
  { w: '首', r: 'くび', rom: 'kubi', m: 'pescoço' },
  { w: '雲', r: 'くも', rom: 'kumo', m: 'nuvem' },
  { w: '草', r: 'くさ', rom: 'kusa', m: 'grama; mato' },
  { w: '空気', r: 'くうき', rom: 'kuuki', m: 'ar; atmosfera' },
  { w: '空港', r: 'くうこう', rom: 'kuukou', m: 'aeroporto' },
  { w: '客', r: 'きゃく', rom: 'kyaku', m: 'cliente; hóspede; visitante' },
  { w: '教育', r: 'きょういく', rom: 'kyouiku', m: 'educação' },
  { w: '教会', r: 'きょうかい', rom: 'kyoukai', m: 'igreja' },
  { w: '興味', r: 'きょうみ', rom: 'kyoumi', m: 'interesse' },
  { w: '競争', r: 'きょうそう', rom: 'kyousou', m: 'competição' },
  { w: '急行', r: 'きゅうこう', rom: 'kyuukou', m: 'trem expresso; apressar-se' },
  { w: '漫画', r: 'まんが', rom: 'manga', m: 'mangá; quadrinhos' },
  { w: '真ん中', r: 'まんなか', rom: 'mannaka', m: 'bem no meio; centro' },
  { w: '周り', r: 'まわり', rom: 'mawari', m: 'ao redor; em volta' }
];

const examples = {
  '一生懸命': { jp: '一生懸命勉強します。', r: 'いっしょうけんめい べんきょうします。', rom: 'isshoukenmei benkyoushimasu.', pt: 'Estudo com todo o esforço.' },
  '糸': { jp: '針に糸を通します。', r: 'はりに いとを とおします。', rom: 'hari ni ito o tooshimasu.', pt: 'Passar a linha na agulha.' },
  'ジャム': { jp: 'パンにジャムを塗ります。', r: 'パンに ジャムを ぬります。', rom: 'pan ni jamu o nurimasu.', pt: 'Passar geleia no pão.' },
  '字': { jp: '彼の字はとても綺麗です。', r: 'かれの じは とても きれいです。', rom: 'kare no ji wa totemo kirei desu.', pt: 'A letra dele é muito bonita.' },
  '時代': { jp: '新しい時代が始まりました。', r: 'あたらしい じだいが はじまりました。', rom: 'atarashii jidai ga hajimarimashita.', pt: 'Uma nova era começou.' },
  '事故': { jp: '交差点で事故がありました。', r: 'こうさてんで じこが ありました。', rom: 'kousaten de jiko ga arimashita.', pt: 'Houve um acidente no cruzamento.' },
  '事務所': { jp: '事務所は二階にあります。', r: 'じむしょは にかいに あります。', rom: 'jimusho wa nikai ni arimasu.', pt: 'O escritório fica no segundo andar.' },
  '神社': { jp: 'お正月に神社へ行きました。', r: 'おしょうがつに じんじゃへ いきました。', rom: 'oshougatsu ni jinja e ikimashita.', pt: 'Fui ao santuário no Ano Novo.' },
  '人口': { jp: 'この町の人口は増えています。', r: 'この まちの じんこうは ふえています。', rom: 'kono machi no jinkou wa fueteimasu.', pt: 'A população desta cidade está aumentando.' },
  '人生': { jp: '素晴らしい人生を送りたいです。', r: 'すばらしい じんせいを おくりたいです。', rom: 'subarashii jinsei o okuritai desu.', pt: 'Quero ter (viver) uma vida maravilhosa.' },
  '地震': { jp: '大きな地震がありました。', r: 'おおきな じしんが ありました。', rom: 'ookina jishin ga arimashita.', pt: 'Houve um grande terremoto.' },
  '辞典': { jp: '電子辞典を使います。', r: 'でんし じてんを つかいます。', rom: 'denshi jiten o tsukaimasu.', pt: 'Uso um dicionário eletrônico.' },
  '自由': { jp: '自由な時間が欲しいです。', r: 'じゆうな じかんが ほしいです。', rom: 'jiyuu na jikan ga hoshii desu.', pt: 'Quero ter tempo livre (liberdade).' },
  '女性': { jp: 'あの女性は先生です。', r: 'あの じょせいは せんせいです。', rom: 'ano josei wa sensei desu.', pt: 'Aquela mulher é professora.' },
  '準備': { jp: '旅行の準備をします。', r: 'りょこうの じゅんびを します。', rom: 'ryokou no junbi o shimasu.', pt: 'Fazer os preparativos para a viagem.' },
  '十分': { jp: '時間が十分あります。', r: 'じかんが じゅうぶん あります。', rom: 'jikan ga juubun arimasu.', pt: 'Temos tempo suficiente.' },
  '柔道': { jp: '柔道を習っています。', r: 'じゅうどうを ならっています。', rom: 'juudou o naratteimasu.', pt: 'Estou aprendendo judô.' },
  '住所': { jp: 'ここに住所を書いてください。', r: 'ここに じゅうしょを かいてください。', rom: 'koko ni juusho o kaite kudasai.', pt: 'Por favor, escreva seu endereço aqui.' },
  'カーテン': { jp: '窓のカーテンを閉めます。', r: 'まどの カーテンを しめます。', rom: 'mado no kaaten o shimemasu.', pt: 'Fecho a cortina da janela.' },
  '壁': { jp: '壁に絵を飾りました。', r: 'かべに えを かざりました。', rom: 'kabe ni e o kazarimashita.', pt: 'Decorei a parede com um quadro.' },
  '課長': { jp: '課長に報告します。', r: 'かちょうに ほうこくします。', rom: 'kachou ni houkokushimasu.', pt: 'Relatar ao chefe de seção.' },
  '帰り': { jp: '帰りは遅くなります。', r: 'かえりは おそくなります。', rom: 'kaeri wa osoku narimasu.', pt: 'Meu retorno será tarde.' },
  '科学': { jp: '科学の雑誌を読みます。', r: 'かがくの ざっしを よみます。', rom: 'kagaku no zasshi o yomimasu.', pt: 'Leio revistas de ciência.' },
  '鏡': { jp: '鏡で顔を見ます。', r: 'かがみで かおを みます。', rom: 'kagami de kao o mimasu.', pt: 'Olho o rosto no espelho.' },
  '海岸': { jp: '海岸を散歩しましょう。', r: 'かいがんを さんぽしましょう。', rom: 'kaigan o sanposhimashou.', pt: 'Vamos passear pela costa (litoral).' },
  '会議': { jp: '午後から会議があります。', r: 'ごごから かいぎが あります。', rom: 'gogo kara kaigi ga arimasu.', pt: 'Tem reunião a partir da tarde.' },
  '会議室': { jp: '会議室に集まってください。', r: 'かいぎしつに あつまってください。', rom: 'kaigishitsu ni atsumatte kudasai.', pt: 'Reúnam-se na sala de reunião, por favor.' },
  '会場': { jp: 'コンサートの会場へ行きます。', r: 'コンサートの かいじょうへ いきます。', rom: 'konsaato no kaijou e ikimasu.', pt: 'Ir para o local (salão) do concerto.' },
  '会話': { jp: '英会話を勉強しています。', r: 'えいかいわを べんきょうしています。', rom: 'eikaiwa o benkyoushiteimasu.', pt: 'Estou estudando conversação em inglês.' },
  '火事': { jp: '近所で火事がありました。', r: 'きんじょで かじが ありました。', rom: 'kinjo de kaji ga arimashita.', pt: 'Houve um incêndio na vizinhança.' },
  '格好': { jp: 'あの人は格好がいいです。', r: 'あの ひとは かっこうが いいです。', rom: 'ano hito wa kakkou ga ii desu.', pt: 'Aquela pessoa tem uma boa aparência (é estilosa).' },
  '髪': { jp: '髪を短く切りました。', r: 'かみを みじかく きりました。', rom: 'kami o mijikaku kirimashita.', pt: 'Cortei o cabelo curto.' },
  '家内': { jp: '家内は買い物に出かけました。', r: 'かないは かいものに でかけました。', rom: 'kanai wa kaimono ni dekakemashita.', pt: 'Minha esposa saiu para fazer compras.' },
  '看護婦': { jp: '病院に優しい看護婦さんがいます。', r: 'びょういんに やさしい かんごふさんが います。', rom: 'byouin ni yasashii kangofusan ga imasu.', pt: 'Tem uma enfermeira gentil no hospital.' },
  '関係': { jp: '彼との関係は良好です。', r: 'かれとの かんけいは りょうこうです。', rom: 'kare to no kankei wa ryoukou desu.', pt: 'O relacionamento com ele é bom.' },
  '簡単': { jp: 'このテストは簡単でした。', r: 'この テストは かんたんでした。', rom: 'kono tesuto wa kantan deshita.', pt: 'Este teste foi simples/fácil.' },
  '形': { jp: 'この雲は面白い形をしています。', r: 'この くもは おもしろい かたちを しています。', rom: 'kono kumo wa omoshiroi katachi o shiteimasu.', pt: 'Esta nuvem tem um formato interessante.' },
  '代わり': { jp: '社長の代わりに会議に出ます。', r: 'しゃちょうの かわりに かいぎに でます。', rom: 'shachou no kawari ni kaigi ni demasu.', pt: 'Participarei da reunião no lugar do presidente.' },
  '毛': { jp: '犬の毛が抜けました。', r: 'いぬの けが ぬけました。', rom: 'inu no ke ga nukemashita.', pt: 'Os pelos do cachorro caíram.' },
  'ケーキ': { jp: '誕生日にケーキを食べます。', r: 'たんじょうびに ケーキを たべます。', rom: 'tanjoubi ni keeki o tabemasu.', pt: 'Comer bolo no aniversário.' },
  '怪我': { jp: 'サッカーで怪我をしました。', r: 'サッカーで けがを しました。', rom: 'sakkaa de kega o shimashita.', pt: 'Me machuquei (lesionei) no futebol.' },
  '計画': { jp: '旅行の計画を立てます。', r: 'りょこうの けいかくを たてます。', rom: 'ryokou no keikaku o tatemasu.', pt: 'Fazer o plano da viagem.' },
  '経験': { jp: 'これは良い経験になります。', r: 'これは いい けいけんに なります。', rom: 'kore wa ii keiken ni narimasu.', pt: 'Isso será uma boa experiência.' },
  '警察': { jp: '警察を呼んでください。', r: 'けいさつを よんでください。', rom: 'keisatsu o yonde kudasai.', pt: 'Chame a polícia, por favor.' },
  '経済': { jp: '大学で経済を学びます。', r: 'だいがくで けいざいを まなびます。', rom: 'daigaku de keizai o manabimasu.', pt: 'Aprender economia na universidade.' },
  '見物': { jp: '京都へお寺の見物に行きます。', r: 'きょうとへ おてらの けんぶつに いきます。', rom: 'kyouto e otera no kenbutsu ni ikimasu.', pt: 'Vou a Quioto fazer turismo pelos templos.' },
  '喧嘩': { jp: '兄弟で喧嘩をしました。', r: 'きょうだいで けんかを しました。', rom: 'kyoudai de kenka o shimashita.', pt: 'Briguei (discuti) com meu irmão.' },
  '研究': { jp: '科学の研究をしています。', r: 'かがくの けんきゅうを しています。', rom: 'kagaku no kenkyuu o shiteimasu.', pt: 'Estou fazendo pesquisa em ciência.' },
  '研究室': { jp: '教授は研究室にいます。', r: 'きょうじゅは けんきゅうしつに います。', rom: 'kyouju wa kenkyuushitsu ni imasu.', pt: 'O professor está no laboratório.' },
  '消しゴム': { jp: '消しゴムを貸してください。', r: 'けしゴムを かしてください。', rom: 'keshigomu o kashite kudasai.', pt: 'Empreste-me a borracha, por favor.' },
  '景色': { jp: '山の景色がとても綺麗です。', r: 'やまの けしきが とても きれいです。', rom: 'yama no keshiki ga totemo kirei desu.', pt: 'A paisagem da montanha é muito bonita.' },
  '気': { jp: '気がつくと夜でした。', r: 'きが つくと よるでした。', rom: 'ki ga tsuku to yoru deshita.', pt: 'Quando percebi (quando o espírito notou), já era noite.' },
  '気分': { jp: '今日は気分がいいです。', r: 'きょうは きぶんが いいです。', rom: 'kyou wa kibun ga ii desu.', pt: 'Hoje o humor está bom (Estou me sentindo bem).' },
  '機会': { jp: 'また機会があれば行きましょう。', r: 'また きかいが あれば いきましょう。', rom: 'mata kikai ga areba ikimashou.', pt: 'Se houver oportunidade novamente, vamos.' },
  '危険': { jp: 'ここは危険だから入らないで。', r: 'ここは きけんだから はいらないで。', rom: 'koko wa kiken dakara hairanaide.', pt: 'Como aqui é perigoso, não entre.' },
  '気持ち': { jp: '感謝の気持ちを伝えます。', r: 'かんしゃの きもちを つたえます。', rom: 'kansha no kimochi o tsutaemasu.', pt: 'Transmitir o sentimento de gratidão.' },
  '着物': { jp: 'お祭りで着物を着ます。', r: 'おまつりで きものを きます。', rom: 'omatsuri de kimono o kimasu.', pt: 'Vou vestir um quimono no festival.' },
  '近所': { jp: '近所の人に挨拶します。', r: 'きんじょの ひとに あいさつします。', rom: 'kinjo no hito ni aisatsushimasu.', pt: 'Cumprimento as pessoas da vizinhança.' },
  '絹': { jp: 'このスカーフは絹でできています。', r: 'この スカーフは きぬで できています。', rom: 'kono sukaafu wa kinu de dekiteimasu.', pt: 'Este cachecol é feito de seda.' },
  '季節': { jp: '日本には四つの季節があります。', r: 'にほんには よっつの きせつが あります。', rom: 'nihon ni wa yottsu no kisetsu ga arimasu.', pt: 'O Japão tem quatro estações.' },
  '汽車': { jp: '汽車に乗って旅行します。', r: 'きしゃに のって りょこうします。', rom: 'kisha ni notte ryokoushimasu.', pt: 'Viajar pegando um trem a vapor.' },
  '規則': { jp: '学校の規則を守ります。', r: 'がっこうの きそくを まもります。', rom: 'gakkou no kisoku o mamorimasu.', pt: 'Cumprir as regras da escola.' },
  '子': { jp: 'あの子は誰ですか。', r: 'あの こは だれですか。', rom: 'ano ko wa dare desu ka.', pt: 'Quem é aquela criança?' },
  '心': { jp: '心を込めてプレゼントを選びました。', r: 'こころを こめて プレゼントを えらびました。', rom: 'kokoro o komete purezento o erabimashita.', pt: 'Escolhi o presente com todo o coração.' },
  '国際': { jp: '国際問題について考えます。', r: 'こくさい もんだいについて かんがえます。', rom: 'kokusai mondai ni tsuite kangaemasu.', pt: 'Pensar sobre problemas internacionais.' },
  '米': { jp: 'スーパーで米を買いました。', r: 'スーパーで こめを かいました。', rom: 'suupaa de kome o kaimashita.', pt: 'Comprei arroz no supermercado.' },
  '今度': { jp: '今度の日曜日は暇ですか。', r: 'こんどの にちようびは ひまですか。', rom: 'kondo no nichiyoubi wa hima desu ka.', pt: 'Você está livre no próximo domingo?' },
  'この間': { jp: 'この間はありがとうございました。', r: 'このあいだは ありがとうございました。', rom: 'kono aida wa arigatou gozaimashita.', pt: 'Obrigado(a) pelo outro dia.' },
  'このごろ': { jp: 'このごろ寒くなりましたね。', r: 'このごろ さむくなりましたね。', rom: 'kono goro samuku narimashita ne.', pt: 'Ultimamente tem feito frio, né?' },
  'コンピュータ': { jp: '新しいコンピュータを買いました。', r: 'あたらしい コンピュータを かいました。', rom: 'atarashii konpyuuta o kaimashita.', pt: 'Comprei um computador novo.' },
  'コンサート': { jp: '週末にコンサートへ行きます。', r: 'しゅうまつに コンサートへ いきます。', rom: 'shuumatsu ni konsaato e ikimasu.', pt: 'No fim de semana vou a um concerto.' },
  '今夜': { jp: '今夜は月が綺麗です。', r: 'こんやは つきが きれいです。', rom: 'konya wa tsuki ga kirei desu.', pt: 'Esta noite a lua está bonita.' },
  '故障': { jp: '車が故障しました。', r: 'くるまが こしょうしました。', rom: 'kuruma ga koshoushimashita.', pt: 'O carro quebrou (deu defeito).' },
  '答え': { jp: '正しい答えを選んでください。', r: 'ただしい こたえを えらんでください。', rom: 'tadashii kotae o erande kudasai.', pt: 'Por favor, escolha a resposta correta.' },
  '小鳥': { jp: '木の上で小鳥が鳴いています。', r: 'きの うえで ことりが ないています。', rom: 'ki no ue de kotori ga naiteimasu.', pt: 'Os passarinhos estão cantando em cima da árvore.' },
  '校長': { jp: '校長先生のお話を聞きます。', r: 'こうちょうせんせいの おはなしを ききます。', rom: 'kouchousensei no ohanashi o kikimasu.', pt: 'Ouvir a fala do diretor da escola.' },
  '講堂': { jp: '入学式は講堂で行われます。', r: 'にゅうがくしきは こうどうで おこなわれます。', rom: 'nyuugakushiki wa koudou de okonawaremasu.', pt: 'A cerimônia de ingresso é realizada no auditório.' },
  '郊外': { jp: '郊外に家を買いました。', r: 'こうがいに いえを かいました。', rom: 'kougai ni ie o kaimashita.', pt: 'Comprei uma casa no subúrbio.' },
  '講義': { jp: '大学の講義に出席します。', r: 'だいがくの こうぎに しゅっせきします。', rom: 'daigaku no kougi ni shussekishimasu.', pt: 'Comparecer à palestra (aula) da universidade.' },
  '工業': { jp: 'この町は工業が盛んです。', r: 'この まちは こうぎょうが さかんです。', rom: 'kono machi wa kougyou ga sakan desu.', pt: 'Esta cidade tem a indústria próspera.' },
  '工場': { jp: '自動車の工場で働いています。', r: 'じどうしゃの こうじょうで はたらいています。', rom: 'jidousha no koujou de hataraiteimasu.', pt: 'Estou trabalhando em uma fábrica de automóveis.' },
  '高校': { jp: '来年、高校に入学します。', r: 'らいねん、こうこうに にゅうがくします。', rom: 'rainen, koukou ni nyuugakushimasu.', pt: 'Ano que vem entrarei no ensino médio.' },
  '高校生': { jp: '私の兄は高校生です。', r: 'わたしの あには こうこうせいです。', rom: 'watashi no ani wa koukousei desu.', pt: 'Meu irmão mais velho é estudante do ensino médio.' },
  '公務員': { jp: '彼は公務員として働いています。', r: 'かれは こうむいんとして はたらいています。', rom: 'kare wa koumuin to shite hataraiteimasu.', pt: 'Ele trabalha como funcionário público.' },
  '高等学校': { jp: '高等学校を卒業しました。', r: 'こうとうがっこうを そつぎょうしました。', rom: 'koutougakkou o sotsugyoushimashita.', pt: 'Me formei na escola de ensino médio.' },
  '交通': { jp: 'ここは交通が便利です。', r: 'ここは こうつうが べんりです。', rom: 'koko wa koutsuu ga benri desu.', pt: 'Aqui o transporte é prático.' },
  '首': { jp: '首が痛いです。', r: 'くびが いたいです。', rom: 'kubi ga itai desu.', pt: 'Meu pescoço está doendo.' },
  '雲': { jp: '空に雲が多いです。', r: 'そらに くもが おおいです。', rom: 'sora ni kumo ga ooi desu.', pt: 'Há muitas nuvens no céu.' },
  '草': { jp: '庭の草を取ります。', r: 'にわの くさを とります。', rom: 'niwa no kusa o torimasu.', pt: 'Tirar o mato/grama do jardim.' },
  '空気': { jp: '山の空気は綺麗です。', r: 'やまの くうきは きれいです。', rom: 'yama no kuuki wa kirei desu.', pt: 'O ar da montanha é limpo.' },
  '空港': { jp: 'バスで空港へ行きます。', r: 'バスで くうこうへ いきます。', rom: 'basu de kuukou e ikimasu.', pt: 'Vou de ônibus para o aeroporto.' },
  '客': { jp: '店に客がたくさんいます。', r: 'みせに きゃくが たくさん います。', rom: 'mise ni kyaku ga takusan imasu.', pt: 'Há muitos clientes na loja.' },
  '教育': { jp: '子供の教育は大切です。', r: 'こどもの きょういくは たいせつです。', rom: 'kodomo no kyouiku wa taisetsu desu.', pt: 'A educação das crianças é importante.' },
  '教会': { jp: '日曜日に教会へ行きます。', r: 'にちようびに きょうかいへ いきます。', rom: 'nichiyoubi ni kyoukai e ikimasu.', pt: 'Vou à igreja no domingo.' },
  '興味': { jp: '日本の歴史に興味があります。', r: 'にほんの れきしに きょうみが あります。', rom: 'nihon no rekishi ni kyoumi ga arimasu.', pt: 'Tenho interesse na história do Japão.' },
  '競争': { jp: '友達と競争しました。', r: 'ともだちと きょうそうしました。', rom: 'tomodachi to kyousoushimashita.', pt: 'Competi com o meu amigo.' },
  '急行': { jp: '急行電車に乗ります。', r: 'きゅうこう でんしゃに のります。', rom: 'kyuukou densha ni norimasu.', pt: 'Vou pegar o trem expresso.' },
  '漫画': { jp: '日本の漫画が好きです。', r: 'にほんの まんがが すきです。', rom: 'nihon no manga ga suki desu.', pt: 'Gosto de mangás japoneses.' },
  '真ん中': { jp: '部屋の真ん中にテーブルがあります。', r: 'へやの まんなかに テーブルが あります。', rom: 'heya no mannaka ni teeburu ga arimasu.', pt: 'Tem uma mesa bem no centro da sala.' },
  '周り': { jp: '家の周りを掃除します。', r: 'いえの まわりを そうじします。', rom: 'ie no mawari o soujishimasu.', pt: 'Fazer a limpeza ao redor de casa.' }
};

const filePath = path.join(process.cwd(), 'src/data/vocabN4.ts');
let fileContent = fs.readFileSync(filePath, 'utf8');

const newObjects = nouns.map((n, i) => {
  const ex = examples[n.w] || {
    jp: "Exemplo",
    reading: "...",
    rom: "...",
    pt: "..."
  };
  
  const safePt = ex.pt.replace(/'/g, "\\'");

  return "  {\n" +
    "    id: 'n4_noun_batch2_" + Date.now() + "_" + i + "',\n" +
    "    word: '" + n.w + "',\n" +
    "    reading: '" + n.r + "',\n" +
    "    romaji: '" + n.rom + "',\n" +
    "    meaningPt: '" + n.m + "',\n" +
    "    category: 'substantivo',\n" +
    "    jlpt: 'N4',\n" +
    "    categoryLabelPt: 'Substantivo N4',\n" +
    "    exampleSentence: {\n" +
    "      jp: '" + ex.jp + "',\n" +
    "      reading: '" + ex.r + "',\n" +
    "      romaji: '" + ex.rom + "',\n" +
    "      meaningPt: '" + safePt + "'\n" +
    "    }\n" +
    "  }";
}).join(',\n');

fileContent = fileContent.replace(
  /export const VOCAB_N4: VocabItem\[\] = \[/,
  "export const VOCAB_N4: VocabItem[] = [\n" + newObjects + ",\n"
);

fs.writeFileSync(filePath, fileContent, 'utf8');
console.log('Added 100 more N4 Nouns to vocabN4.ts successfully!');
