import fs from 'fs';
import path from 'path';

const verbs = [
  { w: '浴びる', r: 'あびる', rom: 'abiru', m: 'tomar banho', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '上げる', r: 'あげる', rom: 'ageru', m: 'elevar; levantar; dar', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '開ける', r: 'あける', rom: 'akeru', m: 'abrir', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '開く', r: 'あく', rom: 'aku', m: 'abrir (intransitivo)', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '洗う', r: 'あらう', rom: 'arau', m: 'lavar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: 'ある', r: 'ある', rom: 'aru', m: 'ser; existir; ter', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '歩く', r: 'あるく', rom: 'aruku', m: 'andar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '遊ぶ', r: 'あそぶ', rom: 'asobu', m: 'brincar; jogar; divertir-se', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '会う', r: 'あう', rom: 'au', m: 'encontrar-se', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '勉強する', r: 'べんきょうする', rom: 'benkyousuru', m: 'estudar', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '違う', r: 'ちがう', rom: 'chigau', m: 'diferir; estar errado', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '出す', r: 'だす', rom: 'dasu', m: 'tirar; entregar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '出かける', r: 'でかける', rom: 'dekakeru', m: 'sair', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '電話する', r: 'でんわする', rom: 'denwasuru', m: 'telefonar', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '出る', r: 'でる', rom: 'deru', m: 'sair; aparecer', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '吹く', r: 'ふく', rom: 'fuku', m: 'soprar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '降る', r: 'ふる', rom: 'furu', m: 'chover; nevar (cair do céu)', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '入る', r: 'はいる', rom: 'hairu', m: 'entrar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '始まる', r: 'はじまる', rom: 'hajimaru', m: 'começar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '履く', r: 'はく', rom: 'haku', m: 'vestir (da cintura para baixo); calçar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '話す', r: 'はなす', rom: 'hanasu', m: 'falar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '晴れる', r: 'はれる', rom: 'hareru', m: 'fazer sol; tempo limpar', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '貼る', r: 'はる', rom: 'haru', m: 'colar; fixar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '走る', r: 'はしる', rom: 'hashiru', m: 'correr', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '働く', r: 'はたらく', rom: 'hataraku', m: 'trabalhar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '引く', r: 'ひく', rom: 'hiku', m: 'puxar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '弾く', r: 'ひく', rom: 'hiku', m: 'tocar (instrumento de corda/teclado)', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '行く', r: 'いく', rom: 'iku', m: 'ir', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '入れる', r: 'いれる', rom: 'ireru', m: 'colocar dentro; inserir', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '要る', r: 'いる', rom: 'iru', m: 'precisar; ser necessário', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '居る', r: 'いる', rom: 'iru', m: 'estar; existir (seres vivos)', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '言う', r: 'いう', rom: 'iu', m: 'dizer', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '授業する', r: 'じゅぎょうする', rom: 'jugyousuru', m: 'dar aula; ter aula', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '帰る', r: 'かえる', rom: 'kaeru', m: 'voltar (para casa)', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '返す', r: 'かえす', rom: 'kaesu', m: 'devolver', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '掛かる', r: 'かかる', rom: 'kakaru', m: 'levar (tempo/dinheiro)', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '掛ける', r: 'かける', rom: 'kakeru', m: 'pendurar; ligar (telefone); sentar', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '書く', r: 'かく', rom: 'kaku', m: 'escrever; desenhar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '借りる', r: 'かりる', rom: 'kariru', m: 'emprestar (pegar emprestado)', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '貸す', r: 'かす', rom: 'kasu', m: 'emprestar (para alguém)', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '買う', r: 'かう', rom: 'kau', m: 'comprar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '結婚する', r: 'けっこんする', rom: 'kekkonsuru', m: 'casar-se', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '消す', r: 'けす', rom: 'kesu', m: 'apagar; desligar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '消える', r: 'きえる', rom: 'kieru', m: 'desaparecer; apagar-se', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '聞く', r: 'きく', rom: 'kiku', m: 'ouvir; perguntar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '切る', r: 'きる', rom: 'kiru', m: 'cortar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '着る', r: 'きる', rom: 'kiru', m: 'vestir (da cintura para cima)', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '困る', r: 'こまる', rom: 'komaru', m: 'ter problemas; estar em apuros', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: 'コピーする', r: 'コピーする', rom: 'kopiisuru', m: 'fazer cópia; fotocopiar', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '答える', r: 'こたえる', rom: 'kotaeru', m: 'responder', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '曇る', r: 'くもる', rom: 'kumoru', m: 'ficar nublado', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '来る', r: 'くる', rom: 'kuru', m: 'vir', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '曲がる', r: 'まがる', rom: 'magaru', m: 'virar; dobrar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '待つ', r: 'まつ', rom: 'matsu', m: 'esperar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '磨く', r: 'みがく', rom: 'migaku', m: 'escovar (dentes); polir', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '見る', r: 'みる', rom: 'miru', m: 'ver; assistir; olhar', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '見せる', r: 'みせる', rom: 'miseru', m: 'mostrar', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '持つ', r: 'もつ', rom: 'motsu', m: 'segurar; ter', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '鳴く', r: 'なく', rom: 'naku', m: 'fazer som de animal (latir, miar, etc)', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '無くす', r: 'なくす', rom: 'nakusu', m: 'perder', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '並べる', r: 'ならべる', rom: 'naraberu', m: 'enfileirar; alinhar', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '並ぶ', r: 'ならぶ', rom: 'narabu', m: 'fazer fila', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '習う', r: 'ならう', rom: 'narau', m: 'aprender (de alguém)', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '寝る', r: 'ねる', rom: 'neru', m: 'dormir', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '登る', r: 'のぼる', rom: 'noboru', m: 'escalar; subir', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '飲む', r: 'のむ', rom: 'nomu', m: 'beber', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '乗る', r: 'のる', rom: 'noru', m: 'andar em; embarcar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '脱ぐ', r: 'ぬぐ', rom: 'nugu', m: 'tirar (a roupa)', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '覚える', r: 'おぼえる', rom: 'oboeru', m: 'lembrar; memorizar', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '起きる', r: 'おきる', rom: 'okiru', m: 'acordar; levantar-se', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '置く', r: 'おく', rom: 'oku', m: 'colocar; pôr', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '降りる', r: 'おりる', rom: 'oriru', m: 'descer (de um veículo)', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '教える', r: 'おしえる', rom: 'oshieru', m: 'ensinar', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '押す', r: 'おす', rom: 'osu', m: 'apertar; empurrar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '終わる', r: 'おわる', rom: 'owaru', m: 'terminar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '泳ぐ', r: 'およぐ', rom: 'oyogu', m: 'nadar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '練習する', r: 'れんしゅうする', rom: 'renshuusuru', m: 'praticar', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '旅行する', r: 'りょこうする', rom: 'ryokousuru', m: 'viajar', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '料理する', r: 'りょうりする', rom: 'ryourisuru', m: 'cozinhar', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '咲く', r: 'さく', rom: 'saku', m: 'florescer', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '散歩する', r: 'さんぽする', rom: 'sanposuru', m: 'passear (a pé)', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '差す', r: 'さす', rom: 'sasu', m: 'abrir guarda-chuva', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '洗濯する', r: 'せんたくする', rom: 'sentakusuru', m: 'lavar roupa', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '仕事する', r: 'しごとする', rom: 'shigotosuru', m: 'trabalhar', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '閉まる', r: 'しまる', rom: 'shimaru', m: 'fechar (intransitivo)', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '閉める', r: 'しめる', rom: 'shimeru', m: 'fechar', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '締める', r: 'しめる', rom: 'shimeru', m: 'apertar (cinto); amarrar', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '死ぬ', r: 'しぬ', rom: 'shinu', m: 'morrer', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '知る', r: 'しる', rom: 'shiru', m: 'saber; conhecer', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '質問する', r: 'しつもんする', rom: 'shitsumonsuru', m: 'perguntar; fazer uma pergunta', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '掃除する', r: 'そうじする', rom: 'soujisuru', m: 'fazer faxina; limpar', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '住む', r: 'すむ', rom: 'sumu', m: 'morar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '吸う', r: 'すう', rom: 'suu', m: 'fumar; inspirar/sugar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '座る', r: 'すわる', rom: 'suwaru', m: 'sentar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '食べる', r: 'たべる', rom: 'taberu', m: 'comer', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '頼む', r: 'たのむ', rom: 'tanomu', m: 'pedir', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '立つ', r: 'たつ', rom: 'tatsu', m: 'ficar de pé; levantar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: 'テストする', r: 'テストする', rom: 'tesutosuru', m: 'fazer teste', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '飛ぶ', r: 'とぶ', rom: 'tobu', m: 'voar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '止まる', r: 'とまる', rom: 'tomaru', m: 'parar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' }
];

const examples = {
  '浴びる': { jp: 'シャワーを浴びます。', r: 'シャワーを あびます。', rom: 'shawaa o abimasu.', pt: 'Tomo banho (de chuveiro).' },
  '上げる': { jp: '手を上げてください。', r: 'てを あげてください。', rom: 'te o agete kudasai.', pt: 'Por favor, levante a mão.' },
  '開ける': { jp: '窓を開けます。', r: 'まどを あけます。', rom: 'mado o akemasu.', pt: 'Vou abrir a janela.' },
  '開く': { jp: 'ドアが開きます。', r: 'ドアが あきます。', rom: 'doa ga akimasu.', pt: 'A porta abre.' },
  '洗う': { jp: '手を洗います。', r: 'てを あらいます。', rom: 'te o araimasu.', pt: 'Lavo as mãos.' },
  'ある': { jp: '机の上に本があります。', r: 'つくえの うえに ほんが あります。', rom: 'tsukue no ue ni hon ga arimasu.', pt: 'Há um livro em cima da mesa.' },
  '歩く': { jp: '駅まで歩きます。', r: 'えきまで あるきます。', rom: 'eki made arukimasu.', pt: 'Ando (caminho) até a estação.' },
  '遊ぶ': { jp: '公園で遊びます。', r: 'こうえんで あそびます。', rom: 'kouen de asobimasu.', pt: 'Brinco no parque.' },
  '会う': { jp: '友達に会います。', r: 'ともだちに あいます。', rom: 'tomodachi ni aimasu.', pt: 'Encontro um amigo.' },
  '勉強する': { jp: '日本語を勉強します。', r: 'にほんごを べんきょうします。', rom: 'nihongo o benkyoushimasu.', pt: 'Estudo japonês.' },
  '違う': { jp: 'それは違います。', r: 'それは ちがいます。', rom: 'sore wa chigaimasu.', pt: 'Isso está errado (difere).' },
  '出す': { jp: '手紙を出します。', r: 'てがみを だします。', rom: 'tegami o dashimasu.', pt: 'Entrego a carta (ou tiro para fora).' },
  '出かける': { jp: '明日出かけます。', r: 'あした でかけます。', rom: 'ashita dekakemasu.', pt: 'Vou sair amanhã.' },
  '電話する': { jp: '母に電話します。', r: 'ははに でんわします。', rom: 'haha ni denwashimasu.', pt: 'Ligo para a minha mãe.' },
  '出る': { jp: '部屋を出ます。', r: 'へやを でます。', rom: 'heya o demasu.', pt: 'Saio do quarto.' },
  '吹く': { jp: '風が吹いています。', r: 'かぜが ふいています。', rom: 'kaze ga fuiteimasu.', pt: 'O vento está soprando.' },
  '降る': { jp: '雨が降っています。', r: 'あめが ふっています。', rom: 'ame ga futteimasu.', pt: 'Está chovendo.' },
  '入る': { jp: '部屋に入ります。', r: 'へやに はいります。', rom: 'heya ni hairimasu.', pt: 'Entro na sala.' },
  '始まる': { jp: '映画が始まります。', r: 'えいがが はじまります。', rom: 'eiga ga hajimarimasu.', pt: 'O filme vai começar.' },
  '履く': { jp: '靴を履きます。', r: 'くつを はきます。', rom: 'kutsu o hakimasu.', pt: 'Calço os sapatos.' },
  '話す': { jp: '日本語で話します。', r: 'にほんごで はなします。', rom: 'nihongo de hanashimasu.', pt: 'Falo em japonês.' },
  '晴れる': { jp: '今日はよく晴れています。', r: 'きょうは よく はれています。', rom: 'kyou wa yoku hareteimasu.', pt: 'Hoje o tempo está bem ensolarado.' },
  '貼る': { jp: '切手を貼ります。', r: 'きってを はります。', rom: 'kitte o harimasu.', pt: 'Colo um selo.' },
  '走る': { jp: '駅まで走ります。', r: 'えきまで はしります。', rom: 'eki made hashirimasu.', pt: 'Corro até a estação.' },
  '働く': { jp: '会社で働きます。', r: 'かいしゃで はたらきます。', rom: 'kaisha de hatarakimasu.', pt: 'Trabalho na empresa.' },
  '引く': { jp: 'ドアを引きます。', r: 'ドアを ひきます。', rom: 'doa o hikimasu.', pt: 'Puxo a porta.' },
  '弾く': { jp: 'ピアノを弾きます。', r: 'ピアノを ひきます。', rom: 'piano o hikimasu.', pt: 'Toco piano.' },
  '行く': { jp: '学校へ行きます。', r: 'がっこうへ いきます。', rom: 'gakkou e ikimasu.', pt: 'Vou para a escola.' },
  '入れる': { jp: 'コーヒーに砂糖を入れます。', r: 'コーヒーに さとうを いれます。', rom: 'koohii ni satou o iremasu.', pt: 'Coloco açúcar no café.' },
  '要る': { jp: 'お金が要ります。', r: 'おかねが いります。', rom: 'okane ga irimasu.', pt: 'Preciso de dinheiro.' },
  '居る': { jp: '犬がいます。', r: 'いぬが います。', rom: 'inu ga imasu.', pt: 'Tem um cachorro.' },
  '言う': { jp: '「はい」と言いました。', r: '「はい」と いいました。', rom: '"hai" to iimashita.', pt: 'Disse "Sim".' },
  '授業する': { jp: '今、授業しています。', r: 'いま、じゅぎょうしています。', rom: 'ima, jugyoushiteimasu.', pt: 'Agora estou em aula / dando aula.' },
  '帰る': { jp: '家に帰ります。', r: 'いえに かえります。', rom: 'ie ni kaerimasu.', pt: 'Volto para casa.' },
  '返す': { jp: '本を返します。', r: 'ほんを かえします。', rom: 'hon o kaeshimasu.', pt: 'Devolvo o livro.' },
  '掛かる': { jp: '一時間掛かります。', r: 'いちじかん かかります。', rom: 'ichijikan kakarimasu.', pt: 'Leva (demora) uma hora.' },
  '掛ける': { jp: '友達に電話を掛けます。', r: 'ともだちに でんわを かけます。', rom: 'tomodachi ni denwa o kakemasu.', pt: 'Ligo (faço uma ligação) para um amigo.' },
  '書く': { jp: '手紙を書きます。', r: 'てがみを かきます。', rom: 'tegami o kakimasu.', pt: 'Escrevo uma carta.' },
  '借りる': { jp: '本を借ります。', r: 'ほんを かります。', rom: 'hon o karimasu.', pt: 'Pego um livro emprestado.' },
  '貸す': { jp: 'ペンを貸してください。', r: 'ペンを かしてください。', rom: 'pen o kashite kudasai.', pt: 'Me empreste uma caneta, por favor.' },
  '買う': { jp: '新しい靴を買います。', r: 'あたらしい くつを かいます。', rom: 'atarashii kutsu o kaimasu.', pt: 'Compro sapatos novos.' },
  '結婚する': { jp: '来年、結婚します。', r: 'らいねん、けっこんします。', rom: 'rainen, kekkonshimasu.', pt: 'Ano que vem vou me casar.' },
  '消す': { jp: '電気を消します。', r: 'でんきを けします。', rom: 'denki o keshimasu.', pt: 'Desligo a luz (apago a luz).' },
  '消える': { jp: '電気が消えました。', r: 'でんきが きえました。', rom: 'denki ga kiemashita.', pt: 'A luz se apagou.' },
  '聞く': { jp: '音楽を聞きます。', r: 'おんがくを ききます。', rom: 'ongaku o kikimasu.', pt: 'Escuto música.' },
  '切る': { jp: '紙を切ります。', r: 'かみを きります。', rom: 'kami o kirimasu.', pt: 'Corto o papel.' },
  '着る': { jp: 'シャツを着ます。', r: 'シャツを きます。', rom: 'shatsu o kimasu.', pt: 'Visto a camisa.' },
  '困る': { jp: '道がわからなくて困りました。', r: 'みちが わからなくて こまりました。', rom: 'michi ga wakaranakute komarimashita.', pt: 'Fiquei com problemas (em apuros) porque não sabia o caminho.' },
  'コピーする': { jp: '書類をコピーします。', r: 'しょるいを コピーします。', rom: 'shorui o kopiishimasu.', pt: 'Vou tirar cópia dos documentos.' },
  '答える': { jp: '質問に答えます。', r: 'しつもんに こたえます。', rom: 'shitsumon ni kotaemasu.', pt: 'Respondo à pergunta.' },
  '曇る': { jp: '空が曇ってきました。', r: 'そらが くもってきました。', rom: 'sora ga kumottekimashita.', pt: 'O céu começou a ficar nublado.' },
  '来る': { jp: '友達が家に来ます。', r: 'ともだちが いえに きます。', rom: 'tomodachi ga ie ni kimasu.', pt: 'Um amigo virá em casa.' },
  '曲がる': { jp: '右に曲がります。', r: 'みぎに まがります。', rom: 'migi ni magarimasu.', pt: 'Viro à direita.' },
  '待つ': { jp: '駅で友達を待ちます。', r: 'えきで ともだちを まちます。', rom: 'eki de tomodachi o machimasu.', pt: 'Espero o amigo na estação.' },
  '磨く': { jp: '歯を磨きます。', r: 'はを みがきます。', rom: 'ha o migakimasu.', pt: 'Escovo os dentes.' },
  '見る': { jp: '映画を見ます。', r: 'えいがを みます。', rom: 'eiga o mimasu.', pt: 'Assisto ao filme.' },
  '見せる': { jp: '写真を見せます。', r: 'しゃしんを みせます。', rom: 'shashin o misemasu.', pt: 'Mostro a foto.' },
  '持つ': { jp: 'カバンを持ちます。', r: 'カバンを もちます。', rom: 'kaban o mochimasu.', pt: 'Seguro a bolsa.' },
  '鳴く': { jp: '犬が鳴いています。', r: 'いぬが ないています。', rom: 'inu ga naiteimasu.', pt: 'O cachorro está latindo.' },
  '無くす': { jp: '鍵を無くしました。', r: 'かぎを なくしました。', rom: 'kagi o nakushimashita.', pt: 'Perdi a chave.' },
  '並べる': { jp: '椅子を並べます。', r: 'いすを ならべます。', rom: 'isu o narabemasu.', pt: 'Enfileiro as cadeiras.' },
  '並ぶ': { jp: 'バス停に並びます。', r: 'バスていに ならびます。', rom: 'basutei ni narabimasu.', pt: 'Faço fila no ponto de ônibus.' },
  '習う': { jp: '先生に日本語を習います。', r: 'せんせいに にほんごを ならいます。', rom: 'sensei ni nihongo o naraimasu.', pt: 'Aprendo japonês com o professor.' },
  '寝る': { jp: '夜十時に寝ます。', r: 'よる じゅうじに ねます。', rom: 'yoru juuji ni nemasu.', pt: 'Durmo às dez horas da noite.' },
  '登る': { jp: '山に登ります。', r: 'やまに のぼります。', rom: 'yama ni noborimasu.', pt: 'Escalo (subo) a montanha.' },
  '飲む': { jp: '水を飲みます。', r: 'みずを のみます。', rom: 'mizu o nomimasu.', pt: 'Bebo água.' },
  '乗る': { jp: '電車に乗ります。', r: 'でんしゃに のります。', rom: 'densha ni norimasu.', pt: 'Pego (embarco no) trem.' },
  '脱ぐ': { jp: '靴を脱ぎます。', r: 'くつを ぬぎます。', rom: 'kutsu o nugimasu.', pt: 'Tiro os sapatos.' },
  '覚える': { jp: '漢字を覚えます。', r: 'かんじを おぼえます。', rom: 'kanji o oboemasu.', pt: 'Memorizo (aprendo) os kanjis.' },
  '起きる': { jp: '朝六時に起きます。', r: 'あさ ろくじに おきます。', rom: 'asa rokuji ni okimasu.', pt: 'Acordo às seis da manhã.' },
  '置く': { jp: '机の上に本を置きます。', r: 'つくえの うえに ほんを おきます。', rom: 'tsukue no ue ni hon o okimasu.', pt: 'Coloco o livro em cima da mesa.' },
  '降りる': { jp: 'バスを降ります。', r: 'バスを おります。', rom: 'basu o orimasu.', pt: 'Desço do ônibus.' },
  '教える': { jp: '英語を教えます。', r: 'えいごを おしえます。', rom: 'eigo o oshiemasu.', pt: 'Ensino inglês.' },
  '押す': { jp: 'ボタンを押します。', r: 'ボタンを おします。', rom: 'botan o oshimasu.', pt: 'Aperto o botão.' },
  '終わる': { jp: '仕事が終わりました。', r: 'しごとが おわりました。', rom: 'shigoto ga owarimashita.', pt: 'O trabalho terminou.' },
  '泳ぐ': { jp: 'プールで泳ぎます。', r: 'プールで およぎます。', rom: 'puuru de oyogimasu.', pt: 'Nado na piscina.' },
  '練習する': { jp: '毎日ピアノを練習します。', r: 'まいにち ピアノを れんしゅうします。', rom: 'mainichi piano o renshuushimasu.', pt: 'Pratico piano todos os dias.' },
  '旅行する': { jp: '来月、日本を旅行します。', r: 'らいげつ、にほんを りょこうします。', rom: 'raigetsu, nihon o ryokoushimasu.', pt: 'No próximo mês, vou viajar pelo Japão.' },
  '料理する': { jp: '夕食を料理します。', r: 'ゆうしょくを りょうりします。', rom: 'yuushoku o ryourishimasu.', pt: 'Vou cozinhar o jantar.' },
  '咲く': { jp: '桜が咲きました。', r: 'さくらが さきました。', rom: 'sakura ga sakimashita.', pt: 'As flores de cerejeira floresceram.' },
  '散歩する': { jp: '朝、公園を散歩します。', r: 'あさ、こうえんを さんぽします。', rom: 'asa, kouen o sanposhimasu.', pt: 'De manhã, eu passeio pelo parque.' },
  '差す': { jp: '傘を差します。', r: 'かさを さします。', rom: 'kasa o sashimasu.', pt: 'Abro o guarda-chuva.' },
  '洗濯する': { jp: '服を洗濯します。', r: 'ふくを せんたくします。', rom: 'fuku o sentakushimasu.', pt: 'Lavo as roupas.' },
  '仕事する': { jp: '今日もしっかり仕事します。', r: 'きょうも しっかり しごとする。', rom: 'kyou mo shikkari shigoto shimasu.', pt: 'Trabalho firme hoje também.' },
  '閉まる': { jp: 'ドアが閉まります。', r: 'ドアが しまります。', rom: 'doa ga shimarimasu.', pt: 'A porta se fecha.' },
  '閉める': { jp: '窓を閉めます。', r: 'まどを しめます。', rom: 'mado o shimemasu.', pt: 'Fecho a janela.' },
  '締める': { jp: 'シートベルトを締めます。', r: 'シートベルトを しめます。', rom: 'shiitoberuto o shimemasu.', pt: 'Aperto (amarro) o cinto de segurança.' },
  '死ぬ': { jp: '花が死にました。', r: 'はなが しにました。', rom: 'hana ga shinimashita.', pt: 'A flor morreu.' },
  '知る': { jp: 'そのニュースを知っています。', r: 'その ニュースを しっています。', rom: 'sono nyuusu o shitteimasu.', pt: 'Eu sei daquela notícia.' },
  '質問する': { jp: '先生に質問します。', r: 'せんせいに しつもんします。', rom: 'sensei ni shitsumonshimasu.', pt: 'Faço uma pergunta ao professor.' },
  '掃除する': { jp: '部屋を掃除します。', r: 'へやを そうじします。', rom: 'heya o soujishimasu.', pt: 'Limpo o quarto (faço faxina).' },
  '住む': { jp: '東京に住んでいます。', r: 'とうきょうに すんでいます。', rom: 'toukyou ni sundeimasu.', pt: 'Moro em Tóquio.' },
  '吸う': { jp: 'タバコを吸いますか。', r: 'タバコを すいますか。', rom: 'tabako o suimasu ka.', pt: 'Você fuma (suga cigarro)?' },
  '座る': { jp: '椅子に座ります。', r: 'いすに すわります。', rom: 'isu ni suwarimasu.', pt: 'Sento-me na cadeira.' },
  '食べる': { jp: 'ご飯を食べます。', r: 'ごはんを たべます。', rom: 'gohan o tabemasu.', pt: 'Como a comida.' },
  '頼む': { jp: '友達に頼みます。', r: 'ともだちに たのみます。', rom: 'tomodachi ni tanomimasu.', pt: 'Faço um pedido a um amigo.' },
  '立つ': { jp: '立ってください。', r: 'たってください。', rom: 'tatte kudasai.', pt: 'Fique de pé, por favor.' },
  'テストする': { jp: 'システムをテストします。', r: 'システムを テストします。', rom: 'shisutemu o tesutoshimasu.', pt: 'Testar o sistema.' },
  '飛ぶ': { jp: '鳥が飛んでいます。', r: 'とりが とんでいます。', rom: 'tori ga tondeimasu.', pt: 'O pássaro está voando.' },
  '止まる': { jp: '車が止まりました。', r: 'くるまが とまりました。', rom: 'kuruma ga tomarimashita.', pt: 'O carro parou.' }
};

const filePath = path.join(process.cwd(), 'src/data/vocabN5.ts');
let fileContent = fs.readFileSync(filePath, 'utf8');

const newObjects = verbs.map((n, i) => {
  const ex = examples[n.w] || {
    jp: "Exemplo",
    reading: "...",
    rom: "...",
    pt: "..."
  };
  
  const safePt = ex.pt.replace(/'/g, "\\'");
  const safeRom = ex.rom.replace(/'/g, "\\'");

  return "  {\n" +
    "    id: 'n5_verb_batch1_" + Date.now() + "_" + i + "',\n" +
    "    word: '" + n.w + "',\n" +
    "    reading: '" + n.r.replace(/'/g, "\\'") + "',\n" +
    "    romaji: '" + n.rom.replace(/'/g, "\\'") + "',\n" +
    "    meaningPt: '" + n.m.replace(/'/g, "\\'") + "',\n" +
    "    category: '" + n.cat + "',\n" +
    "    jlpt: 'N5',\n" +
    "    categoryLabelPt: '" + n.catLabel + "',\n" +
    "    exampleSentence: {\n" +
    "      jp: '" + ex.jp + "',\n" +
    "      reading: '" + ex.r.replace(/'/g, "\\'") + "',\n" +
    "      romaji: '" + safeRom + "',\n" +
    "      meaningPt: '" + safePt + "'\n" +
    "    }\n" +
    "  }";
}).join(',\n');

fileContent = fileContent.replace(
  /export const VOCAB_N5: VocabItem\[\] = \[/,
  "export const VOCAB_N5: VocabItem[] = [\n" + newObjects + ",\n"
);

fs.writeFileSync(filePath, fileContent, 'utf8');
console.log('Added 100 N5 Verbs to vocabN5.ts successfully!');
