import fs from 'fs';
import path from 'path';

const newKanjis = [
  { id: 'k_n2_add10_1', kanji: '針', onyomi: ['シン (shin)'], kunyomi: ['はり (hari)'], meaningPt: 'Agulha', strokes: 10, radical: '金 (ouro/metal)', jlpt: 'N2', examples: [ { word: '針', reading: 'はり (hari)', meaningPt: 'Agulha' }, { word: '方針', reading: 'ほうしん (houshin)', meaningPt: 'Política / Diretriz' }, { word: '時計の針', reading: 'とけいのはり (tokeinohari)', meaningPt: 'Ponteiro do relógio' } ] },
  { id: 'k_n2_add10_2', kanji: '辛', onyomi: ['シン (shin)'], kunyomi: ['から.い (kara.i)'], meaningPt: 'Picante, Difícil', strokes: 7, radical: '辛 (picante)', jlpt: 'N2', examples: [ { word: '辛い', reading: 'からい (karai)', meaningPt: 'Picante' }, { word: '辛い', reading: 'つらい (tsurai)', meaningPt: 'Doloroso / Difícil' }, { word: '香辛料', reading: 'こうしんりょう (koushinryou)', meaningPt: 'Especiarias / Temperos' } ] },
  { id: 'k_n2_add10_3', kanji: '身', onyomi: ['シン (shin)'], kunyomi: ['み (mi)'], meaningPt: 'Corpo, Si mesmo', strokes: 7, radical: '身 (corpo)', jlpt: 'N2', examples: [ { word: '自身', reading: 'じしん (jishin)', meaningPt: 'A si mesmo / Próprio' }, { word: '出身', reading: 'しゅっしん (shusshin)', meaningPt: 'Origem (cidade natal)' }, { word: '中身', reading: 'なかみ (nakami)', meaningPt: 'Conteúdo / Interior' } ] },
  { id: 'k_n2_add10_4', kanji: '臣', onyomi: ['シン (shin)', 'ジン (jin)'], kunyomi: [], meaningPt: 'Vassalo, Ministro', strokes: 7, radical: '臣 (vassalo/ministro)', jlpt: 'N2', examples: [ { word: '大臣', reading: 'だいじん (daijin)', meaningPt: 'Ministro' }, { word: '総理大臣', reading: 'そうりだいじん (souridaijin)', meaningPt: 'Primeiro-Ministro' }, { word: '家臣', reading: 'かしん (kashin)', meaningPt: 'Vassalo / Criado' } ] },
  { id: 'k_n2_add10_5', kanji: '神', onyomi: ['シン (shin)', 'ジン (jin)'], kunyomi: ['かみ (kami)'], meaningPt: 'Deus', strokes: 9, radical: '示 (mostrar)', jlpt: 'N2', examples: [ { word: '神様', reading: 'かみさま (kamisama)', meaningPt: 'Deus' }, { word: '神社', reading: 'じんじゃ (jinja)', meaningPt: 'Santuário xintoísta' }, { word: '精神', reading: 'せいしん (seishin)', meaningPt: 'Mente / Espírito' } ] },
  { id: 'k_n2_add10_6', kanji: '申', onyomi: ['シン (shin)'], kunyomi: ['もう.す (mou.su)'], meaningPt: 'Dizer (humilde)', strokes: 5, radical: '田 (campo de arroz)', jlpt: 'N2', examples: [ { word: '申す', reading: 'もうす (mousu)', meaningPt: 'Dizer / Chamar-se (humilde)' }, { word: '申し込む', reading: 'もうしこむ (moushikomu)', meaningPt: 'Inscrever-se / Candidatar-se' }, { word: '申告', reading: 'しんこく (shinkoku)', meaningPt: 'Declaração' } ] },
  { id: 'k_n2_add10_7', kanji: '深', onyomi: ['シン (shin)'], kunyomi: ['ふか.い (fuka.i)', 'ふか.まる (fuka.maru)'], meaningPt: 'Profundo', strokes: 11, radical: '水 (água)', jlpt: 'N2', examples: [ { word: '深い', reading: 'ふかい (fukai)', meaningPt: 'Profundo' }, { word: '深夜', reading: 'しんや (shinya)', meaningPt: 'Madrugada / Tarde da noite' }, { word: '深刻', reading: 'しんこく (shinkoku)', meaningPt: 'Grave / Sério' } ] },
  { id: 'k_n2_add10_8', kanji: '寝', onyomi: ['シン (shin)'], kunyomi: ['ね.る (ne.ru)', 'ね.かす (ne.kasu)'], meaningPt: 'Dormir, Deitar-se', strokes: 13, radical: '宀 (telhado)', jlpt: 'N2', examples: [ { word: '寝る', reading: 'ねる (neru)', meaningPt: 'Dormir / Deitar' }, { word: '昼寝', reading: 'ひるね (hirune)', meaningPt: 'Cochilo à tarde' }, { word: '寝室', reading: 'しんしつ (shinshitsu)', meaningPt: 'Quarto (de dormir)' } ] },
  { id: 'k_n2_add10_9', kanji: '信', onyomi: ['シン (shin)'], kunyomi: [], meaningPt: 'Confiança, Crença', strokes: 9, radical: '人 (pessoa)', jlpt: 'N2', examples: [ { word: '信じる', reading: 'しんじる (shinjiru)', meaningPt: 'Acreditar' }, { word: '自信', reading: 'じしん (jishin)', meaningPt: 'Autoconfiança' }, { word: '信号', reading: 'しんごう (shingou)', meaningPt: 'Semáforo / Sinal' } ] },
  { id: 'k_n2_add10_10', kanji: '伸', onyomi: ['シン (shin)'], kunyomi: ['の.びる (no.biru)', 'の.ばす (no.basu)'], meaningPt: 'Esticar, Alongar', strokes: 7, radical: '人 (pessoa)', jlpt: 'N2', examples: [ { word: '伸びる', reading: 'のびる (nobiru)', meaningPt: 'Crescer / Esticar-se' }, { word: '伸ばす', reading: 'のばす (nobasu)', meaningPt: 'Alongar / Esticar (algo)' }, { word: '背伸び', reading: 'せのび (senobi)', meaningPt: 'Ficar na ponta dos pés' } ] },
  { id: 'k_n2_add10_11', kanji: '触', onyomi: ['ショク (shoku)'], kunyomi: ['ふ.れる (fu.reru)', 'さわ.る (sawa.ru)'], meaningPt: 'Tocar', strokes: 13, radical: '角 (chifre)', jlpt: 'N2', examples: [ { word: '触る', reading: 'さわる (sawaru)', meaningPt: 'Tocar (intencionalmente)' }, { word: '触れる', reading: 'ふれる (fureru)', meaningPt: 'Tocar (de leve) / Mencionar' }, { word: '感触', reading: 'かんしょく (kanshoku)', meaningPt: 'Sensação ao toque' } ] },
  { id: 'k_n2_add10_12', kanji: '職', onyomi: ['ショク (shoku)'], kunyomi: [], meaningPt: 'Emprego, Profissão', strokes: 18, radical: '耳 (orelha)', jlpt: 'N2', examples: [ { word: '職業', reading: 'しょくぎょう (shokugyou)', meaningPt: 'Profissão' }, { word: '職場', reading: 'しょくば (shokuba)', meaningPt: 'Local de trabalho' }, { word: '就職', reading: 'しゅうしょく (shuushoku)', meaningPt: 'Conseguir emprego' } ] },
  { id: 'k_n2_add10_13', kanji: '植', onyomi: ['ショク (shoku)'], kunyomi: ['う.える (u.eru)', 'う.わる (u.waru)'], meaningPt: 'Plantar', strokes: 12, radical: '木 (árvore)', jlpt: 'N2', examples: [ { word: '植える', reading: 'うえる (ueru)', meaningPt: 'Plantar' }, { word: '植物', reading: 'しょくぶつ (shokubutsu)', meaningPt: 'Planta / Vegetal' }, { word: '植木', reading: 'うえき (ueki)', meaningPt: 'Planta de vaso/jardim' } ] },
  { id: 'k_n2_add10_14', kanji: '蒸', onyomi: ['ジョウ (jou)'], kunyomi: ['む.す (mu.su)', 'む.れる (mu.reru)'], meaningPt: 'Vapor, Cozinhar a vapor', strokes: 13, radical: '艸 (grama)', jlpt: 'N2', examples: [ { word: '蒸し暑い', reading: 'むしあつい (mushiatsui)', meaningPt: 'Quente e úmido / Abafado' }, { word: '水蒸気', reading: 'すいじょうき (suijouki)', meaningPt: 'Vapor de água' }, { word: '蒸発', reading: 'じょうはつ (jouhatsu)', meaningPt: 'Evaporação' } ] },
  { id: 'k_n2_add10_15', kanji: '畳', onyomi: ['ジョウ (jou)'], kunyomi: ['たたみ (tatami)', 'たた.む (tata.mu)'], meaningPt: 'Tatame, Dobrar', strokes: 12, radical: '田 (campo de arroz)', jlpt: 'N2', examples: [ { word: '畳', reading: 'たたみ (tatami)', meaningPt: 'Tatame (esteira japonesa)' }, { word: '畳む', reading: 'たたむ (tatamu)', meaningPt: 'Dobrar (roupa/guarda-chuva)' }, { word: '四畳半', reading: 'よじょうはん (yojouhan)', meaningPt: 'Quarto de 4.5 tatames' } ] },
  { id: 'k_n2_add10_16', kanji: '状', onyomi: ['ジョウ (jou)'], kunyomi: [], meaningPt: 'Estado, Condição', strokes: 7, radical: '犬 (cachorro)', jlpt: 'N2', examples: [ { word: '状態', reading: 'じょうたい (joutai)', meaningPt: 'Estado / Condição' }, { word: '状況', reading: 'じょうきょう (joukyou)', meaningPt: 'Situação / Circunstâncias' }, { word: '招待状', reading: 'しょうたいじょう (shoutaijou)', meaningPt: 'Convite (cartão)' } ] },
  { id: 'k_n2_add10_17', kanji: '条', onyomi: ['ジョウ (jou)'], kunyomi: [], meaningPt: 'Cláusula, Artigo, Condição', strokes: 7, radical: '木 (árvore)', jlpt: 'N2', examples: [ { word: '条件', reading: 'じょうけん (jouken)', meaningPt: 'Condição / Requisito' }, { word: '条約', reading: 'じょうやく (jouyaku)', meaningPt: 'Tratado / Acordo' }, { word: '箇条書き', reading: 'かじょうがき (kajougaki)', meaningPt: 'Lista de itens' } ] },
  { id: 'k_n2_add10_18', kanji: '情', onyomi: ['ジョウ (jou)'], kunyomi: ['なさ.け (nasa.ke)'], meaningPt: 'Emoção, Informação', strokes: 11, radical: '心 (coração)', jlpt: 'N2', examples: [ { word: '情報', reading: 'じょうほう (jouhou)', meaningPt: 'Informação' }, { word: '感情', reading: 'かんじょう (kanjou)', meaningPt: 'Emoção / Sentimento' }, { word: '事情', reading: 'じじょう (jijou)', meaningPt: 'Circunstâncias / Razões' } ] },
  { id: 'k_n2_add10_19', kanji: '常', onyomi: ['ジョウ (jou)'], kunyomi: ['つね (tsune)', 'とこ (toko)'], meaningPt: 'Comum, Normal', strokes: 11, radical: '巾 (tecido/toalha)', jlpt: 'N2', examples: [ { word: '日常', reading: 'にちじょう (nichijou)', meaningPt: 'Cotiano / Dia a dia' }, { word: '常識', reading: 'じょうしき (joushiki)', meaningPt: 'Senso comum' }, { word: '常に', reading: 'つねに (tsuneni)', meaningPt: 'Sempre' } ] },
  { id: 'k_n2_add10_20', kanji: '城', onyomi: ['ジョウ (jou)'], kunyomi: ['しろ (shiro)'], meaningPt: 'Castelo', strokes: 9, radical: '土 (terra)', jlpt: 'N2', examples: [ { word: '城', reading: 'しろ (shiro)', meaningPt: 'Castelo' }, { word: '大阪城', reading: 'おおさかじょう (oosakajou)', meaningPt: 'Castelo de Osaka' } ] },
  { id: 'k_n2_add10_21', kanji: '賞', onyomi: ['ショウ (shou)'], kunyomi: [], meaningPt: 'Prêmio, Recompensa', strokes: 15, radical: '貝 (concha/moeda)', jlpt: 'N2', examples: [ { word: '賞', reading: 'しょう (shou)', meaningPt: 'Prêmio' }, { word: '賞金', reading: 'しょうきん (shoukin)', meaningPt: 'Prêmio em dinheiro' }, { word: '賞品', reading: 'しょうひん (shouhin)', meaningPt: 'Prêmio (objeto)' } ] },
  { id: 'k_n2_add10_22', kanji: '象', onyomi: ['ショウ (shou)', 'ゾウ (zou)'], kunyomi: [], meaningPt: 'Elefante, Imagem', strokes: 12, radical: '豕 (porco)', jlpt: 'N2', examples: [ { word: '象', reading: 'ぞう (zou)', meaningPt: 'Elefante' }, { word: '印象', reading: 'いんしょう (inshou)', meaningPt: 'Impressão (sobre algo/alguém)' }, { word: '対象', reading: 'たいしょう (taishou)', meaningPt: 'Alvo / Objeto (de estudo)' } ] },
  { id: 'k_n2_add10_23', kanji: '紹', onyomi: ['ショウ (shou)'], kunyomi: [], meaningPt: 'Apresentar', strokes: 11, radical: '糸 (fio)', jlpt: 'N2', examples: [ { word: '紹介', reading: 'しょうかい (shoukai)', meaningPt: 'Apresentação (de algo/alguém)' }, { word: '自己紹介', reading: 'じこしょうかい (jikoshoukai)', meaningPt: 'Apresentação pessoal' } ] },
  { id: 'k_n2_add10_24', kanji: '笑', onyomi: ['ショウ (shou)'], kunyomi: ['わら.う (wara.u)', 'え.む (e.mu)'], meaningPt: 'Rir, Sorrir', strokes: 10, radical: '竹 (bambu)', jlpt: 'N2', examples: [ { word: '笑う', reading: 'わらう (warau)', meaningPt: 'Rir' }, { word: '笑顔', reading: 'えがお (egao)', meaningPt: 'Rosto sorridente' }, { word: '爆笑', reading: 'ばくしょう (bakushou)', meaningPt: 'Gargalhada / Rir muito' } ] },
  { id: 'k_n2_add10_25', kanji: '章', onyomi: ['ショウ (shou)'], kunyomi: [], meaningPt: 'Capítulo, Distintivo', strokes: 11, radical: '立 (ficar em pé)', jlpt: 'N2', examples: [ { word: '文章', reading: 'ぶんしょう (bunshou)', meaningPt: 'Texto / Frase' }, { word: '第１章', reading: 'だいいっしょう (daiisshou)', meaningPt: 'Capítulo 1' }, { word: '勲章', reading: 'くんしょう (kunshou)', meaningPt: 'Medalha / Condecoração' } ] },
  { id: 'k_n2_add10_26', kanji: '省', onyomi: ['ショウ (shou)', 'セイ (sei)'], kunyomi: ['はぶ.く (habu.ku)', 'かえり.みる (kaeri.miru)'], meaningPt: 'Ministério, Omitir, Refletir', strokes: 9, radical: '目 (olho)', jlpt: 'N2', examples: [ { word: '省く', reading: 'はぶく (habuku)', meaningPt: 'Omitir / Cortar / Poupar' }, { word: '反省', reading: 'はんせい (hansei)', meaningPt: 'Reflexão / Arrependimento' }, { word: '外務省', reading: 'がいむしょう (gaimushou)', meaningPt: 'Ministério das Relações Exteriores' } ] },
  { id: 'k_n2_add10_27', kanji: '照', onyomi: ['ショウ (shou)'], kunyomi: ['て.る (te.ru)', 'て.らす (te.rasu)'], meaningPt: 'Iluminar, Brilhar', strokes: 13, radical: '火 (fogo)', jlpt: 'N2', examples: [ { word: '照らす', reading: 'てらす (terasu)', meaningPt: 'Iluminar' }, { word: '照明', reading: 'しょうめい (shoumei)', meaningPt: 'Iluminação' }, { word: '対照的', reading: 'たいしょうてき (taishouteki)', meaningPt: 'Contrastante' } ] },
  { id: 'k_n2_add10_28', kanji: '焼', onyomi: ['ショウ (shou)'], kunyomi: ['や.く (ya.ku)', 'や.ける (ya.keru)'], meaningPt: 'Assar, Queimar', strokes: 12, radical: '火 (fogo)', jlpt: 'N2', examples: [ { word: '焼く', reading: 'やく (yaku)', meaningPt: 'Assar / Queimar (transitivo)' }, { word: '焼ける', reading: 'やける (yakeru)', meaningPt: 'Queimar (intransitivo) / Bronzear-se' }, { word: '日焼け', reading: 'ひやけ (hiyake)', meaningPt: 'Bronzeado / Queimadura de sol' } ] },
  { id: 'k_n2_add10_29', kanji: '消', onyomi: ['ショウ (shou)'], kunyomi: ['き.える (ki.eru)', 'け.す (ke.su)'], meaningPt: 'Apagar, Desaparecer', strokes: 10, radical: '水 (água)', jlpt: 'N2', examples: [ { word: '消す', reading: 'けす (kesu)', meaningPt: 'Apagar' }, { word: '消える', reading: 'きえる (kieru)', meaningPt: 'Desaparecer / Apagar-se' }, { word: '消費', reading: 'しょうひ (shouhi)', meaningPt: 'Consumo' } ] },
  { id: 'k_n2_add10_30', kanji: '昇', onyomi: ['ショウ (shou)'], kunyomi: ['のぼ.る (nobo.ru)'], meaningPt: 'Subir, Ascender', strokes: 8, radical: '日 (sol/dia)', jlpt: 'N2', examples: [ { word: '上昇', reading: 'じょうしょう (joushou)', meaningPt: 'Elevação / Subida' }, { word: '昇進', reading: 'しょうしん (shoushin)', meaningPt: 'Promoção (no trabalho)' } ] },
  { id: 'k_n2_add10_31', kanji: '招', onyomi: ['ショウ (shou)'], kunyomi: ['まね.く (mane.ku)'], meaningPt: 'Convidar, Chamar', strokes: 8, radical: '手 (mão)', jlpt: 'N2', examples: [ { word: '招く', reading: 'まねく (maneku)', meaningPt: 'Convidar' }, { word: '招待', reading: 'しょうたい (shoutai)', meaningPt: 'Convite' }, { word: '招き猫', reading: 'まねきねこ (manekineko)', meaningPt: 'Gato da sorte (Maneki-neko)' } ] },
  { id: 'k_n2_add10_32', kanji: '承', onyomi: ['ショウ (shou)'], kunyomi: ['うけたまわ.る (uketamawa.ru)'], meaningPt: 'Concordar, Escutar (humilde)', strokes: 8, radical: '手 (mão)', jlpt: 'N2', examples: [ { word: '承知', reading: 'しょうち (shouchi)', meaningPt: 'Concordância / Conhecimento' }, { word: '承認', reading: 'しょうにん (shounin)', meaningPt: 'Aprovação' }, { word: '承る', reading: 'うけたまわる (uketamawaru)', meaningPt: 'Escutar / Aceitar (humilde)' } ] },
  { id: 'k_n2_add10_33', kanji: '床', onyomi: ['ショウ (shou)'], kunyomi: ['ゆか (yuka)', 'とこ (toko)'], meaningPt: 'Chão, Cama', strokes: 7, radical: '广 (prédio largo)', jlpt: 'N2', examples: [ { word: '床', reading: 'ゆか (yuka)', meaningPt: 'Chão / Piso' }, { word: '起床', reading: 'きしょう (kishou)', meaningPt: 'Levantar-se (da cama)' }, { word: '床屋', reading: 'とこや (tokoya)', meaningPt: 'Barbearia' } ] },
  { id: 'k_n2_add10_34', kanji: '将', onyomi: ['ショウ (shou)'], kunyomi: [], meaningPt: 'Comandante, General', strokes: 10, radical: '寸 (medida)', jlpt: 'N2', examples: [ { word: '将来', reading: 'しょうらい (shourai)', meaningPt: 'Futuro' }, { word: '将軍', reading: 'しょうぐん (shougun)', meaningPt: 'General (Shogun)' }, { word: '将棋', reading: 'しょうぎ (shougi)', meaningPt: 'Shogi (Xadrez japonês)' } ] },
  { id: 'k_n2_add10_35', kanji: '商', onyomi: ['ショウ (shou)'], kunyomi: ['あきな.う (akina.u)'], meaningPt: 'Comércio, Negócios', strokes: 11, radical: '口 (boca)', jlpt: 'N2', examples: [ { word: '商業', reading: 'しょうぎょう (shougyou)', meaningPt: 'Comércio' }, { word: '商品', reading: 'しょうひん (shouhin)', meaningPt: 'Produto / Mercadoria' }, { word: '商店', reading: 'しょうてん (shouten)', meaningPt: 'Loja' } ] },
  { id: 'k_n2_add10_36', kanji: '召', onyomi: ['ショウ (shou)'], kunyomi: ['め.す (me.su)'], meaningPt: 'Convocar, Vestir/Comer (honorífico)', strokes: 5, radical: '口 (boca)', jlpt: 'N2', examples: [ { word: '召し上がる', reading: 'めしあがる (meshiagaru)', meaningPt: 'Comer / Beber (honorífico)' }, { word: '召集', reading: 'しょうしゅう (shoushuu)', meaningPt: 'Convocação' } ] },
  { id: 'k_n2_add10_37', kanji: '勝', onyomi: ['ショウ (shou)'], kunyomi: ['か.つ (ka.tsu)', 'まさ.る (masa.ru)'], meaningPt: 'Vencer, Vitória', strokes: 12, radical: '力 (força)', jlpt: 'N2', examples: [ { word: '勝つ', reading: 'かつ (katsu)', meaningPt: 'Vencer / Ganhar' }, { word: '優勝', reading: 'ゆうしょう (yuushou)', meaningPt: 'Vitória (campeonato)' }, { word: '勝利', reading: 'しょうり (shouri)', meaningPt: 'Vitória / Triunfo' } ] },
  { id: 'k_n2_add10_38', kanji: '除', onyomi: ['ジョ (jo)', 'ジ (ji)'], kunyomi: ['のぞ.く (nozo.ku)'], meaningPt: 'Excluir, Remover', strokes: 10, radical: '阜 (colina)', jlpt: 'N2', examples: [ { word: '除く', reading: 'のぞく (nozoku)', meaningPt: 'Excluir / Remover' }, { word: '削除', reading: 'さくじょ (sakujo)', meaningPt: 'Deletar / Excluir (dados)' }, { word: '掃除', reading: 'そうじ (souji)', meaningPt: 'Limpeza' } ] },
  { id: 'k_n2_add10_39', kanji: '助', onyomi: ['ジョ (jo)'], kunyomi: ['たす.ける (tasu.keru)', 'たす.かる (tasu.karu)'], meaningPt: 'Ajudar, Salvar', strokes: 7, radical: '力 (força)', jlpt: 'N2', examples: [ { word: '助ける', reading: 'たすける (tasukeru)', meaningPt: 'Ajudar / Salvar' }, { word: '助手', reading: 'じょしゅ (joshu)', meaningPt: 'Assistente / Ajudante' }, { word: '助言', reading: 'じょげん (jogen)', meaningPt: 'Conselho' } ] },
  { id: 'k_n2_add10_40', kanji: '諸', onyomi: ['ショ (sho)'], kunyomi: [], meaningPt: 'Vários, Muitos', strokes: 15, radical: '言 (palavra/falar)', jlpt: 'N2', examples: [ { word: '諸国', reading: 'しょこく (shokoku)', meaningPt: 'Vários países' }, { word: '諸問題', reading: 'しょもんだい (shomondai)', meaningPt: 'Vários problemas' }, { word: '諸々', reading: 'もろもろ (moromoro)', meaningPt: 'Várias coisas' } ] },
  { id: 'k_n2_add10_41', kanji: '署', onyomi: ['ショ (sho)'], kunyomi: [], meaningPt: 'Delegacia, Assinatura', strokes: 13, radical: '网 (rede)', jlpt: 'N2', examples: [ { word: '警察署', reading: 'けいさつしょ (keisatsusho)', meaningPt: 'Delegacia de polícia' }, { word: '消防署', reading: 'しょうぼうしょ (shoubousho)', meaningPt: 'Corpo de bombeiros' }, { word: '署名', reading: 'しょめい (shomei)', meaningPt: 'Assinatura' } ] },
  { id: 'k_n2_add10_42', kanji: '緒', onyomi: ['ショ (sho)', 'チョ (cho)'], kunyomi: ['お (o)'], meaningPt: 'Início, Cordão', strokes: 14, radical: '糸 (fio)', jlpt: 'N2', examples: [ { word: '一緒に', reading: 'いっしょに (isshoni)', meaningPt: 'Junto' }, { word: '内緒', reading: 'ないしょ (naisho)', meaningPt: 'Segredo' }, { word: '情緒', reading: 'じょうちょ (joucho)', meaningPt: 'Emoção / Sentimento' } ] },
  { id: 'k_n2_add10_43', kanji: '初', onyomi: ['ショ (sho)'], kunyomi: ['はじ.め (haji.me)', 'はつ (hatsu)', 'うい (ui)'], meaningPt: 'Primeiro, Início', strokes: 7, radical: '衣 (roupa)', jlpt: 'N2', examples: [ { word: '初めて', reading: 'はじめて (hajimete)', meaningPt: 'Pela primeira vez' }, { word: '初級', reading: 'しょきゅう (shokyuu)', meaningPt: 'Nível básico' }, { word: '最初', reading: 'さいしょ (saisho)', meaningPt: 'O primeiro / No começo' } ] },
  { id: 'k_n2_add10_44', kanji: '処', onyomi: ['ショ (sho)'], kunyomi: [], meaningPt: 'Lidar, Lugar', strokes: 5, radical: '几 (mesa)', jlpt: 'N2', examples: [ { word: '処理', reading: 'しょり (shori)', meaningPt: 'Processamento / Tratamento' }, { word: '処分', reading: 'しょぶん (shobun)', meaningPt: 'Descarte / Punição' }, { word: '対処', reading: 'たいしょ (taisho)', meaningPt: 'Lidar com (situação)' } ] },
  { id: 'k_n2_add10_45', kanji: '順', onyomi: ['ジュン (jun)'], kunyomi: [], meaningPt: 'Ordem, Vez', strokes: 12, radical: '頁 (página/cabeça)', jlpt: 'N2', examples: [ { word: '順番', reading: 'じゅんばん (junban)', meaningPt: 'Ordem / Vez' }, { word: '順調', reading: 'じゅんちょう (junchou)', meaningPt: 'Favorável / Indo bem' }, { word: '順序', reading: 'じゅんじょ (junjo)', meaningPt: 'Ordem / Sequência' } ] },
  { id: 'k_n2_add10_46', kanji: '純', onyomi: ['ジュン (jun)'], kunyomi: [], meaningPt: 'Puro', strokes: 10, radical: '糸 (fio)', jlpt: 'N2', examples: [ { word: '純粋', reading: 'じゅんすい (junsui)', meaningPt: 'Puro / Genuíno' }, { word: '単純', reading: 'たんじゅん (tanjun)', meaningPt: 'Simples' }, { word: '純金', reading: 'じゅんきん (junkin)', meaningPt: 'Ouro puro' } ] },
  { id: 'k_n2_add10_47', kanji: '準', onyomi: ['ジュン (jun)'], kunyomi: [], meaningPt: 'Padrão, Preparação', strokes: 13, radical: '水 (água)', jlpt: 'N2', examples: [ { word: '準備', reading: 'じゅんび (junbi)', meaningPt: 'Preparação' }, { word: '基準', reading: 'きじゅん (kijun)', meaningPt: 'Padrão / Critério' }, { word: '準決勝', reading: 'じゅんけっしょう (junkesshou)', meaningPt: 'Semifinal' } ] },
  { id: 'k_n2_add10_48', kanji: '述', onyomi: ['ジュツ (jutsu)'], kunyomi: ['の.べる (no.beru)'], meaningPt: 'Expressar, Mencionar', strokes: 8, radical: '辵 (caminhar)', jlpt: 'N2', examples: [ { word: '述べる', reading: 'のべる (noberu)', meaningPt: 'Afirmar / Mencionar' }, { word: '記述', reading: 'きじゅつ (kijutsu)', meaningPt: 'Descrição' }, { word: '述語', reading: 'じゅつご (jutsugo)', meaningPt: 'Predicado (gramática)' } ] },
  { id: 'k_n2_add10_49', kanji: '術', onyomi: ['ジュツ (jutsu)'], kunyomi: [], meaningPt: 'Arte, Técnica', strokes: 11, radical: '行 (ir)', jlpt: 'N2', examples: [ { word: '技術', reading: 'ぎじゅつ (gijutsu)', meaningPt: 'Tecnologia / Técnica' }, { word: '手術', reading: 'しゅじゅつ (shujutsu)', meaningPt: 'Cirurgia' }, { word: '芸術', reading: 'げいじゅつ (geijutsu)', meaningPt: 'Arte' } ] },
  { id: 'k_n2_add10_50', kanji: '祝', onyomi: ['シュク (shuku)', 'シュウ (shuu)'], kunyomi: ['いわ.う (iwa.u)'], meaningPt: 'Celebrar, Parabenizar', strokes: 9, radical: '示 (mostrar)', jlpt: 'N2', examples: [ { word: '祝う', reading: 'いわう (iwau)', meaningPt: 'Celebrar / Festejar' }, { word: 'お祝い', reading: 'おいわい (oiwai)', meaningPt: 'Celebração / Presente de congratulação' }, { word: '祝日', reading: 'しゅくじつ (shukujitsu)', meaningPt: 'Feriado' } ] },
  { id: 'k_n2_add10_51', kanji: '宿', onyomi: ['シュク (shuku)'], kunyomi: ['やど (yado)', 'やど.る (yado.ru)'], meaningPt: 'Hospedagem, Pousada', strokes: 11, radical: '宀 (telhado)', jlpt: 'N2', examples: [ { word: '宿題', reading: 'しゅくだい (shukudai)', meaningPt: 'Dever de casa / Tarefa' }, { word: '宿泊', reading: 'しゅくはく (shukuhaku)', meaningPt: 'Hospedagem' }, { word: '宿', reading: 'やど (yado)', meaningPt: 'Pousada' } ] },
  { id: 'k_n2_add10_52', kanji: '柔', onyomi: ['ジュウ (juu)', 'ニュウ (nyuu)'], kunyomi: ['やわ.らかい (yawa.rakai)'], meaningPt: 'Macio, Flexível', strokes: 9, radical: '木 (árvore)', jlpt: 'N2', examples: [ { word: '柔らかい', reading: 'やわらかい (yawarakai)', meaningPt: 'Macio' }, { word: '柔道', reading: 'じゅうどう (juudou)', meaningPt: 'Judô' }, { word: '柔軟', reading: 'じゅうなん (juunan)', meaningPt: 'Flexível / Adaptável' } ] },
  { id: 'k_n2_add10_53', kanji: '舟', onyomi: ['シュウ (shuu)'], kunyomi: ['ふね (fune)', 'ふな (funa)'], meaningPt: 'Barco', strokes: 6, radical: '舟 (barco)', jlpt: 'N2', examples: [ { word: '小舟', reading: 'こぶね (kobune)', meaningPt: 'Barco pequeno' }, { word: '舟', reading: 'ふね (fune)', meaningPt: 'Barco' } ] },
  { id: 'k_n2_add10_54', kanji: '拾', onyomi: ['シュウ (shuu)', 'ジュウ (juu)'], kunyomi: ['ひろ.う (hiro.u)'], meaningPt: 'Pegar (do chão)', strokes: 9, radical: '手 (mão)', jlpt: 'N2', examples: [ { word: '拾う', reading: 'ひろう (hirou)', meaningPt: 'Pegar (do chão) / Encontrar' }, { word: '拾い物', reading: 'ひろいもの (hiroimono)', meaningPt: 'Achado' } ] },
  { id: 'k_n2_add10_55', kanji: '修', onyomi: ['シュウ (shuu)', 'シュ (shu)'], kunyomi: ['おさ.める (osa.meru)', 'おさ.まる (osa.maru)'], meaningPt: 'Estudar, Consertar', strokes: 10, radical: '人 (pessoa)', jlpt: 'N2', examples: [ { word: '修理', reading: 'しゅうり (shuuri)', meaningPt: 'Conserto / Reparo' }, { word: '研修', reading: 'けんしゅう (kenshuu)', meaningPt: 'Treinamento / Estágio' }, { word: '修正', reading: 'しゅうせい (shuusei)', meaningPt: 'Correção / Modificação' } ] },
  { id: 'k_n2_add10_56', kanji: '州', onyomi: ['シュウ (shuu)'], kunyomi: ['す (su)'], meaningPt: 'Estado, Província', strokes: 6, radical: '川 (rio)', jlpt: 'N2', examples: [ { word: '州', reading: 'しゅう (shuu)', meaningPt: 'Estado (como nação/território)' }, { word: '本州', reading: 'ほんしゅう (honshuu)', meaningPt: 'Honshu (ilha principal do Japão)' }, { word: '九州', reading: 'きゅうしゅう (kyuushuu)', meaningPt: 'Kyushu (ilha do sul do Japão)' } ] },
  { id: 'k_n2_add10_57', kanji: '周', onyomi: ['シュウ (shuu)'], kunyomi: ['まわ.り (mawa.ri)'], meaningPt: 'Circunferência, Volta', strokes: 8, radical: '口 (boca)', jlpt: 'N2', examples: [ { word: '周り', reading: 'まわり (mawari)', meaningPt: 'Arredores / Em volta' }, { word: '周辺', reading: 'しゅうへん (shuuhen)', meaningPt: 'Arredores / Vizinhança' }, { word: '一周', reading: 'いっしゅう (isshuu)', meaningPt: 'Uma volta' } ] },
  { id: 'k_n2_add10_58', kanji: '収', onyomi: ['シュウ (shuu)'], kunyomi: ['おさ.める (osa.meru)', 'おさ.まる (osa.maru)'], meaningPt: 'Obter, Receita', strokes: 4, radical: '又 (de novo)', jlpt: 'N2', examples: [ { word: '収入', reading: 'しゅうにゅう (shuunyuu)', meaningPt: 'Renda / Receita' }, { word: '吸収', reading: 'きゅうしゅう (kyuushuu)', meaningPt: 'Absorção' }, { word: '収集', reading: 'しゅうしゅう (shuushuu)', meaningPt: 'Coleta' } ] },
  { id: 'k_n2_add10_59', kanji: '授', onyomi: ['ジュ (ju)'], kunyomi: ['さず.ける (sazu.keru)', 'さず.かる (sazu.karu)'], meaningPt: 'Instruir, Conceder', strokes: 11, radical: '手 (mão)', jlpt: 'N2', examples: [ { word: '授業', reading: 'じゅぎょう (jugyou)', meaningPt: 'Aula' }, { word: '教授', reading: 'きょうじゅ (kyouju)', meaningPt: 'Professor universitário' } ] },
  { id: 'k_n2_add10_60', kanji: '受', onyomi: ['ジュ (ju)'], kunyomi: ['う.ける (u.keru)', 'う.かる (u.karu)'], meaningPt: 'Receber, Aceitar', strokes: 8, radical: '又 (de novo)', jlpt: 'N2', examples: [ { word: '受ける', reading: 'うける (ukeru)', meaningPt: 'Receber / Fazer (prova)' }, { word: '受付', reading: 'うけつけ (uketsuke)', meaningPt: 'Recepção' }, { word: '受験', reading: 'じゅけん (juken)', meaningPt: 'Prestar exame' } ] },
  { id: 'k_n2_add10_61', kanji: '酒', onyomi: ['シュ (shu)'], kunyomi: ['さけ (sake)', 'さか (saka)'], meaningPt: 'Álcool, Vinho de arroz', strokes: 10, radical: '酉 (pássaro/vinho)', jlpt: 'N2', examples: [ { word: 'お酒', reading: 'おさけ (osake)', meaningPt: 'Bebida alcoólica / Sake' }, { word: '日本酒', reading: 'にほんしゅ (nihonshu)', meaningPt: 'Sake japonês' }, { word: '居酒屋', reading: 'いざかや (izakaya)', meaningPt: 'Bar japonês (Izakaya)' } ] },
  { id: 'k_n2_add10_62', kanji: '種', onyomi: ['シュ (shu)'], kunyomi: ['たね (tane)'], meaningPt: 'Semente, Tipo/Espécie', strokes: 14, radical: '禾 (cereal/grão)', jlpt: 'N2', examples: [ { word: '種類', reading: 'しゅるい (shurui)', meaningPt: 'Tipo / Espécie' }, { word: '種', reading: 'たね (tane)', meaningPt: 'Semente' }, { word: '人種', reading: 'じんしゅ (jinshu)', meaningPt: 'Raça humana' } ] }
];

const dataPathN2 = path.join(process.cwd(), 'src/data/kanjiN2N1.ts');

let n2Content = fs.readFileSync(dataPathN2, 'utf-8');

let addedCount = 0;
let blocksStr = '';

for (const k of newKanjis) {
  if (n2Content.includes(`kanji: '${k.kanji}'`)) {
    console.log(`Skipping duplicate: ${k.kanji}`);
    continue;
  }

  const objStr = `  {
    id: '${k.id}',
    kanji: '${k.kanji}',
    onyomi: ${JSON.stringify(k.onyomi)},
    kunyomi: ${JSON.stringify(k.kunyomi)},
    meaningPt: '${k.meaningPt}',
    strokes: ${k.strokes},
    radical: '${k.radical}',
    jlpt: '${k.jlpt}',
    examples: ${JSON.stringify(k.examples, null, 6).replace(/"([^"]+)":/g, '$1:')}
  }`;

  blocksStr += (addedCount === 0 ? '' : ',\n') + objStr;
  addedCount++;
}

if (addedCount > 0) {
  const lastBracketIndex = n2Content.lastIndexOf('];');
  n2Content = n2Content.slice(0, lastBracketIndex) + ',\n' + blocksStr + '\n];\n';
  fs.writeFileSync(dataPathN2, n2Content, 'utf-8');
}

console.log(`Successfully added ${addedCount} new Kanjis to N2!`);
