import fs from 'fs';
import path from 'path';

const nouns = [
  { w: 'アフリカ', r: 'アフリカ', rom: 'afurika', m: 'África' },
  { w: '挨拶', r: 'あいさつ', rom: 'aisatsu', m: 'saudação; cumprimento' },
  { w: '味', r: 'あじ', rom: 'aji', m: 'sabor; gosto' },
  { w: 'アジア', r: 'アジア', rom: 'ajia', m: 'Ásia' },
  { w: '赤ちゃん', r: 'あかちゃん', rom: 'akachan', m: 'bebê' },
  { w: '赤ん坊', r: 'あかんぼう', rom: 'akanbou', m: 'bebê; recém-nascido' },
  { w: 'アクセサリー', r: 'アクセサリー', rom: 'akusesarii', m: 'acessório' },
  { w: 'アメリカ', r: 'アメリカ', rom: 'amerika', m: 'Estados Unidos (América)' },
  { w: 'アナウンサー', r: 'アナウンサー', rom: 'anaunsaa', m: 'locutor; apresentador' },
  { w: '案内', r: 'あんない', rom: 'annai', m: 'orientação; guia' },
  { w: '安心', r: 'あんしん', rom: 'anshin', m: 'alívio; tranquilidade' },
  { w: '安全', r: 'あんぜん', rom: 'anzen', m: 'segurança' },
  { w: 'アルバイト', r: 'アルバイト', rom: 'arubaito', m: 'trabalho de meio período (bico)' },
  { w: 'アルコール', r: 'アルコール', rom: 'arukooru', m: 'álcool' },
  { w: '遊び', r: 'あそび', rom: 'asobi', m: 'brincadeira; diversão' },
  { w: '倍', r: 'ばい', rom: 'bai', m: 'dobro; vezes' },
  { w: '番組', r: 'ばんぐみ', rom: 'bangumi', m: 'programa (de TV, rádio)' },
  { w: '場所', r: 'ばしょ', rom: 'basho', m: 'lugar; local' },
  { w: 'ベル', r: 'ベル', rom: 'beru', m: 'campainha; sino' },
  { w: '美術館', r: 'びじゅつかん', rom: 'bijutsukan', m: 'museu de arte' },
  { w: 'ビル', r: 'ビル', rom: 'biru', m: 'prédio; edifício' },
  { w: '貿易', r: 'ぼうえき', rom: 'boueki', m: 'comércio (exterior)' },
  { w: '部長', r: 'ぶちょう', rom: 'buchou', m: 'gerente de departamento; diretor' },
  { w: 'ぶどう', r: 'ぶどう', rom: 'budou', m: 'uva' },
  { w: '文学', r: 'ぶんがく', rom: 'bungaku', m: 'literatura' },
  { w: '文化', r: 'ぶんか', rom: 'bunka', m: 'cultura' },
  { w: '文法', r: 'ぶんぽう', rom: 'bunpou', m: 'gramática' },
  { w: 'チェック', r: 'チェック', rom: 'chekku', m: 'verificação (check)' },
  { w: '血', r: 'ち', rom: 'chi', m: 'sangue' },
  { w: '力', r: 'ちから', rom: 'chikara', m: 'força; poder' },
  { w: '地理', r: 'ちり', rom: 'chiri', m: 'geografia' },
  { w: '中学校', r: 'ちゅうがっこう', rom: 'chuugakkou', m: 'escola de ensino fundamental (ginásio)' },
  { w: '注意', r: 'ちゅうい', rom: 'chuui', m: 'cuidado; atenção' },
  { w: '注射', r: 'ちゅうしゃ', rom: 'chuusha', m: 'injeção' },
  { w: '駐車場', r: 'ちゅうしゃじょう', rom: 'chuushajou', m: 'estacionamento' },
  { w: '大学生', r: 'だいがくせい', rom: 'daigakusei', m: 'estudante universitário' },
  { w: '大体', r: 'だいたい', rom: 'daitai', m: 'mais ou menos; em geral' },
  { w: '暖房', r: 'だんぼう', rom: 'danbou', m: 'aquecedor (ambiente)' },
  { w: '男性', r: 'だんせい', rom: 'dansei', m: 'homem; sexo masculino' },
  { w: '電報', r: 'でんぽう', rom: 'denpou', m: 'telegrama' },
  { w: '電灯', r: 'でんとう', rom: 'dentou', m: 'luz elétrica' },
  { w: '泥棒', r: 'どろぼう', rom: 'dorobou', m: 'ladrão' },
  { w: '動物園', r: 'どうぶつえん', rom: 'doubutsuen', m: 'zoológico' },
  { w: '道具', r: 'どうぐ', rom: 'dougu', m: 'ferramenta' },
  { w: '枝', r: 'えだ', rom: 'eda', m: 'galho; ramo' },
  { w: '遠慮', r: 'えんりょ', rom: 'enryo', m: 'hesitação; restrição; cerimônia' },
  { w: 'エスカレーター', r: 'エスカレーター', rom: 'esukareetaa', m: 'escada rolante' },
  { w: 'ファックス', r: 'ファックス', rom: 'fakkusu', m: 'fax' },
  { w: '不便', r: 'ふべん', rom: 'fuben', m: 'inconveniente; falta de praticidade' },
  { w: '復習', r: 'ふくしゅう', rom: 'fukushuu', m: 'revisão (estudos)' },
  { w: '複雑', r: 'ふくざつ', rom: 'fukuzatsu', m: 'complexidade; complicado' },
  { w: '船', r: 'ふね', rom: 'fune', m: 'navio; barco' },
  { w: '布団', r: 'ふとん', rom: 'futon', m: 'futon (colchão japonês)' },
  { w: '普通', r: 'ふつう', rom: 'futsuu', m: 'normal; comum; geralmente' },
  { w: 'ガラス', r: 'ガラス', rom: 'garasu', m: 'vidro' },
  { w: 'ガソリン', r: 'ガソリン', rom: 'gasorin', m: 'gasolina' },
  { w: 'ガソリンスタンド', r: 'ガソリンスタンド', rom: 'gasorin sutando', m: 'posto de gasolina' },
  { w: 'ガス', r: 'ガス', rom: 'gasu', m: 'gás' },
  { w: '原因', r: 'げんいん', rom: 'genin', m: 'causa; motivo' },
  { w: '下宿', r: 'げしゅく', rom: 'geshuku', m: 'pensão; alojamento' },
  { w: '技術', r: 'ぎじゅつ', rom: 'gijutsu', m: 'tecnologia; técnica; habilidade' },
  { w: 'ごちそう', r: 'ごちそう', rom: 'gochisou', m: 'banquete; refeição farta' },
  { w: 'ごみ', r: 'ごみ', rom: 'gomi', m: 'lixo' },
  { w: 'ご主人', r: 'ごしゅじん', rom: 'goshujin', m: 'marido (de outra pessoa)' },
  { w: 'ご存じ', r: 'ごぞんじ', rom: 'gozonji', m: 'conhecer; saber (honorífico)' },
  { w: '具合', r: 'ぐあい', rom: 'guai', m: 'estado; condição' },
  { w: '葉', r: 'は', rom: 'ha', m: 'folha' },
  { w: '拝見', r: 'はいけん', rom: 'haiken', m: 'ver; olhar (humilde)' },
  { w: '歯医者', r: 'はいしゃ', rom: 'haisha', m: 'dentista' },
  { w: '花見', r: 'はなみ', rom: 'hanami', m: 'visualização de flores (cerejeira)' },
  { w: 'ハンドバッグ', r: 'ハンドバッグ', rom: 'handobaggu', m: 'bolsa de mão' },
  { w: '反対', r: 'はんたい', rom: 'hantai', m: 'oposto; contrário' },
  { w: '発音', r: 'はつおん', rom: 'hatsuon', m: 'pronúncia' },
  { w: '林', r: 'はやし', rom: 'hayashi', m: 'bosque' },
  { w: '変', r: 'へん', rom: 'hen', m: 'estranho; esquisito' },
  { w: '返事', r: 'へんじ', rom: 'henji', m: 'resposta' },
  { w: '火', r: 'ひ', rom: 'hi', m: 'fogo' },
  { w: '髭', r: 'ひげ', rom: 'hige', m: 'barba; bigode' },
  { w: '光', r: 'ひかり', rom: 'hikari', m: 'luz' },
  { w: '引き出し', r: 'ひきだし', rom: 'hikidashi', m: 'gaveta' },
  { w: '飛行場', r: 'ひこうじょう', rom: 'hikoujou', m: 'aeródromo; aeroporto' },
  { w: '昼間', r: 'ひるま', rom: 'hiruma', m: 'durante o dia; dia' },
  { w: '昼休み', r: 'ひるやすみ', rom: 'hiruyasumi', m: 'horário de almoço' },
  { w: '久しぶり', r: 'ひさしぶり', rom: 'hisashiburi', m: 'faz tempo; há muito tempo' },
  { w: '翻訳', r: 'ほんやく', rom: 'honyaku', m: 'tradução (escrita)' },
  { w: '星', r: 'ほし', rom: 'hoshi', m: 'estrela' },
  { w: 'ほとんど', r: 'ほとんど', rom: 'hotondo', m: 'quase tudo; na maior parte' },
  { w: '法律', r: 'ほうりつ', rom: 'houritsu', m: 'lei' },
  { w: '放送', r: 'ほうそう', rom: 'housou', m: 'transmissão (rádio/TV)' },
  { w: '一度', r: 'いちど', rom: 'ichido', m: 'uma vez' },
  { w: '以外', r: 'いがい', rom: 'igai', m: 'exceto; fora isso' },
  { w: '医学', r: 'いがく', rom: 'igaku', m: 'medicina (ciência)' },
  { w: '以上', r: 'いじょう', rom: 'ijou', m: 'mais que; acima de' },
  { w: '以下', r: 'いか', rom: 'ika', m: 'menos que; abaixo de' },
  { w: '意見', r: 'いけん', rom: 'iken', m: 'opinião' },
  { w: '生き物', r: 'いきもの', rom: 'ikimono', m: 'criatura viva; animal' },
  { w: '以内', r: 'いない', rom: 'inai', m: 'dentro de (tempo, distância)' },
  { w: '田舎', r: 'いなか', rom: 'inaka', m: 'interior; campo' },
  { w: 'いっぱい', r: 'いっぱい', rom: 'ippai', m: 'cheio; muito' },
  { w: '石', r: 'いし', rom: 'ishi', m: 'pedra' }
];

const examples = {
  'アフリカ': { jp: 'アフリカに行きたいです。', r: 'アフリカに いきたいです。', rom: 'afurika ni ikitai desu.', pt: 'Quero ir para a África.' },
  '挨拶': { jp: '先生に挨拶をします。', r: 'せんせいに あいさつを します。', rom: 'sensei ni aisatsu o shimasu.', pt: 'Cumprimento o professor.' },
  '味': { jp: 'この料理は味が薄いです。', r: 'この りょうりは あじが うすいです。', rom: 'kono ryouri wa aji ga usui desu.', pt: 'Este prato tem sabor fraco.' },
  'アジア': { jp: '日本はアジアにあります。', r: 'にほんは アジアに あります。', rom: 'nihon wa ajia ni arimasu.', pt: 'O Japão fica na Ásia.' },
  '赤ちゃん': { jp: '赤ちゃんが泣いています。', r: 'あかちゃんが ないています。', rom: 'akachan ga naiteimasu.', pt: 'O bebê está chorando.' },
  '赤ん坊': { jp: '赤ん坊が生まれました。', r: 'あかんぼうが うまれました。', rom: 'akanbou ga umaremashita.', pt: 'O bebê nasceu.' },
  'アクセサリー': { jp: '可愛いアクセサリーを買いました。', r: 'かわいい アクセサリーを かいました。', rom: 'kawaii akusesarii o kaimashita.', pt: 'Comprei um acessório fofo.' },
  'アメリカ': { jp: 'アメリカに留学します。', r: 'アメリカに りゅうがくします。', rom: 'amerika ni ryuugakushimasu.', pt: 'Vou estudar (intercâmbio) nos Estados Unidos.' },
  'アナウンサー': { jp: '彼女はテレビのアナウンサーです。', r: 'かのじょは テレビの アナウンサーです。', rom: 'kanojo wa terebi no anaunsaa desu.', pt: 'Ela é locutora de televisão.' },
  '案内': { jp: '町を案内します。', r: 'まちを あんないします。', rom: 'machi o annaishimasu.', pt: 'Vou te guiar pela cidade.' },
  '安心': { jp: 'それを聞いて安心しました。', r: 'それを きいて あんしんしました。', rom: 'sore o kiite anshinshimashita.', pt: 'Fiquei aliviado ao ouvir isso.' },
  '安全': { jp: 'ここは安全な場所です。', r: 'ここは あんぜんな ばしょです。', rom: 'koko wa anzen na basho desu.', pt: 'Aqui é um local seguro.' },
  'アルバイト': { jp: 'レストランでアルバイトをしています。', r: 'レストランで アルバイトを しています。', rom: 'resutoran de arubaito o shiteimasu.', pt: 'Faço bico em um restaurante.' },
  'アルコール': { jp: 'アルコールは飲めません。', r: 'アルコールは のめません。', rom: 'arukooru wa nomemasen.', pt: 'Não posso beber álcool.' },
  '遊び': { jp: '子供の遊びは楽しいです。', r: 'こどもの あそびは たのしいです。', rom: 'kodomo no asobi wa tanoshii desu.', pt: 'Brincadeira de criança é divertida.' },
  '倍': { jp: '値段が二倍になりました。', r: 'ねだんが にばいに なりました。', rom: 'nedan ga nibai ni narimashita.', pt: 'O preço dobrou.' },
  '番組': { jp: '面白いテレビ番組を見ました。', r: 'おもしろい テレビばんぐみを みました。', rom: 'omoshiroi terebi bangumi o mimashita.', pt: 'Assisti a um programa de TV interessante.' },
  '場所': { jp: '待ち合わせの場所は駅です。', r: 'まちあわせの ばしょは えきです。', rom: 'machiawase no basho wa eki desu.', pt: 'O local de encontro é a estação.' },
  'ベル': { jp: 'ドアのベルが鳴りました。', r: 'ドアの ベルが なりました。', rom: 'doa no beru ga narimashita.', pt: 'A campainha da porta tocou.' },
  '美術館': { jp: '休日に美術館へ行きます。', r: 'きゅうじつに びじゅつかんへ いきます。', rom: 'kyuujitsu ni bijutsukan e ikimasu.', pt: 'Vou ao museu de arte no feriado.' },
  'ビル': { jp: 'あの高いビルは会社です。', r: 'あの たかい ビルは かいしゃです。', rom: 'ano takai biru wa kaisha desu.', pt: 'Aquele prédio alto é a empresa.' },
  '貿易': { jp: '父は貿易の仕事をしています。', r: 'ちちは ぼうえきの しごとを しています。', rom: 'chichi wa boueki no shigoto o shiteimasu.', pt: 'Meu pai trabalha com comércio.' },
  '部長': { jp: '部長と会議をします。', r: 'ぶちょうと かいぎを します。', rom: 'buchou to kaigi o shimasu.', pt: 'Terei uma reunião com o gerente do departamento.' },
  'ぶどう': { jp: '甘いぶどうを食べました。', r: 'あまい ぶどうを たべました。', rom: 'amai budou o tabemashita.', pt: 'Comi uma uva doce.' },
  '文学': { jp: '日本の文学を勉強しています。', r: 'にほんの ぶんがくを べんきょうしています。', rom: 'nihon no bungaku o benkyoushiteimasu.', pt: 'Estou estudando literatura japonesa.' },
  '文化': { jp: '外国の文化に興味があります。', r: 'がいこくの ぶんかに きょうみが あります。', rom: 'gaikoku no bunka ni kyoumi ga arimasu.', pt: 'Tenho interesse na cultura estrangeira.' },
  '文法': { jp: '日本語の文法は難しいです。', r: 'にほんごの ぶんぽうは むずかしいです。', rom: 'nihongo no bunpou wa muzukashii desu.', pt: 'A gramática do japonês é difícil.' },
  'チェック': { jp: '書類をチェックしてください。', r: 'しょるいを チェックしてください。', rom: 'shorui o chekkushite kudasai.', pt: 'Verifique os documentos, por favor.' },
  '血': { jp: '指を切って血が出ました。', r: 'ゆびを きって ちが でました。', rom: 'yubi o kitte chi ga demashita.', pt: 'Cortei o dedo e saiu sangue.' },
  '力': { jp: '彼は力が強いです。', r: 'かれは ちからが つよいです。', rom: 'kare wa chikara ga tsuyoi desu.', pt: 'Ele é forte (tem força).' },
  '地理': { jp: '学校で地理を学びました。', r: 'がっこうで ちりを まなびました。', rom: 'gakkou de chiri o manabimashita.', pt: 'Estudei geografia na escola.' },
  '中学校': { jp: '弟は中学校に通っています。', r: 'おとうとは ちゅうがっこうに かよっています。', rom: 'otouto wa chuugakkou ni kayotteimasu.', pt: 'Meu irmão mais novo frequenta o ensino fundamental.' },
  '注意': { jp: '車に注意してください。', r: 'くるまに ちゅういしてください。', rom: 'kuruma ni chuuishite kudasai.', pt: 'Tome cuidado com os carros.' },
  '注射': { jp: '病院で注射をしました。', r: 'びょういんで ちゅうしゃを しました。', rom: 'byouin de chuusha o shimashita.', pt: 'Tomei uma injeção no hospital.' },
  '駐車場': { jp: '車を駐車場に止めます。', r: 'くるまを ちゅうしゃじょうに とめます。', rom: 'kuruma o chuushajou ni tomemasu.', pt: 'Vou parar o carro no estacionamento.' },
  '大学生': { jp: '姉は大学生です。', r: 'あねは だいがくせいです。', rom: 'ane wa daigakusei desu.', pt: 'Minha irmã mais velha é estudante universitária.' },
  '大体': { jp: '話の意味は大体わかりました。', r: 'はなしの いみは だいたい わかりました。', rom: 'hanashi no imi wa daitai wakarimashita.', pt: 'Entendi mais ou menos o significado da conversa.' },
  '暖房': { jp: '部屋の暖房をつけます。', r: 'へやの だんぼうを つけます。', rom: 'heya no danbou o tsukemasu.', pt: 'Vou ligar o aquecedor do quarto.' },
  '男性': { jp: 'あの男性は誰ですか。', r: 'あの だんせいは だれですか。', rom: 'ano dansei wa dare desu ka.', pt: 'Quem é aquele homem?' },
  '電報': { jp: 'お祝いの電報を送りました。', r: 'おいわいの でんぽうを おくりました。', rom: 'oiwai no denpou o okurimashita.', pt: 'Enviei um telegrama de felicitação.' },
  '電灯': { jp: '暗いので電灯をつけましょう。', r: 'くらいので でんとうを つけましょう。', rom: 'kurai node dentou o tsukemashou.', pt: 'Como está escuro, vamos acender a luz.' },
  '泥棒': { jp: '家に泥棒が入りました。', r: 'いえに どろぼうが はいりました。', rom: 'ie ni dorobou ga hairimashita.', pt: 'Um ladrão entrou em casa.' },
  '動物園': { jp: '動物園でパンダを見ました。', r: 'どうぶつえんで パンダを みました。', rom: 'doubutsuen de panda o mimashita.', pt: 'Vi um panda no zoológico.' },
  '道具': { jp: 'この道具を使ってください。', r: 'この どうぐを つかってください。', rom: 'kono dougu o tsukatte kudasai.', pt: 'Use esta ferramenta, por favor.' },
  '枝': { jp: '木から枝が落ちました。', r: 'きから えだが おちました。', rom: 'ki kara eda ga ochimashita.', pt: 'Um galho caiu da árvore.' },
  '遠慮': { jp: '遠慮しないで食べてください。', r: 'えんりょしないで たべてください。', rom: 'enryoshinaide tabete kudasai.', pt: 'Coma sem cerimônia, por favor.' },
  'エスカレーター': { jp: 'エスカレーターで二階へ行きます。', r: 'エスカレーターで にかいへ いきます。', rom: 'esukareetaa de nikai e ikimasu.', pt: 'Vou para o segundo andar de escada rolante.' },
  'ファックス': { jp: '書類をファックスで送ります。', r: 'しょるいを ファックスで おくります。', rom: 'shorui o fakkusu de okurimasu.', pt: 'Vou enviar os documentos por fax.' },
  '不便': { jp: 'ここは交通が不便です。', r: 'ここは こうつうが ふべんです。', rom: 'koko wa koutsuu ga fuben desu.', pt: 'O transporte/trânsito aqui é inconveniente.' },
  '復習': { jp: '家に帰って復習します。', r: 'いえに かえって ふくしゅうします。', rom: 'ie ni kaette fukushuushimasu.', pt: 'Volto para casa e faço a revisão.' },
  '複雑': { jp: 'この機械は使い方が複雑です。', r: 'この きかいは つかいかたが ふくざつです。', rom: 'kono kikai wa tsukaikata ga fukuzatsu desu.', pt: 'O modo de usar esta máquina é complicado.' },
  '船': { jp: '船で海を渡ります。', r: 'ふねで うみを わたります。', rom: 'fune de umi o watarimasu.', pt: 'Atravesso o mar de barco.' },
  '布団': { jp: '布団を敷いて寝ます。', r: 'ふとんを しいて ねます。', rom: 'futon o shiite nemasu.', pt: 'Estendo o futon e durmo.' },
  '普通': { jp: '普通の電車に乗ります。', r: 'ふつうの でんしゃに のります。', rom: 'futsuu no densha ni norimasu.', pt: 'Pego um trem comum.' },
  'ガラス': { jp: 'ガラスのコップを買いました。', r: 'ガラスの コップを かいました。', rom: 'garasu no koppu o kaimashita.', pt: 'Comprei um copo de vidro.' },
  'ガソリン': { jp: '車にガソリンを入れます。', r: 'くるまに ガソリンを いれます。', rom: 'kuruma ni gasorin o iremasu.', pt: 'Abasteço o carro com gasolina.' },
  'ガソリンスタンド': { jp: 'ガソリンスタンドで休みます。', r: 'ガソリンスタンドで やすみます。', rom: 'gasorin sutando de yasumimasu.', pt: 'Descanso no posto de gasolina.' },
  'ガス': { jp: 'ガスをつけてお湯を沸かします。', r: 'ガスを つけて おゆを わかします。', rom: 'gasu o tsukete oyu o wakashimasu.', pt: 'Ligo o gás e fervo a água.' },
  '原因': { jp: '事故の原因を調べます。', r: 'じこの げんいんを しらべます。', rom: 'jiko no genin o shirabemasu.', pt: 'Investigar a causa do acidente.' },
  '下宿': { jp: '大学の近くに下宿しています。', r: 'だいがくの ちかくに げしゅくしています。', rom: 'daigaku no chikaku ni geshukushiteimasu.', pt: 'Estou alojado (em pensão) perto da universidade.' },
  '技術': { jp: '新しい技術を開発します。', r: 'あたらしい ぎじゅつを かいはつします。', rom: 'atarashii gijutsu o kaihatsushimasu.', pt: 'Desenvolver uma nova tecnologia.' },
  'ごちそう': { jp: '今日はごちそうですね。', r: 'きょうは ごちそうですね。', rom: 'kyou wa gochisou desu ne.', pt: 'Hoje é um banquete, não é?' },
  'ごみ': { jp: 'ごみを捨ててください。', r: 'ごみを すててください。', rom: 'gomi o sutete kudasai.', pt: 'Jogue o lixo fora, por favor.' },
  'ご主人': { jp: 'ご主人はお元気ですか。', r: 'ごしゅじんは おげんきですか。', rom: 'goshujin wa ogenki desu ka.', pt: 'Como está o seu marido?' },
  'ご存じ': { jp: 'この本をご存じですか。', r: 'この ほんを ごぞんじですか。', rom: 'kono hon o gozonji desu ka.', pt: 'Você conhece este livro?' },
  '具合': { jp: '体の具合が悪いです。', r: 'からだの ぐあいが わるいです。', rom: 'karada no guai ga warui desu.', pt: 'Minha condição física está ruim.' },
  '葉': { jp: '木から葉が落ちます。', r: 'きから はが おちます。', rom: 'ki kara ha ga ochimasu.', pt: 'A folha cai da árvore.' },
  '拝見': { jp: 'パスポートを拝見します。', r: 'パスポートを はいけんします。', rom: 'pasupooto o haikenshimasu.', pt: 'Vou dar uma olhada (ver) no seu passaporte.' },
  '歯医者': { jp: '歯医者に行きます。', r: 'はいしゃに いきます。', rom: 'haisha ni ikimasu.', pt: 'Vou ao dentista.' },
  '花見': { jp: '春に花見をします。', r: 'はるに はなみを します。', rom: 'haru ni hanami o shimasu.', pt: 'Faço visualização de flores na primavera.' },
  'ハンドバッグ': { jp: '彼女は赤いハンドバッグを持っています。', r: 'かのじょは あかい ハンドバッグを もっています。', rom: 'kanojo wa akai handobaggu o motteimasu.', pt: 'Ela tem uma bolsa de mão vermelha.' },
  '反対': { jp: '彼の意見に反対です。', r: 'かれの いけんに はんたいです。', rom: 'kare no iken ni hantai desu.', pt: 'Sou oposto (contrário) à opinião dele.' },
  '発音': { jp: 'この単語の発音を教えてください。', r: 'この たんごの はつおんを おしえてください。', rom: 'kono tango no hatsuon o oshiete kudasai.', pt: 'Ensine a pronúncia desta palavra, por favor.' },
  '林': { jp: '林の中で鳥が鳴いています。', r: 'はやしの なかで とりが ないています。', rom: 'hayashi no naka de tori ga naiteimasu.', pt: 'Os pássaros estão cantando no bosque.' },
  '変': { jp: '今日は変な天気です。', r: 'きょうは へんな てんきです。', rom: 'kyou wa hen na tenki desu.', pt: 'Hoje está um tempo estranho.' },
  '返事': { jp: '手紙の返事を書きます。', r: 'てがみの へんじを かきます。', rom: 'tegami no henji o kakimasu.', pt: 'Escrevo uma resposta para a carta.' },
  '火': { jp: '火に気をつけてください。', r: 'ひに きをつけてください。', rom: 'hi ni ki o tsukete kudasai.', pt: 'Tome cuidado com o fogo.' },
  '髭': { jp: '彼は髭を生やしています。', r: 'かれは ひげを はやしています。', rom: 'kare wa hige o hayashiteimasu.', pt: 'Ele deixa a barba crescer.' },
  '光': { jp: '太陽の光がまぶしいです。', r: 'たいようの ひかりが まぶしいです。', rom: 'taiyou no hikari ga mabushii desu.', pt: 'A luz do sol é ofuscante.' },
  '引き出し': { jp: '引き出しの中にペンがあります。', r: 'ひきだしの なかに ペンが あります。', rom: 'hikidashi no naka ni pen ga arimasu.', pt: 'Há uma caneta na gaveta.' },
  '飛行場': { jp: '飛行場までタクシーで行きます。', r: 'ひこうじょうまで タクシーで いきます。', rom: 'hikoujou made takushii de ikimasu.', pt: 'Vou de táxi até o aeroporto.' },
  '昼間': { jp: '昼間は暑いです。', r: 'ひるまは あついです。', rom: 'hiruma wa atsui desu.', pt: 'Durante o dia faz calor.' },
  '昼休み': { jp: '昼休みに公園を散歩します。', r: 'ひるやすみに こうえんを さんぽします。', rom: 'hiruyasumi ni kouen o sanposhimasu.', pt: 'Passeio no parque durante o horário de almoço.' },
  '久しぶり': { jp: '久しぶりに友達に会いました。', r: 'ひさしぶりに ともだちに あいました。', rom: 'hisashiburi ni tomodachi ni aimashita.', pt: 'Encontrei um amigo depois de muito tempo.' },
  '翻訳': { jp: '英語の本を日本語に翻訳します。', r: 'えいごの ほんを にほんごに ほんやくします。', rom: 'eigo no hon o nihongo ni honyakushimasu.', pt: 'Traduzo livros de inglês para japonês.' },
  '星': { jp: '夜空に星が輝いています。', r: 'よぞらに ほしが かがやいています。', rom: 'yozora ni hoshi ga kagayaiteimasu.', pt: 'As estrelas estão brilhando no céu noturno.' },
  'ほとんど': { jp: '宿題はほとんど終わりました。', r: 'しゅくだいは ほとんど おわりました。', rom: 'shukudai wa hotondo owarimashita.', pt: 'A lição de casa está quase terminada.' },
  '法律': { jp: '大学で法律を勉強しています。', r: 'だいがくで ほうりつを べんきょうしています。', rom: 'daigaku de houritsu o benkyoushiteimasu.', pt: 'Estudo direito (leis) na universidade.' },
  '放送': { jp: 'ニュースの放送を聞きました。', r: 'ニュースの ほうそうを ききました。', rom: 'nyuusu no housou o kikimashita.', pt: 'Ouvi a transmissão de notícias.' },
  '一度': { jp: '一度日本へ行ってみたいです。', r: 'いちど にほんへ いってみたいです。', rom: 'ichido nihon e ittemitai desu.', pt: 'Quero tentar ir ao Japão uma vez.' },
  '以外': { jp: '日曜以外は仕事です。', r: 'にちよう いがいは しごとです。', rom: 'nichiyou igai wa shigoto desu.', pt: 'Com exceção de domingo, é trabalho.' },
  '医学': { jp: '彼は医学を研究しています。', r: 'かれは いがくを けんきゅうしています。', rom: 'kare wa igaku o kenkyuushiteimasu.', pt: 'Ele pesquisa medicina.' },
  '以上': { jp: '三十歳以上の人が参加できます。', r: 'さんじゅっさい いじょうの ひとが さんかできます。', rom: 'sanjussai ijou no hito ga sankadekimasu.', pt: 'Pessoas com 30 anos ou mais podem participar.' },
  '以下': { jp: '十歳以下の子供は無料です。', r: 'じゅっさい いかの こどもは むりょうです。', rom: 'jussai ika no kodomo wa muryou desu.', pt: 'Crianças de dez anos ou menos são de graça.' },
  '意見': { jp: 'あなたの意見を聞かせてください。', r: 'あなたの いけんを きかせてください。', rom: 'anata no iken o kikasete kudasai.', pt: 'Deixe-me ouvir a sua opinião, por favor.' },
  '生き物': { jp: '海にはたくさんの生き物がいます。', r: 'うみには たくさんの いきものが います。', rom: 'umi ni wa takusan no ikimono ga imasu.', pt: 'No mar há muitas criaturas vivas.' },
  '以内': { jp: '一時間以内に帰ります。', r: 'いちじかん いないに かえります。', rom: 'ichijikan inai ni kaerimasu.', pt: 'Voltarei dentro de uma hora.' },
  '田舎': { jp: '私の田舎は静かです。', r: 'わたしの いなかは しずかです。', rom: 'watashi no inaka wa shizuka desu.', pt: 'Meu interior (terra natal) é calmo.' },
  'いっぱい': { jp: 'お腹がいっぱいです。', r: 'おなかが いっぱいです。', rom: 'onaka ga ippai desu.', pt: 'A barriga está cheia (Estou satisfeito).' },
  '石': { jp: '道に石が落ちています。', r: 'みちに いしが おちています。', rom: 'michi ni ishi ga ochiteimasu.', pt: 'Há pedras caídas na rua.' }
};

const filePath = path.join(process.cwd(), 'src/data/vocabN4.ts');
let fileContent = fs.readFileSync(filePath, 'utf8');

const newObjects = nouns.map((n, i) => {
  const ex = examples[n.w] || {
    jp: "Exemplo",
    reading: "...",
    rom: "...",
    pt: "..."
  };
  
  const safePt = ex.pt.replace(/'/g, "\\'");

  return "  {\n" +
    "    id: 'n4_noun_batch1_" + Date.now() + "_" + i + "',\n" +
    "    word: '" + n.w + "',\n" +
    "    reading: '" + n.r + "',\n" +
    "    romaji: '" + n.rom + "',\n" +
    "    meaningPt: '" + n.m + "',\n" +
    "    category: 'substantivo',\n" +
    "    jlpt: 'N4',\n" +
    "    categoryLabelPt: 'Substantivo N4',\n" +
    "    exampleSentence: {\n" +
    "      jp: '" + ex.jp + "',\n" +
    "      reading: '" + ex.r + "',\n" +
    "      romaji: '" + ex.rom + "',\n" +
    "      meaningPt: '" + safePt + "'\n" +
    "    }\n" +
    "  }";
}).join(',\n');

fileContent = fileContent.replace(
  /export const VOCAB_N4: VocabItem\[\] = \[/,
  "export const VOCAB_N4: VocabItem[] = [\n" + newObjects + ",\n"
);

fs.writeFileSync(filePath, fileContent, 'utf8');
console.log('Added 100 N4 Nouns to vocabN4.ts successfully!');
