import fs from 'fs';
import path from 'path';

const nouns = [
  { w: '赤', r: 'あか', rom: 'aka', m: 'vermelho; rubro' },
  { w: '秋', r: 'あき', rom: 'aki', m: 'outono' },
  { w: '雨', r: 'あめ', rom: 'ame', m: 'chuva' },
  { w: '飴', r: 'あめ', rom: 'ame_2', m: 'doce; bala' },
  { w: '姉', r: 'あね', rom: 'ane', m: 'irmã mais velha' },
  { w: '兄', r: 'あに', rom: 'ani', m: 'irmão mais velho' },
  { w: '青', r: 'あお', rom: 'ao', m: 'azul; azul claro' },
  { w: 'アパート', r: 'アパート', rom: 'apaato', m: 'apartamento' },
  { w: '朝', r: 'あさ', rom: 'asa', m: 'manhã' },
  { w: '朝ご飯', r: 'あさごはん', rom: 'asagohan', m: 'café da manhã' },
  { w: '明後日', r: 'あさって', rom: 'asatte', m: 'depois de amanhã' },
  { w: '足', r: 'あし', rom: 'ashi', m: 'pé; perna' },
  { w: '明日', r: 'あした', rom: 'ashita', m: 'amanhã' },
  { w: '頭', r: 'あたま', rom: 'atama', m: 'cabeça' },
  { w: '後', r: 'あと', rom: 'ato', m: 'depois; atrás' },
  { w: '晩ご飯', r: 'ばんごはん', rom: 'bangohan', m: 'jantar' },
  { w: '番号', r: 'ばんごう', rom: 'bangou', m: 'número' },
  { w: 'バス', r: 'バス', rom: 'basu', m: 'ônibus' },
  { w: 'バター', r: 'バター', rom: 'bataa', m: 'manteiga' },
  { w: 'ベッド', r: 'ベッド', rom: 'beddo', m: 'cama' },
  { w: '勉強', r: 'べんきょう', rom: 'benkyou', m: 'estudo' },
  { w: 'ボールペン', r: 'ボールペン', rom: 'boorupen', m: 'caneta esferográfica' },
  { w: 'ボタン', r: 'ボタン', rom: 'botan', m: 'botão' },
  { w: '帽子', r: 'ぼうし', rom: 'boushi', m: 'chapéu; boné' },
  { w: '文章', r: 'ぶんしょう', rom: 'bunshou', m: 'frase; texto' },
  { w: '豚肉', r: 'ぶたにく', rom: 'butaniku', m: 'carne de porco' },
  { w: '病院', r: 'びょういん', rom: 'byouin', m: 'hospital' },
  { w: '病気', r: 'びょうき', rom: 'byouki', m: 'doença; enfermidade' },
  { w: '茶色', r: 'ちゃいろ', rom: 'chairo', m: 'marrom; cor de chá' },
  { w: '茶碗', r: 'ちゃわん', rom: 'chawan', m: 'tigela (de arroz); xícara de chá' },
  { w: '父', r: 'ちち', rom: 'chichi', m: 'pai' },
  { w: '地下鉄', r: 'ちかてつ', rom: 'chikatetsu', m: 'metrô' },
  { w: '地図', r: 'ちず', rom: 'chizu', m: 'mapa' },
  { w: '台所', r: 'だいどころ', rom: 'daidokoro', m: 'cozinha' },
  { w: '大学', r: 'だいがく', rom: 'daigaku', m: 'universidade' },
  { w: '出口', r: 'でぐち', rom: 'deguchi', m: 'saída' },
  { w: '電気', r: 'でんき', rom: 'denki', m: 'eletricidade; luz elétrica' },
  { w: '電車', r: 'でんしゃ', rom: 'densha', m: 'trem' },
  { w: '電話', r: 'でんわ', rom: 'denwa', m: 'telefone; ligação' },
  { w: 'デパート', r: 'デパート', rom: 'depaato', m: 'loja de departamentos' },
  { w: 'ドア', r: 'ドア', rom: 'doa', m: 'porta' },
  { w: 'どなた', r: 'どなた', rom: 'donata', m: 'quem (polido)' },
  { w: '動物', r: 'どうぶつ', rom: 'doubutsu', m: 'animal' },
  { w: '土曜日', r: 'どようび', rom: 'doyoubi', m: 'sábado' },
  { w: '絵', r: 'え', rom: 'e', m: 'desenho; pintura; quadro' },
  { w: 'ええ', r: 'ええ', rom: 'ee', m: 'sim (informal)' },
  { w: '映画', r: 'えいが', rom: 'eiga', m: 'filme' },
  { w: '映画館', r: 'えいがかん', rom: 'eigakan', m: 'cinema (lugar)' },
  { w: '英語', r: 'えいご', rom: 'eigo', m: 'idioma inglês' },
  { w: '駅', r: 'えき', rom: 'eki', m: 'estação (de trem)' },
  { w: '鉛筆', r: 'えんぴつ', rom: 'enpitsu', m: 'lápis' },
  { w: 'エレベーター', r: 'エレベーター', rom: 'erebeetaa', m: 'elevador' },
  { w: 'フィルム', r: 'フィルム', rom: 'firumu', m: 'filme (fotográfico)' },
  { w: 'フォーク', r: 'フォーク', rom: 'fooku', m: 'garfo' },
  { w: '服', r: 'ふく', rom: 'fuku', m: 'roupa' },
  { w: '二人', r: 'ふたり', rom: 'futari', m: 'duas pessoas' },
  { w: '二つ', r: 'ふたつ', rom: 'futatsu', m: 'dois (objetos)' },
  { w: '二日', r: 'ふつか', rom: 'futsuka', m: 'dia 2 (do mês); dois dias' },
  { w: '封筒', r: 'ふうとう', rom: 'fuutou', m: 'envelope' },
  { w: '冬', r: 'ふゆ', rom: 'fuyu', m: 'inverno' },
  { w: '外国', r: 'がいこく', rom: 'gaikoku', m: 'país estrangeiro' },
  { w: '外国人', r: 'がいこくじん', rom: 'gaikokujin', m: 'estrangeiro (pessoa)' },
  { w: '学校', r: 'がっこう', rom: 'gakkou', m: 'escola' },
  { w: '学生', r: 'がくせい', rom: 'gakusei', m: 'estudante' },
  { w: '玄関', r: 'げんかん', rom: 'genkan', m: 'hall de entrada; vestíbulo' },
  { w: '元気', r: 'げんき', rom: 'genki', m: 'saúde; energia; vigor' },
  { w: '月曜日', r: 'げつようび', rom: 'getsuyoubi', m: 'segunda-feira' },
  { w: '銀行', r: 'ぎんこう', rom: 'ginkou', m: 'banco (instituição financeira)' },
  { w: 'ギター', r: 'ギター', rom: 'gitaa', m: 'violão; guitarra' },
  { w: '五', r: 'ご', rom: 'go', m: 'cinco; 5' },
  { w: '午後', r: 'ごご', rom: 'gogo', m: 'tarde (PM)' },
  { w: 'ご飯', r: 'ごはん', rom: 'gohan', m: 'arroz cozido; refeição' },
  { w: '午前', r: 'ごぜん', rom: 'gozen', m: 'manhã (AM)' },
  { w: 'グラム', r: 'グラム', rom: 'guramu', m: 'grama (medida)' },
  { w: '牛肉', r: 'ぎゅうにく', rom: 'gyuuniku', m: 'carne de vaca' },
  { w: '牛乳', r: 'ぎゅうにゅう', rom: 'gyuunyuu', m: 'leite (de vaca)' },
  { w: '歯', r: 'は', rom: 'ha', m: 'dente' },
  { w: '八', r: 'はち', rom: 'hachi', m: 'oito; 8' },
  { w: '葉書', r: 'はがき', rom: 'hagaki', m: 'cartão-postal' },
  { w: '母', r: 'はは', rom: 'haha', m: 'mãe' },
  { w: 'はい', r: 'はい', rom: 'hai', m: 'sim' },
  { w: '灰皿', r: 'はいざら', rom: 'haizara', m: 'cinzeiro' },
  { w: '箱', r: 'はこ', rom: 'hako', m: 'caixa' },
  { w: '半', r: 'はん', rom: 'han', m: 'meia; metade (hora)' },
  { w: '花', r: 'はな', rom: 'hana', m: 'flor' },
  { w: '鼻', r: 'はな', rom: 'hana_2', m: 'nariz' },
  { w: '話', r: 'はなし', rom: 'hanashi', m: 'conversa; história' },
  { w: '半分', r: 'はんぶん', rom: 'hanbun', m: 'metade' },
  { w: 'ハンカチ', r: 'ハンカチ', rom: 'hankachi', m: 'lenço (de bolso)' },
  { w: '晴れ', r: 'はれ', rom: 'hare', m: 'tempo ensolarado; tempo limpo' },
  { w: '春', r: 'はる', rom: 'haru', m: 'primavera' },
  { w: '箸', r: 'はし', rom: 'hashi', m: 'hashi; pauzinhos (talher)' },
  { w: '橋', r: 'はし', rom: 'hashi_2', m: 'ponte' },
  { w: '二十歳', r: 'はたち', rom: 'hatachi', m: '20 anos de idade' },
  { w: '二十日', r: 'はつか', rom: 'hatsuka', m: 'dia 20 (do mês); vinte dias' },
  { w: '辺', r: 'へん', rom: 'hen', m: 'área; arredores' },
  { w: '下手', r: 'へた', rom: 'heta', m: 'inábil; ruim em algo' },
  { w: '部屋', r: 'へや', rom: 'heya', m: 'quarto; cômodo' },
  { w: '左', r: 'ひだり', rom: 'hidari', m: 'esquerda' },
  { w: '東', r: 'ひがし', rom: 'higashi', m: 'leste' },
];

const examples = {
  '赤': { jp: '信号が赤になりました。', r: 'しんごうが あかになりました。', rom: 'shingou ga aka ni narimashita.', pt: 'O semáforo ficou vermelho.' },
  '秋': { jp: '秋は涼しいです。', r: 'あきは すずしいです。', rom: 'aki wa suzushii desu.', pt: 'O outono é fresco.' },
  '雨': { jp: '今日は雨が降っています。', r: 'きょうは あめが ふっています。', rom: 'kyou wa ame ga futteimasu.', pt: 'Hoje está chovendo.' },
  '飴': { jp: '子供に飴をあげました。', r: 'こどもに あめを あげました。', rom: 'kodomo ni ame o agemashita.', pt: 'Dei um doce para a criança.' },
  '姉': { jp: '私の姉は先生です。', r: 'わたしの あねは せんせいです。', rom: 'watashi no ane wa sensei desu.', pt: 'Minha irmã mais velha é professora.' },
  '兄': { jp: '兄は大学生です。', r: 'あには だいがくせいです。', rom: 'ani wa daigakusei desu.', pt: 'Meu irmão mais velho é universitário.' },
  '青': { jp: '青い空が綺麗です。', r: 'あおい そらが きれいです。', rom: 'aoi sora ga kirei desu.', pt: 'O céu azul é bonito.' },
  'アパート': { jp: '新しいアパートに引っ越しました。', r: 'あたらしい アパートに ひっこしました。', rom: 'atarashii apaato ni hikkoshimashita.', pt: 'Mudei para um apartamento novo.' },
  '朝': { jp: '毎朝６時に起きます。', r: 'まいあさ ろくじに おきます。', rom: 'maiasa rokuji ni okimasu.', pt: 'Todos os dias acordo às 6 da manhã.' },
  '朝ご飯': { jp: '朝ご飯にパンを食べます。', r: 'あさごはんに パンを たべます。', rom: 'asagohan ni pan o tabemasu.', pt: 'Como pão no café da manhã.' },
  '明後日': { jp: '明後日は休みです。', r: 'あさっては やすみです。', rom: 'asatte wa yasumi desu.', pt: 'Depois de amanhã é folga.' },
  '足': { jp: 'たくさん歩いたので足が痛いです。', r: 'たくさん あるいたので あしが いたいです。', rom: 'takusan aruita node ashi ga itai desu.', pt: 'Meu pé está doendo porque andei muito.' },
  '明日': { jp: '明日の天気はどうですか。', r: 'あしたの てんきは どうですか。', rom: 'ashita no tenki wa dou desu ka.', pt: 'Como estará o tempo amanhã?' },
  '頭': { jp: '頭が痛いです。', r: 'あたまが いたいです。', rom: 'atama ga itai desu.', pt: 'Minha cabeça está doendo.' },
  '後': { jp: '授業の後で会いましょう。', r: 'じゅぎょうの あとで あいましょう。', rom: 'jugyou no ato de aimashou.', pt: 'Vamos nos encontrar depois da aula.' },
  '晩ご飯': { jp: '晩ご飯はカレーでした。', r: 'ばんごはんは カレーでした。', rom: 'bangohan wa karee deshita.', pt: 'O jantar foi curry.' },
  '番号': { jp: '電話番号を教えてください。', r: 'でんわ ばんごうを おしえてください。', rom: 'denwa bangou o oshiete kudasai.', pt: 'Por favor, me informe seu número de telefone.' },
  'バス': { jp: 'バスで学校へ行きます。', r: 'バスで がっこうへ いきます。', rom: 'basu de gakkou e ikimasu.', pt: 'Vou de ônibus para a escola.' },
  'バター': { jp: 'パンにバターを塗ります。', r: 'パンに バターを ぬります。', rom: 'pan ni bataa o nurimasu.', pt: 'Passar manteiga no pão.' },
  'ベッド': { jp: 'ベッドで寝ます。', r: 'ベッドで ねます。', rom: 'beddo de nemasu.', pt: 'Dormir na cama.' },
  '勉強': { jp: '毎日日本語を勉強します。', r: 'まいにち にほんごを べんきょうします。', rom: 'mainichi nihongo o benkyou shimasu.', pt: 'Estudo japonês todos os dias.' },
  'ボールペン': { jp: 'ボールペンで名前を書いてください。', r: 'ボールペンで なまえを かいてください。', rom: 'boorupen de namae o kaite kudasai.', pt: 'Por favor, escreva seu nome de caneta esferográfica.' },
  'ボタン': { jp: 'シャツのボタンが取れました。', r: 'シャツの ボタンが とれました。', rom: 'shatsu no botan ga toremashita.', pt: 'O botão da camisa soltou.' },
  '帽子': { jp: '外に出る時は帽子をかぶります。', r: 'そとに でる ときは ぼうしを かぶります。', rom: 'soto ni deru toki wa boushi o kaburimasu.', pt: 'Ao sair de casa eu coloco um chapéu.' },
  '文章': { jp: '短い文章を書いてください。', r: 'みじかい ぶんしょうを かいてください。', rom: 'mijikai bunshou o kaite kudasai.', pt: 'Escreva uma frase curta, por favor.' },
  '豚肉': { jp: 'スーパーで豚肉を買いました。', r: 'スーパーで ぶたにくを かいました。', rom: 'suupaa de butaniku o kaimashita.', pt: 'Comprei carne de porco no supermercado.' },
  '病院': { jp: '風邪をひいたので病院へ行きます。', r: 'かぜを ひいたので びょういんへ いきます。', rom: 'kaze o hiita node byouin e ikimasu.', pt: 'Vou ao hospital pois peguei um resfriado.' },
  '病気': { jp: '病気で会社を休みました。', r: 'びょうきで かいしゃを やすみました。', rom: 'byouki de kaisha o yasumimashita.', pt: 'Faltei na empresa por causa de doença.' },
  '茶色': { jp: '彼は茶色の靴を履いています。', r: 'かれは ちゃいろの くつを はいています。', rom: 'kare wa chairo no kutsu o haiteimasu.', pt: 'Ele está usando sapatos marrons.' },
  '茶碗': { jp: 'ご飯を茶碗に盛ります。', r: 'ごはんを ちゃわんに もります。', rom: 'gohan o chawan ni morimasu.', pt: 'Servir o arroz na tigela.' },
  '父': { jp: '父は会社員です。', r: 'ちちは かいしゃいんです。', rom: 'chichi wa kaishain desu.', pt: 'Meu pai é funcionário de empresa.' },
  '地下鉄': { jp: '地下鉄はとても便利です。', r: 'ちかてつは とても べんりです。', rom: 'chikatetsu wa totemo benri desu.', pt: 'O metrô é muito conveniente.' },
  '地図': { jp: '駅で地図をもらいました。', r: 'えきで ちずを もらいました。', rom: 'eki de chizu o moraimashita.', pt: 'Peguei um mapa na estação.' },
  '台所': { jp: '母は台所にいます。', r: 'ははは だいどころに います。', rom: 'haha wa daidokoro ni imasu.', pt: 'Minha mãe está na cozinha.' },
  '大学': { jp: '兄は大学で英語を勉強しています。', r: 'あには だいがくで えいごを べんきょうしています。', rom: 'ani wa daigaku de eigo o benkyou shiteimasu.', pt: 'Meu irmão mais velho estuda inglês na universidade.' },
  '出口': { jp: '出口はあちらです。', r: 'でぐちは あちらです。', rom: 'deguchi wa achira desu.', pt: 'A saída é por ali.' },
  '電気': { jp: '部屋が暗いので電気をつけます。', r: 'へやが くらいので でんきを つけます。', rom: 'heya ga kurai node denki o tsukemasu.', pt: 'O quarto está escuro, então vou acender a luz.' },
  '電車': { jp: '電車で会社に通っています。', r: 'でんしゃで かいしゃに かよっています。', rom: 'densha de kaisha ni kayotteimasu.', pt: 'Vou para a empresa de trem.' },
  '電話': { jp: '友達に電話をかけます。', r: 'ともだちに でんわを かけます。', rom: 'tomodachi ni denwa o kakemasu.', pt: 'Vou ligar para um amigo.' },
  'デパート': { jp: '休日はデパートに買い物に行きます。', r: 'きゅうじつは デパートに かいものに いきます。', rom: 'kyuujitsu wa depaato ni kaimono ni ikimasu.', pt: 'No feriado vou fazer compras na loja de departamentos.' },
  'ドア': { jp: 'ドアを開けてください。', r: 'ドアを あけてください。', rom: 'doa o akete kudasai.', pt: 'Abra a porta, por favor.' },
  'どなた': { jp: 'あの方はどなたですか。', r: 'あの かたは どなたですか。', rom: 'ano kata wa donata desu ka.', pt: 'Quem é aquela pessoa?' },
  '動物': { jp: '私は動物が好きです。', r: 'わたしは どうぶつが すきです。', rom: 'watashi wa doubutsu ga suki desu.', pt: 'Eu gosto de animais.' },
  '土曜日': { jp: '土曜日は仕事が休みです。', r: 'どようびは しごとが やすみです。', rom: 'doyoubi wa shigoto ga yasumi desu.', pt: 'Sábado o trabalho é folga.' },
  '絵': { jp: '綺麗な絵を描きました。', r: 'きれいな えを かきました。', rom: 'kirei na e o kakimashita.', pt: 'Desenhei um quadro bonito.' },
  'ええ': { jp: 'ええ、その通りです。', r: 'ええ、その とおりです。', rom: 'ee, sono toori desu.', pt: 'Sim, é isso mesmo.' },
  '映画': { jp: '週末に映画を見ます。', r: 'しゅうまつに えいがを みます。', rom: 'shuumatsu ni eiga o mimasu.', pt: 'Vou ver um filme no final de semana.' },
  '映画館': { jp: '映画館でポップコーンを買います。', r: 'えいがかんで ポップコーンを かいます。', rom: 'eigakan de poppukoon o kaimasu.', pt: 'Vou comprar pipoca no cinema.' },
  '英語': { jp: '英語を話すことができますか。', r: 'えいごを はなすことができますか。', rom: 'eigo o hanasu koto ga dekimasu ka.', pt: 'Você consegue falar inglês?' },
  '駅': { jp: '駅の前で待ち合わせしましょう。', r: 'えきの まえで まちあわせしましょう。', rom: 'eki no mae de machiawaseshimashou.', pt: 'Vamos nos encontrar na frente da estação.' },
  '鉛筆': { jp: '鉛筆でテストを受けます。', r: 'えんぴつで テストを うけます。', rom: 'enpitsu de tesuto o ukemasu.', pt: 'Vou fazer a prova com lápis.' },
  'エレベーター': { jp: 'エレベーターで五階まで行きます。', r: 'エレベーターで ごかいまで いきます。', rom: 'erebeetaa de gokai made ikimasu.', pt: 'Vou até o quinto andar de elevador.' },
  'フィルム': { jp: 'カメラのフィルムを買います。', r: 'カメラの フィルムを かいます。', rom: 'kamera no firumu o kaimasu.', pt: 'Vou comprar filme para a câmera.' },
  'フォーク': { jp: 'ケーキをフォークで食べます。', r: 'ケーキを フォークで たべます。', rom: 'keeki o fooku de tabemasu.', pt: 'Comer bolo com o garfo.' },
  '服': { jp: '新しい服を買いたいです。', r: 'あたらしい ふくを かいたいです。', rom: 'atarashii fuku o kaitai desu.', pt: 'Quero comprar roupas novas.' },
  '二人': { jp: '二人は仲が良いです。', r: 'ふたりは なかが よいです。', rom: 'futari wa naka ga yoi desu.', pt: 'Os dois se dão bem.' },
  '二つ': { jp: 'りんごを二つください。', r: 'りんごを ふたつください。', rom: 'ringo o futatsu kudasai.', pt: 'Me dê duas maçãs, por favor.' },
  '二日': { jp: '二日後に旅行へ行きます。', r: 'ふつかごに りょこうへ いきます。', rom: 'futsukago ni ryokou e ikimasu.', pt: 'Vou viajar daqui a dois dias.' },
  '封筒': { jp: '手紙を封筒に入れます。', r: 'てがみを ふうとうに いれます。', rom: 'tegami o fuutou ni iremasu.', pt: 'Colocar a carta no envelope.' },
  '冬': { jp: '冬は雪が降ります。', r: 'ふゆは ゆきが ふります。', rom: 'fuyu wa yuki ga furimasu.', pt: 'No inverno neva.' },
  '外国': { jp: 'いつか外国に行ってみたいです。', r: 'いつか がいこくに いってみたいです。', rom: 'itsuka gaikoku ni itte mitai desu.', pt: 'Um dia quero ir a um país estrangeiro.' },
  '外国人': { jp: 'あそこに外国人がいます。', r: 'あそこに がいこくじんが います。', rom: 'asoko ni gaikokujin ga imasu.', pt: 'Há um estrangeiro ali.' },
  '学校': { jp: '学校は何時からですか。', r: 'がっこうは なんじからですか。', rom: 'gakkou wa nanji kara desu ka.', pt: 'A escola começa a que horas?' },
  '学生': { jp: '私は日本語の学生です。', r: 'わたしは にほんごの がくせいです。', rom: 'watashi wa nihongo no gakusei desu.', pt: 'Sou um estudante de japonês.' },
  '玄関': { jp: '玄関で靴を脱いでください。', r: 'げんかんで くつを ぬいでください。', rom: 'genkan de kutsu o nuide kudasai.', pt: 'Tire os sapatos no hall de entrada, por favor.' },
  '元気': { jp: 'お元気ですか。', r: 'おげんきですか。', rom: 'ogenki desu ka.', pt: 'Como você está? (Você está bem?)' },
  '月曜日': { jp: '月曜日は忙しいです。', r: 'げつようびは いそがしいです。', rom: 'getsuyoubi wa isogashii desu.', pt: 'Segunda-feira é ocupado.' },
  '銀行': { jp: '銀行にお金を預けます。', r: 'ぎんこうに おかねを あずけます。', rom: 'ginkou ni okane o azukemasu.', pt: 'Vou depositar dinheiro no banco.' },
  'ギター': { jp: 'ギターを弾くのが好きです。', r: 'ギターを ひくのが すきです。', rom: 'gitaa o hiku no ga suki desu.', pt: 'Gosto de tocar violão/guitarra.' },
  '五': { jp: 'このクラスには五人学生がいます。', r: 'この クラスには ごにん がくせいが います。', rom: 'kono kurasu ni wa gonin gakusei ga imasu.', pt: 'Há cinco alunos nesta turma.' },
  '午後': { jp: '午後から雨が降るそうです。', r: 'ごごから あめが ふるそうです。', rom: 'gogo kara ame ga furu sou desu.', pt: 'Ouvi dizer que vai chover a partir da tarde.' },
  'ご飯': { jp: '晩ご飯は何ですか。', r: 'ばんごはんは なんですか。', rom: 'bangohan wa nan desu ka.', pt: 'O que é o jantar?' },
  '午前': { jp: '午前中に掃除を終わらせます。', r: 'ごぜんちゅうに そうじを おわらせます。', rom: 'gozenchuu ni souji o owarasemasu.', pt: 'Vou terminar a limpeza durante a manhã.' },
  'グラム': { jp: '肉を二百グラムください。', r: 'にくを にひゃくグラムください。', rom: 'niku o nihyakuguramu kudasai.', pt: 'Por favor, me dê 200 gramas de carne.' },
  '牛肉': { jp: '牛肉と玉ねぎを炒めます。', r: 'ぎゅうにくと たまねぎを いためます。', rom: 'gyuuniku to tamanegi o itamemasu.', pt: 'Fritar carne de vaca com cebola.' },
  '牛乳': { jp: '毎日牛乳を飲みます。', r: 'まいにち ぎゅうにゅうを のみます。', rom: 'mainichi gyuunyuu o nomimasu.', pt: 'Bebo leite todos os dias.' },
  '歯': { jp: '毎食後に歯を磨きます。', r: 'まいしょくごに はを みがきます。', rom: 'maishokugo ni ha o migakimasu.', pt: 'Escovo os dentes após cada refeição.' },
  '八': { jp: 'りんごを八つ買いました。', r: 'りんごを やっつ かいました。', rom: 'ringo o yattsu kaimashita.', pt: 'Comprei oito maçãs.' },
  '葉書': { jp: '友達に葉書を書きます。', r: 'ともだちに はがきを かきます。', rom: 'tomodachi ni hagaki o kakimasu.', pt: 'Vou escrever um cartão-postal para um amigo.' },
  '母': { jp: '母は料理が上手です。', r: 'ははは りょうりが じょうずです。', rom: 'haha wa ryouri ga jouzu desu.', pt: 'Minha mãe é boa na cozinha.' },
  'はい': { jp: 'はい、わかりました。', r: 'はい、わかりました。', rom: 'hai, wakarimashita.', pt: 'Sim, entendi.' },
  '灰皿': { jp: '灰皿はどこですか。', r: 'はいざらは どこですか。', rom: 'haizara wa doko desu ka.', pt: 'Onde fica o cinzeiro?' },
  '箱': { jp: 'この箱の中に何がありますか。', r: 'この はこの なかに なにが ありますか。', rom: 'kono hako no naka ni nani ga arimasu ka.', pt: 'O que há dentro desta caixa?' },
  '半': { jp: '一時半に会いましょう。', r: 'いちじはんに あいましょう。', rom: 'ichijihan ni aimashou.', pt: 'Vamos nos encontrar à uma e meia.' },
  '花': { jp: '庭に綺麗な花が咲きました。', r: 'にわに きれいな はなが さきました。', rom: 'niwa ni kirei na hana ga sakimashita.', pt: 'Flores bonitas desabrocharam no jardim.' },
  '鼻': { jp: '風邪で鼻が出ます。', r: 'かぜで はなが でます。', rom: 'kaze de hana ga demasu.', pt: 'Meu nariz está escorrendo devido a um resfriado.' },
  '話': { jp: '先生の話を聞きましょう。', r: 'せんせいの はなしを ききましょう。', rom: 'sensei no hanashi o kikimashou.', pt: 'Vamos ouvir o que o professor tem a dizer (a história do professor).' },
  '半分': { jp: 'ケーキを半分に分けましょう。', r: 'ケーキを はんぶんに わけましょう。', rom: 'keeki o hanbun ni wakemashou.', pt: 'Vamos dividir o bolo pela metade.' },
  'ハンカチ': { jp: '手を洗ったらハンカチで拭きます。', r: 'てを あらったら ハンカチで ふきます。', rom: 'te o arattara hankachi de fukimasu.', pt: 'Quando lavo as mãos, enxugo-as com um lenço.' },
  '晴れ': { jp: '明日は晴れるでしょう。', r: 'あしたは はれるでしょう。', rom: 'ashita wa hareru deshou.', pt: 'Amanhã provavelmente fará tempo bom.' },
  '春': { jp: '春になると桜が咲きます。', r: 'はるになると さくらが さきます。', rom: 'haru ni naru to sakura ga sakimasu.', pt: 'Quando chega a primavera, as cerejeiras florescem.' },
  '箸': { jp: '箸を使ってご飯を食べます。', r: 'はしを つかって ごはんを たべます。', rom: 'hashi o tsukatte gohan o tabemasu.', pt: 'Como usando hashis (pauzinhos).' },
  '橋': { jp: '大きな橋を渡ります。', r: 'おおきな はしを わたります。', rom: 'ookina hashi o watarimasu.', pt: 'Vou atravessar a ponte grande.' },
  '二十歳': { jp: '来年、二十歳になります。', r: 'らいねん、はたちになります。', rom: 'rainen, hatachi ni narimasu.', pt: 'No ano que vem, farei 20 anos.' },
  '二十日': { jp: '毎月二十日は給料日です。', r: 'まいつき はつかは きゅうりょうびです。', rom: 'maitsuki hatsuka wa kyuuryoubi desu.', pt: 'Todo dia vinte é dia de pagamento.' },
  '辺': { jp: 'この辺にコンビニはありますか。', r: 'この へんに コンビニは ありますか。', rom: 'kono hen ni konbini wa arimasu ka.', pt: 'Tem alguma loja de conveniência por aqui?' },
  '下手': { jp: '私は歌が下手です。', r: 'わたしは うたが へたです。', rom: 'watashi wa uta ga heta desu.', pt: 'Sou ruim em cantar.' },
  '部屋': { jp: '自分の部屋を掃除します。', r: 'じぶんの へやを そうじします。', rom: 'jibun no heya o soujishimasu.', pt: 'Vou limpar o meu quarto.' },
  '左': { jp: '次の角を左に曲がってください。', r: 'つぎの かどを ひだりに まがってください。', rom: 'tsugi no kado o hidari ni magatte kudasai.', pt: 'Vire à esquerda na próxima esquina, por favor.' },
  '東': { jp: '太陽は東から昇ります。', r: 'たいようは ひがしから のぼります。', rom: 'taiyou wa higashi kara noborimasu.', pt: 'O sol nasce a leste.' },
};

const filePath = path.join(process.cwd(), 'src/data/vocabN5.ts');
let fileContent = fs.readFileSync(filePath, 'utf8');

const newObjects = nouns.map((n, i) => {
  const ex = examples[n.w] || {
    jp: "Exemplo",
    reading: "...",
    rom: "...",
    pt: "..."
  };

  return "  {\n" +
    "    id: 'n5_noun_" + Date.now() + "_" + i + "',\n" +
    "    word: '" + n.w + "',\n" +
    "    reading: '" + n.r + "',\n" +
    "    romaji: '" + n.rom + "',\n" +
    "    meaningPt: '" + n.m + "',\n" +
    "    category: 'substantivo',\n" +
    "    jlpt: 'N5',\n" +
    "    categoryLabelPt: 'Substantivo N5',\n" +
    "    exampleSentence: {\n" +
    "      jp: '" + ex.jp + "',\n" +
    "      reading: '" + ex.r + "',\n" +
    "      romaji: '" + ex.rom + "',\n" +
    "      meaningPt: '" + ex.pt + "'\n" +
    "    }\n" +
    "  }";
}).join(',\n');

fileContent = fileContent.replace(
  /export const VOCAB_N5: VocabItem\[\] = \[/,
  "export const VOCAB_N5: VocabItem[] = [\n" + newObjects + ",\n"
);

fs.writeFileSync(filePath, fileContent, 'utf8');
console.log('Added N5 Nouns to vocabN5.ts successfully!');
