import fs from 'fs';
import path from 'path';

const nouns = [
  { w: '港', r: 'みなと', rom: 'minato', m: 'porto' },
  { w: '味噌', r: 'みそ', rom: 'miso', m: 'pasta de soja (miso)' },
  { w: '都', r: 'みやこ', rom: 'miyako', m: 'capital (antiga/tradicional)' },
  { w: '湖', r: 'みずうみ', rom: 'mizuumi', m: 'lago' },
  { w: '木綿', r: 'もめん', rom: 'momen', m: 'algodão (material)' },
  { w: '森', r: 'もり', rom: 'mori', m: 'floresta; bosque denso' },
  { w: '昔', r: 'むかし', rom: 'mukashi', m: 'antigamente; tempos antigos' },
  { w: '無理', r: 'むり', rom: 'muri', m: 'impossível; irracional' },
  { w: '虫', r: 'むし', rom: 'mushi', m: 'inseto; bicho' },
  { w: '息子', r: 'むすこ', rom: 'musuko', m: 'filho' },
  { w: '娘', r: 'むすめ', rom: 'musume', m: 'filha' },
  { w: '生', r: 'なま', rom: 'nama', m: 'cru; fresco' },
  { w: '寝坊', r: 'ねぼう', rom: 'nebou', m: 'dormir demais; acordar tarde' },
  { w: '値段', r: 'ねだん', rom: 'nedan', m: 'preço; custo' },
  { w: '熱', r: 'ねつ', rom: 'netsu', m: 'febre; calor' },
  { w: '二階建て', r: 'にかいだて', rom: 'nikaidate', m: 'prédio de dois andares' },
  { w: '人形', r: 'にんぎょう', rom: 'ningyou', m: 'boneca; fantoche' },
  { w: '匂い', r: 'におい', rom: 'nioi', m: 'cheiro; odor' },
  { w: '喉', r: 'のど', rom: 'nodo', m: 'garganta' },
  { w: '乗り物', r: 'のりもの', rom: 'norimono', m: 'veículo; meio de transporte' },
  { w: '入学', r: 'にゅうがく', rom: 'nyuugaku', m: 'ingresso (na escola/universidade)' },
  { w: '入院', r: 'にゅういん', rom: 'nyuuin', m: 'internação (hospitalar)' },
  { w: '踊り', r: 'おどり', rom: 'odori', m: 'dança' },
  { w: 'お祝い', r: 'おいわい', rom: 'oiwai', m: 'celebração; felicitação' },
  { w: 'お嬢さん', r: 'おじょうさん', rom: 'ojousan', m: 'filha (de outra pessoa); moça' },
  { w: '屋上', r: 'おくじょう', rom: 'okujou', m: 'terraço; telhado' },
  { w: '贈り物', r: 'おくりもの', rom: 'okurimono', m: 'presente; dádiva' },
  { w: 'お祭り', r: 'おまつり', rom: 'omatsuri', m: 'festival; festa tradicional' },
  { w: 'お見舞い', r: 'おみまい', rom: 'omimai', m: 'visita (a um doente)' },
  { w: 'お土産', r: 'おみやげ', rom: 'omiyage', m: 'souvenir; lembrancinha' },
  { w: 'おもちゃ', r: 'おもちゃ', rom: 'omocha', m: 'brinquedo' },
  { w: '表', r: 'おもて', rom: 'omote', m: 'frente; lado externo' },
  { w: 'オートバイ', r: 'オートバイ', rom: 'ootobai', m: 'motocicleta' },
  { w: 'お礼', r: 'おれい', rom: 'orei', m: 'agradecimento; recompensa' },
  { w: '押し入れ', r: 'おしいれ', rom: 'oshiire', m: 'armário embutido (japonês)' },
  { w: 'お宅', r: 'おたく', rom: 'otaku', m: 'sua casa (polido)' },
  { w: '音', r: 'おと', rom: 'oto', m: 'som; barulho; nota (musical)' },
  { w: 'お釣り', r: 'おつり', rom: 'otsuri', m: 'troco' },
  { w: '夫', r: 'おっと', rom: 'otto', m: 'marido' },
  { w: '終わり', r: 'おわり', rom: 'owari', m: 'fim; término' },
  { w: '親', r: 'おや', rom: 'oya', m: 'pais (mãe e pai)' },
  { w: '泳ぎ方', r: 'およぎかた', rom: 'oyogikata', m: 'modo de nadar' },
  { w: 'パート', r: 'パート', rom: 'paato', m: 'trabalho de meio período (part-time)' },
  { w: 'パソコン', r: 'パソコン', rom: 'pasokon', m: 'computador pessoal (PC)' },
  { w: 'ピアノ', r: 'ピアノ', rom: 'piano', m: 'piano' },
  { w: 'プレゼント', r: 'プレゼント', rom: 'purezento', m: 'presente' },
  { w: '冷房', r: 'れいぼう', rom: 'reibou', m: 'ar-condicionado (refrigeração)' },
  { w: 'レジ', r: 'レジ', rom: 'reji', m: 'caixa (registradora)' },
  { w: '歴史', r: 'れきし', rom: 'rekishi', m: 'história' },
  { w: 'レポート', r: 'レポート', rom: 'repooto', m: 'relatório; trabalho escolar' },
  { w: '利用', r: 'りよう', rom: 'riyou', m: 'uso; utilização' },
  { w: '理由', r: 'りゆう', rom: 'riyuu', m: 'razão; motivo' },
  { w: '留守', r: 'るす', rom: 'rusu', m: 'ausência (de casa)' },
  { w: '旅館', r: 'りょかん', rom: 'ryokan', m: 'pousada tradicional japonesa' },
  { w: '両方', r: 'りょうほう', rom: 'ryouhou', m: 'ambos; os dois lados' },
  { w: '最後', r: 'さいご', rom: 'saigo', m: 'último; fim' },
  { w: '最近', r: 'さいきん', rom: 'saikin', m: 'recentemente; ultimamente' },
  { w: '最初', r: 'さいしょ', rom: 'saisho', m: 'início; o primeiro' },
  { w: '坂', r: 'さか', rom: 'saka', m: 'ladeira; subida/descida' },
  { w: '昨夜', r: 'さくや', rom: 'sakuya', m: 'noite passada; ontem à noite' },
  { w: 'サンダル', r: 'サンダル', rom: 'sandaru', m: 'sandália' },
  { w: 'サンドイッチ', r: 'サンドイッチ', rom: 'sandoicchi', m: 'sanduíche' },
  { w: '産業', r: 'さんぎょう', rom: 'sangyou', m: 'indústria (setor)' },
  { w: 'サラダ', r: 'サラダ', rom: 'sarada', m: 'salada' },
  { w: '再来月', r: 'さらいげつ', rom: 'saraigetsu', m: 'mês seguinte ao próximo' },
  { w: '再来週', r: 'さらいしゅう', rom: 'saraishuu', m: 'semana seguinte à próxima' },
  { w: '生物', r: 'せいぶつ', rom: 'seibutsu', m: 'criatura viva; biologia' },
  { w: '政治', r: 'せいじ', rom: 'seiji', m: 'política' },
  { w: '生活', r: 'せいかつ', rom: 'seikatsu', m: 'vida cotidiana; sustento' },
  { w: '生命', r: 'せいめい', rom: 'seimei', m: 'vida; existência' },
  { w: '生産', r: 'せいさん', rom: 'seisan', m: 'produção; fabricação' },
  { w: '西洋', r: 'せいよう', rom: 'seiyou', m: 'Ocidente' },
  { w: '世界', r: 'せかい', rom: 'sekai', m: 'mundo' },
  { w: '席', r: 'せき', rom: 'seki', m: 'assento; lugar' },
  { w: '線', r: 'せん', rom: 'sen', m: 'linha' },
  { w: '背中', r: 'せなか', rom: 'senaka', m: 'costas (do corpo)' },
  { w: '先輩', r: 'せんぱい', rom: 'senpai', m: 'veterano; sênior' },
  { w: '戦争', r: 'せんそう', rom: 'sensou', m: 'guerra' },
  { w: '説明', r: 'せつめい', rom: 'setsumei', m: 'explicação' },
  { w: '社長', r: 'しゃちょう', rom: 'shachou', m: 'presidente de empresa' },
  { w: '社会', r: 'しゃかい', rom: 'shakai', m: 'sociedade; mundo público' },
  { w: '市', r: 'し', rom: 'shi', m: 'cidade (município)' },
  { w: '試合', r: 'しあい', rom: 'shiai', m: 'partida; jogo (esporte)' },
  { w: '仕方', r: 'しかた', rom: 'shikata', m: 'método; forma de fazer' },
  { w: '試験', r: 'しけん', rom: 'shiken', m: 'exame; prova' },
  { w: '島', r: 'しま', rom: 'shima', m: 'ilha' },
  { w: '市民', r: 'しみん', rom: 'shimin', m: 'cidadão' },
  { w: '品物', r: 'しなもの', rom: 'shinamono', m: 'mercadoria; artigo' },
  { w: '新聞社', r: 'しんぶんしゃ', rom: 'shinbunsha', m: 'empresa de jornal' },
  { w: '親切', r: 'しんせつ', rom: 'shinsetsu', m: 'gentileza' },
  { w: '失敗', r: 'しっぱい', rom: 'shippai', m: 'falha; fracasso' },
  { w: '下着', r: 'したぎ', rom: 'shitagi', m: 'roupa íntima' },
  { w: '食料品', r: 'しょくりょうひん', rom: 'shokuryouhin', m: 'alimentos; mantimentos' },
  { w: '小学校', r: 'しょうがっこう', rom: 'shougakkou', m: 'escola de ensino fundamental (primário)' },
  { w: '紹介', r: 'しょうかい', rom: 'shoukai', m: 'apresentação (de alguém); introdução' },
  { w: '将来', r: 'しょうらい', rom: 'shourai', m: 'futuro (próximo/pessoal)' },
  { w: '小説', r: 'しょうせつ', rom: 'shousetsu', m: 'romance (livro)' },
  { w: '趣味', r: 'しゅみ', rom: 'shumi', m: 'hobby; passatempo' },
  { w: '習慣', r: 'しゅうかん', rom: 'shuukan', m: 'hábito; costume' },
  { w: '祖母', r: 'そぼ', rom: 'sobo', m: 'avó' }
];

const examples = {
  '港': { jp: '港に大きな船がいます。', r: 'みなとに おおきな ふねが います。', rom: 'minato ni ookina fune ga imasu.', pt: 'Há um grande navio no porto.' },
  '味噌': { jp: '味噌汁を作ります。', r: 'みそしるを つくります。', rom: 'misoshiru o tsukurimasu.', pt: 'Vou fazer sopa de miso.' },
  '都': { jp: '京都は古い都です。', r: 'きょうとは ふるい みやこです。', rom: 'kyouto wa furui miyako desu.', pt: 'Quioto é uma antiga capital.' },
  '湖': { jp: '湖でボートに乗ります。', r: 'みずうみで ボートに のります。', rom: 'mizuumi de booto ni norimasu.', pt: 'Andar de barco no lago.' },
  '木綿': { jp: 'これは木綿のシャツです。', r: 'これは もめんの シャツです。', rom: 'kore wa momen no shatsu desu.', pt: 'Esta é uma camisa de algodão.' },
  '森': { jp: '森の中に動物がいます。', r: 'もりの なかに どうぶつが います。', rom: 'mori no naka ni doubutsu ga imasu.', pt: 'Há animais na floresta.' },
  '昔': { jp: '昔の話を聞かせてください。', r: 'むかしの はなしを きかせてください。', rom: 'mukashi no hanashi o kikasete kudasai.', pt: 'Conte-me histórias dos velhos tempos, por favor.' },
  '無理': { jp: '無理をしないでください。', r: 'むりを しないでください。', rom: 'muri o shinaide kudasai.', pt: 'Não force o impossível (não se esforce demais).' },
  '虫': { jp: '私は虫が嫌いです。', r: 'わたしは むしが きらいです。', rom: 'watashi wa mushi ga kirai desu.', pt: 'Eu não gosto de insetos.' },
  '息子': { jp: '私の息子は小学生です。', r: 'わたしの むすこは しょうがくせいです。', rom: 'watashi no musuko wa shougakusei desu.', pt: 'Meu filho está no ensino fundamental.' },
  '娘': { jp: '娘はピアノを習っています。', r: 'むすめは ピアノを ならっています。', rom: 'musume wa piano o naratteimasu.', pt: 'Minha filha está aprendendo piano.' },
  '生': { jp: '生の魚は食べられません。', r: 'なまの さかなは たべられません。', rom: 'nama no sakana wa taberaremasen.', pt: 'Não consigo comer peixe cru.' },
  '寝坊': { jp: '今朝は寝坊してしまいました。', r: 'けさは ねぼうしてしまいました。', rom: 'kesa wa nebou shiteshimaimashita.', pt: 'Esta manhã eu dormi demais (acordei tarde).' },
  '値段': { jp: 'この靴の値段は高いです。', r: 'この くつの ねだんは たかいです。', rom: 'kono kutsu no nedan wa takai desu.', pt: 'O preço deste sapato é alto.' },
  '熱': { jp: '熱があるので休みます。', r: 'ねつが あるので やすみます。', rom: 'netsu ga aru node yasumimasu.', pt: 'Como tenho febre, vou descansar.' },
  '二階建て': { jp: 'あの家は二階建てです。', r: 'あの いえは にかいだてです。', rom: 'ano ie wa nikaidate desu.', pt: 'Aquela casa é de dois andares.' },
  '人形': { jp: '日本の人形を買いました。', r: 'にほんの にんぎょうを かいました。', rom: 'nihon no ningyou o kaimashita.', pt: 'Comprei uma boneca japonesa.' },
  '匂い': { jp: '花のいい匂いがします。', r: 'はなの いい においが します。', rom: 'hana no ii nioi ga shimasu.', pt: 'Tem um cheiro bom de flores.' },
  '喉': { jp: '風邪で喉が痛いです。', r: 'かぜで のどが いたいです。', rom: 'kaze de nodo ga itai desu.', pt: 'Minha garganta dói por causa do resfriado.' },
  '乗り物': { jp: '乗り物に酔いやすいです。', r: 'のりものに よいやすいです。', rom: 'norimono ni yoiyasui desu.', pt: 'Enjoo facilmente em veículos.' },
  '入学': { jp: '大学に入学しました。', r: 'だいがくに にゅうがくしました。', rom: 'daigaku ni nyuugakushimashita.', pt: 'Ingressei na universidade.' },
  '入院': { jp: '祖母が病院に入院しました。', r: 'そぼが びょういんに にゅういんしました。', rom: 'sobo ga byouin ni nyuuinshimashita.', pt: 'Minha avó foi internada no hospital.' },
  '踊り': { jp: '祭りで踊りを見ました。', r: 'まつりで おどりを みました。', rom: 'matsuri de odori o mimashita.', pt: 'Vi a dança no festival.' },
  'お祝い': { jp: '結婚のお祝いを贈ります。', r: 'けっこんの おいわいを おくります。', rom: 'kekkon no oiwai o okurimasu.', pt: 'Enviar um presente de comemoração do casamento.' },
  'お嬢さん': { jp: '社長のお嬢さんに会いました。', r: 'しゃちょうの おじょうさんに あいました。', rom: 'shachou no ojousan ni aimashita.', pt: 'Encontrei a filha do presidente (da empresa).' },
  '屋上': { jp: 'デパートの屋上にいます。', r: 'デパートの おくじょうに います。', rom: 'depaato no okujou ni imasu.', pt: 'Estou no terraço da loja de departamentos.' },
  '贈り物': { jp: '母に贈り物をしました。', r: 'ははに おくりものを しました。', rom: 'haha ni okurimono o shimashita.', pt: 'Dei um presente para a minha mãe.' },
  'お祭り': { jp: '夏のお祭りは楽しいです。', r: 'なつの おまつりは たのしいです。', rom: 'natsu no omatsuri wa tanoshii desu.', pt: 'O festival de verão é divertido.' },
  'お見舞い': { jp: '友達のお見舞いに行きます。', r: 'ともだちの おみまいに いきます。', rom: 'tomodachi no omimai ni ikimasu.', pt: 'Vou fazer uma visita ao meu amigo doente.' },
  'お土産': { jp: '旅行のお土産を買いました。', r: 'りょこうの おみやげを かいました。', rom: 'ryokou no omiyage o kaimashita.', pt: 'Comprei lembrancinhas da viagem.' },
  'おもちゃ': { jp: '子供におもちゃをあげます。', r: 'こどもに おもちゃを あげます。', rom: 'kodomo ni omocha o agemasu.', pt: 'Dou um brinquedo à criança.' },
  '表': { jp: '建物の表に車を止めました。', r: 'たてものの おもてに くるまを とめました。', rom: 'tatemono no omote ni kuruma o tomemashita.', pt: 'Parei o carro na frente do prédio.' },
  'オートバイ': { jp: 'オートバイで通勤します。', r: 'オートバイで つうきんします。', rom: 'ootobai de tsuukinshimasu.', pt: 'Vou trabalhar de motocicleta.' },
  'お礼': { jp: '手伝ってくれたお礼を言います。', r: 'てつだってくれた おれいを いいます。', rom: 'tetsudattekureta orei o iimasu.', pt: 'Digo obrigado como forma de agradecimento pela ajuda.' },
  '押し入れ': { jp: '布団を押し入れに片付けます。', r: 'ふとんを おしいれに かたづけます。', rom: 'futon o oshiire ni katadukemasu.', pt: 'Guardo o futon no armário embutido.' },
  'お宅': { jp: '先生のお宅へ伺います。', r: 'せんせいの おたくへ うかがいます。', rom: 'sensei no otaku e ukagaimasu.', pt: 'Visitarei a casa do professor (humilde).' },
  '音': { jp: '外から大きな音が聞こえます。', r: 'そとから おおきな おとが きこえます。', rom: 'soto kara ookina oto ga kikoemasu.', pt: 'Ouço um barulho alto vindo de fora.' },
  'お釣り': { jp: 'お釣りをもらうのを忘れました。', r: 'おつりを もらうのを わすれました。', rom: 'otsuri o morau no o wasuremashita.', pt: 'Esqueci de pegar o troco.' },
  '夫': { jp: '私の夫は会社員です。', r: 'わたしの おっとは かいしゃいんです。', rom: 'watashi no otto wa kaishain desu.', pt: 'Meu marido é funcionário de empresa.' },
  '終わり': { jp: '映画の終わりが面白かったです。', r: 'えいがの おわりが おもしろかったです。', rom: 'eiga no owari ga omoshirokatta desu.', pt: 'O final do filme foi interessante.' },
  '親': { jp: '親に手紙を書きます。', r: 'おやに てがみを かきます。', rom: 'oya ni tegami o kakimasu.', pt: 'Escrevo uma carta aos meus pais.' },
  '泳ぎ方': { jp: '泳ぎ方を教えてください。', r: 'およぎかたを おしえてください。', rom: 'oyogikata o oshiete kudasai.', pt: 'Por favor, ensine-me a nadar (o jeito de nadar).' },
  'パート': { jp: '母はスーパーでパートをしています。', r: 'ははは スーパーで パートを しています。', rom: 'haha wa suupaa de paato o shiteimasu.', pt: 'Minha mãe trabalha de meio período no supermercado.' },
  'パソコン': { jp: 'パソコンで仕事をします。', r: 'パソコンで しごとを します。', rom: 'pasokon de shigoto o shimasu.', pt: 'Trabalho usando o computador.' },
  'ピアノ': { jp: '彼女はピアノを弾くのが上手です。', r: 'かのじょは ピアノを ひくのが じょうずです。', rom: 'kanojo wa piano o hiku no ga jouzu desu.', pt: 'Ela é boa em tocar piano.' },
  'プレゼント': { jp: '誕生日プレゼントをもらいました。', r: 'たんじょうび プレゼントを もらいました。', rom: 'tanjoubi purezento o moraimashita.', pt: 'Ganhei um presente de aniversário.' },
  '冷房': { jp: '冷房をつけて涼しくします。', r: 'れいぼうを つけて すずしくします。', rom: 'reibou o tsukete suzushiku shimasu.', pt: 'Ligar o ar-condicionado para esfriar.' },
  'レジ': { jp: 'レジでお金を払います。', r: 'レジで おかねを はらいます。', rom: 'reji de okane o haraimasu.', pt: 'Pago o dinheiro no caixa.' },
  '歴史': { jp: '日本の歴史を勉強します。', r: 'にほんの れきしを べんきょうします。', rom: 'nihon no rekishi o benkyoushimasu.', pt: 'Estudo a história do Japão.' },
  'レポート': { jp: '明日までにレポートを書きます。', r: 'あしたまでに レポートを かきます。', rom: 'ashita made ni repooto o kakimasu.', pt: 'Escreverei o relatório até amanhã.' },
  '利用': { jp: '図書館を利用します。', r: 'としょかんを りようします。', rom: 'toshokan o riyoushimasu.', pt: 'Utilizo a biblioteca.' },
  '理由': { jp: '遅れた理由を説明してください。', r: 'おくれた りゆうを せつめいしてください。', rom: 'okureta riyuu o setsumeishite kudasai.', pt: 'Por favor, explique o motivo do atraso.' },
  '留守': { jp: '彼は今、留守です。', r: 'かれは いま、るすです。', rom: 'kare wa ima, rusu desu.', pt: 'Ele está ausente agora.' },
  '旅館': { jp: '旅行で旅館に泊まりました。', r: 'りょこうで りょかんに とまりました。', rom: 'ryokou de ryokan ni tomarimashita.', pt: 'Hospedei-me numa pousada tradicional na viagem.' },
  '両方': { jp: 'りんごとみかん、両方好きです。', r: 'りんごと みかん、りょうほう すきです。', rom: 'ringo to mikan, ryouhou suki desu.', pt: 'Gosto de maçã e tangerina, de ambos.' },
  '最後': { jp: '最後まで頑張ります。', r: 'さいごまで がんばります。', rom: 'saigo made ganbarimasu.', pt: 'Vou me esforçar até o fim.' },
  '最近': { jp: '最近、忙しいです。', r: 'さいきん、いそがしいです。', rom: 'saikin, isogashii desu.', pt: 'Recentemente, estou ocupado.' },
  '最初': { jp: '最初からやり直します。', r: 'さいしょから やりなおします。', rom: 'saisho kara yarinaoshimasu.', pt: 'Vou refazer desde o início.' },
  '坂': { jp: '自転車で坂を上ります。', r: 'じてんしゃで さかを のぼります。', rom: 'jitensha de saka o noborimasu.', pt: 'Subo a ladeira de bicicleta.' },
  '昨夜': { jp: '昨夜は遅くまで起きていました。', r: 'さくやは おそくまで おきていました。', rom: 'sakuya wa osoku made okiteimashita.', pt: 'Ontem à noite fiquei acordado até tarde.' },
  'サンダル': { jp: '夏はサンダルを履きます。', r: 'なつは サンダルを はきます。', rom: 'natsu wa sandaru o hakimasu.', pt: 'No verão eu calço sandálias.' },
  'サンドイッチ': { jp: '昼ご飯にサンドイッチを作りました。', r: 'ひるごはんに サンドイッチを つくりました。', rom: 'hirugohan ni sandoicchi o tsukurimashita.', pt: 'Fiz sanduíche para o almoço.' },
  '産業': { jp: 'この国の産業は発展しています。', r: 'この くにの さんぎょうは はってんしています。', rom: 'kono kuni no sangyou wa hattenshiteimasu.', pt: 'A indústria deste país está se desenvolvendo.' },
  'サラダ': { jp: '野菜サラダを食べます。', r: 'やさい サラダを たべます。', rom: 'yasai sarada o tabemasu.', pt: 'Como salada de vegetais.' },
  '再来月': { jp: '再来月に帰国します。', r: 'さらいげつに きこくします。', rom: 'saraigetsu ni kikokushimasu.', pt: 'Voltarei ao meu país no mês seguinte ao próximo.' },
  '再来週': { jp: '再来週、テストがあります。', r: 'さらいしゅう、テストが あります。', rom: 'saraishuu, tesuto ga arimasu.', pt: 'Haverá prova na semana seguinte à próxima.' },
  '生物': { jp: '大学で生物を勉強しています。', r: 'だいがくで せいぶつを べんきょうしています。', rom: 'daigaku de seibutsu o benkyoushiteimasu.', pt: 'Estou estudando biologia na universidade.' },
  '政治': { jp: '政治のニュースを読みます。', r: 'せいじの ニュースを よみます。', rom: 'seiji no nyuusu o yomimasu.', pt: 'Leio as notícias de política.' },
  '生活': { jp: '日本の生活に慣れました。', r: 'にほんの せいかつに なれました。', rom: 'nihon no seikatsu ni naremashita.', pt: 'Acostumei-me à vida no Japão.' },
  '生命': { jp: '生命を大切にしましょう。', r: 'せいめいを たいせつに しましょう。', rom: 'seimei o taisetsu ni shimashou.', pt: 'Vamos valorizar a vida.' },
  '生産': { jp: '車を生産する工場です。', r: 'くるまを せいさんする こうじょうです。', rom: 'kuruma o seisansuru koujou desu.', pt: 'É uma fábrica que produz carros.' },
  '西洋': { jp: '西洋の文化に興味があります。', r: 'せいようの ぶんかに きょうみが あります。', rom: 'seiyou no bunka ni kyoumi ga arimasu.', pt: 'Tenho interesse na cultura ocidental.' },
  '世界': { jp: '世界中を旅行したいです。', r: 'せかいじゅうを りょこうしたいです。', rom: 'sekaijuu o ryokoushitai desu.', pt: 'Quero viajar pelo mundo todo.' },
  '席': { jp: '席に座ってください。', r: 'せきに すわってください。', rom: 'seki ni suwatte kudasai.', pt: 'Sente-se no seu lugar (assento), por favor.' },
  '線': { jp: 'ここに線を引いてください。', r: 'ここに せんを ひいてください。', rom: 'koko ni sen o hiite kudasai.', pt: 'Por favor, desenhe uma linha aqui.' },
  '背中': { jp: '背中が痛いです。', r: 'せなかが いたいです。', rom: 'senaka ga itai desu.', pt: 'Minhas costas estão doendo.' },
  '先輩': { jp: '先輩に仕事を教えてもらいます。', r: 'せんぱいに しごとを おしえてもらいます。', rom: 'senpai ni shigoto o oshietemoraimasu.', pt: 'Meu veterano me ensina o trabalho.' },
  '戦争': { jp: '戦争は悲しいことです。', r: 'せんそうは かなしい ことです。', rom: 'sensou wa kanashii koto desu.', pt: 'A guerra é uma coisa triste.' },
  '説明': { jp: '使い方の説明を読みます。', r: 'つかいかたの せつめいを よみます。', rom: 'tsukaikata no setsumei o yomimasu.', pt: 'Leio a explicação do modo de uso.' },
  '社長': { jp: '社長と会議をします。', r: 'しゃちょうと かいぎを します。', rom: 'shachou to kaigi o shimasu.', pt: 'Terei uma reunião com o presidente da empresa.' },
  '社会': { jp: '社会のルールを守ります。', r: 'しゃかいの ルールを まもります。', rom: 'shakai no ruuru o mamorimasu.', pt: 'Cumprirei as regras da sociedade.' },
  '市': { jp: '私はこの市に住んでいます。', r: 'わたしは この しに すんでいます。', rom: 'watashi wa kono shi ni sundeimasu.', pt: 'Eu moro nesta cidade (município).' },
  '試合': { jp: '明日はサッカーの試合があります。', r: 'あしたは サッカーの しあいが あります。', rom: 'ashita wa sakkaa no shiai ga arimasu.', pt: 'Amanhã tem partida de futebol.' },
  '仕方': { jp: '機械の使い方がわかりません。', r: 'きかいの つかいかたが わかりません。', rom: 'kikai no tsukaikata ga wakarimasen.', pt: 'Não sei o método de uso da máquina.' },
  '試験': { jp: '来週、入学試験があります。', r: 'らいしゅう、にゅうがく しけんが あります。', rom: 'raishuu, nyuugaku shiken ga arimasu.', pt: 'Semana que vem há um exame de admissão.' },
  '島': { jp: '南の島へ行きたいです。', r: 'みなみの しまへ いきたいです。', rom: 'minami no shima e ikitai desu.', pt: 'Quero ir para uma ilha do sul.' },
  '市民': { jp: '市民の意見を聞きます。', r: 'しみんの いけんを ききます。', rom: 'shimin no iken o kikimasu.', pt: 'Ouviremos as opiniões dos cidadãos.' },
  '品物': { jp: '良い品物を安く買いました。', r: 'よい しなものを やすく かいました。', rom: 'yoi shinamono o yasuku kaimashita.', pt: 'Comprei mercadorias boas por um preço barato.' },
  '新聞社': { jp: '彼は新聞社で働いています。', r: 'かれは しんぶんしゃで はたらいています。', rom: 'kare wa shinbunsha de hataraiteimasu.', pt: 'Ele trabalha em uma empresa de jornal.' },
  '親切': { jp: 'あなたの親切に感謝します。', r: 'あなたの しんせつに かんしゃします。', rom: 'anata no shinsetsu ni kanshashimasu.', pt: 'Agradeço por sua gentileza.' },
  '失敗': { jp: 'テストで失敗しました。', r: 'テストで しっぱいしました。', rom: 'tesuto de shippaishimashita.', pt: 'Falhei/fui mal na prova.' },
  '下着': { jp: '新しい下着を買いました。', r: 'あたらしい したぎを かいました。', rom: 'atarashii shitagi o kaimashita.', pt: 'Comprei roupas íntimas novas.' },
  '食料品': { jp: 'スーパーで食料品を買います。', r: 'スーパーで しょくりょうひんを かいます。', rom: 'suupaa de shokuryouhin o kaimasu.', pt: 'Compro mantimentos no supermercado.' },
  '小学校': { jp: '弟は小学校に入学しました。', r: 'おとうとは しょうがっこうに にゅうがくしました。', rom: 'otouto wa shougakkou ni nyuugakushimashita.', pt: 'Meu irmão mais novo entrou na escola primária.' },
  '紹介': { jp: '自己紹介をします。', r: 'じこ しょうかいを します。', rom: 'jiko shoukai o shimasu.', pt: 'Vou fazer minha auto-apresentação.' },
  '将来': { jp: '将来の夢は医者になることです。', r: 'しょうらいの ゆめは いしゃに なることです。', rom: 'shourai no yume wa isha ni naru koto desu.', pt: 'Meu sonho para o futuro é me tornar médico.' },
  '小説': { jp: '暇な時は小説を読みます。', r: 'ひまな ときは しょうせつを よみます。', rom: 'hima na toki wa shousetsu o yomimasu.', pt: 'Quando tenho tempo livre, leio romances.' },
  '趣味': { jp: '私の趣味は音楽を聞くことです。', r: 'わたしの しゅみは おんがくを きくことです。', rom: 'watashi no shumi wa ongaku o kiku koto desu.', pt: 'Meu hobby é ouvir música.' },
  '習慣': { jp: '朝早く起きる習慣があります。', r: 'あさ はやく おきる しゅうかんが あります。', rom: 'asa hayaku okiru shuukan ga arimasu.', pt: 'Tenho o hábito de acordar cedo de manhã.' },
  '祖母': { jp: '祖母は九十歳です。', r: 'そぼは きゅうじゅっさいです。', rom: 'sobo wa kyuujussai desu.', pt: 'Minha avó tem 90 anos.' }
};

const filePath = path.join(process.cwd(), 'src/data/vocabN4.ts');
let fileContent = fs.readFileSync(filePath, 'utf8');

const newObjects = nouns.map((n, i) => {
  const ex = examples[n.w] || {
    jp: "Exemplo",
    reading: "...",
    rom: "...",
    pt: "..."
  };
  
  const safePt = ex.pt.replace(/'/g, "\\'");

  return "  {\n" +
    "    id: 'n4_noun_batch3_" + Date.now() + "_" + i + "',\n" +
    "    word: '" + n.w + "',\n" +
    "    reading: '" + n.r + "',\n" +
    "    romaji: '" + n.rom + "',\n" +
    "    meaningPt: '" + n.m + "',\n" +
    "    category: 'substantivo',\n" +
    "    jlpt: 'N4',\n" +
    "    categoryLabelPt: 'Substantivo N4',\n" +
    "    exampleSentence: {\n" +
    "      jp: '" + ex.jp + "',\n" +
    "      reading: '" + ex.r + "',\n" +
    "      romaji: '" + ex.rom + "',\n" +
    "      meaningPt: '" + safePt + "'\n" +
    "    }\n" +
    "  }";
}).join(',\n');

fileContent = fileContent.replace(
  /export const VOCAB_N4: VocabItem\[\] = \[/,
  "export const VOCAB_N4: VocabItem[] = [\n" + newObjects + ",\n"
);

fs.writeFileSync(filePath, fileContent, 'utf8');
console.log('Added 100 more N4 Nouns to vocabN4.ts successfully!');
