import fs from 'fs';
import path from 'path';

const nouns = [
  { w: '黒', r: 'くろ', rom: 'kuro', m: 'preto' },
  { w: '車', r: 'くるま', rom: 'kuruma', m: 'carro; automóvel' },
  { w: '薬', r: 'くすり', rom: 'kusuri', m: 'remédio; medicamento' },
  { w: '靴', r: 'くつ', rom: 'kutsu', m: 'sapatos' },
  { w: '靴下', r: 'くつした', rom: 'kutsushita', m: 'meias' },
  { w: '去年', r: 'きょねん', rom: 'kyonen', m: 'ano passado' },
  { w: '今日', r: 'きょう', rom: 'kyou', m: 'hoje' },
  { w: '兄弟', r: 'きょうだい', rom: 'kyoudai', m: 'irmãos (e irmãs)' },
  { w: '教室', r: 'きょうしつ', rom: 'kyoushitsu', m: 'sala de aula' },
  { w: '九', r: 'きゅう', rom: 'kyuu', m: 'nove; 9' },
  { w: 'マッチ', r: 'マッチ', rom: 'macchi', m: 'fósforo (de acender)' },
  { w: '町', r: 'まち', rom: 'machi', m: 'cidade; bairro' },
  { w: '窓', r: 'まど', rom: 'mado', m: 'janela' },
  { w: '前', r: 'まえ', rom: 'mae', m: 'frente; antes' },
  { w: '毎朝', r: 'まいあさ', rom: 'maiasa', m: 'toda manhã' },
  { w: '毎晩', r: 'まいばん', rom: 'maiban', m: 'toda noite' },
  { w: '毎日', r: 'まいにち', rom: 'mainichi', m: 'todo dia' },
  { w: '毎週', r: 'まいしゅう', rom: 'maishuu', m: 'toda semana' },
  { w: '毎年', r: 'まいとし', rom: 'maitoshi / mainen', m: 'todo ano' },
  { w: '毎月', r: 'まいつき', rom: 'maitsuki', m: 'todo mês' },
  { w: '万', r: 'まん', rom: 'man', m: 'dez mil; 10.000' },
  { w: '万年筆', r: 'まんねんひつ', rom: 'mannenhitsu', m: 'caneta-tinteiro' },
  { w: '真っ直ぐ', r: 'まっすぐ', rom: 'massugu', m: 'reto; direto' },
  { w: '目', r: 'め', rom: 'me', m: 'olho(s)' },
  { w: 'メートル', r: 'メートル', rom: 'meetoru', m: 'metro' },
  { w: '眼鏡', r: 'めがね', rom: 'megane', m: 'óculos' },
  { w: '道', r: 'みち', rom: 'michi', m: 'caminho; rua' },
  { w: '緑', r: 'みどり', rom: 'midori', m: 'verde' },
  { w: '右', r: 'みぎ', rom: 'migi', m: 'direita' },
  { w: '三日', r: 'みっか', rom: 'mikka', m: 'dia 3 (do mês); três dias' },
  { w: '耳', r: 'みみ', rom: 'mimi', m: 'orelha; ouvido' },
  { w: '南', r: 'みなみ', rom: 'minami', m: 'sul' },
  { w: '皆さん', r: 'みなさん', rom: 'minasan', m: 'todos; senhoras e senhores' },
  { w: 'みんな', r: 'みんな', rom: 'minna', m: 'todos; todo mundo' },
  { w: '店', r: 'みせ', rom: 'mise', m: 'loja; estabelecimento' },
  { w: '三つ', r: 'みっつ', rom: 'mittsu', m: 'três (objetos)' },
  { w: '水', r: 'みず', rom: 'mizu', m: 'água' },
  { w: '木曜日', r: 'もくようび', rom: 'mokuyoubi', m: 'quinta-feira' },
  { w: '門', r: 'もん', rom: 'mon', m: 'portão' },
  { w: '問題', r: 'もんだい', rom: 'mondai', m: 'problema; questão (de prova)' },
  { w: '物', r: 'もの', rom: 'mono', m: 'coisa; objeto' },
  { w: '六日', r: 'むいか', rom: 'muika', m: 'dia 6 (do mês); seis dias' },
  { w: '向こう', r: 'むこう', rom: 'mukou', m: 'lá; ali; o outro lado' },
  { w: '村', r: 'むら', rom: 'mura', m: 'aldeia; vila' },
  { w: '六つ', r: 'むっつ', rom: 'muttsu', m: 'seis (objetos)' },
  { w: 'ナイフ', r: 'ナイフ', rom: 'naifu', m: 'faca' },
  { w: '中', r: 'なか', rom: 'naka', m: 'dentro; meio' },
  { w: '名前', r: 'なまえ', rom: 'namae', m: 'nome' },
  { w: '七つ', r: 'ななつ', rom: 'nanatsu', m: 'sete (objetos)' },
  { w: '七日', r: 'なのか', rom: 'nanoka', m: 'dia 7 (do mês); sete dias' },
  { w: '夏', r: 'なつ', rom: 'natsu', m: 'verão' },
  { w: '夏休み', r: 'なつやすみ', rom: 'natsuyasumi', m: 'férias de verão' },
  { w: '猫', r: 'ねこ', rom: 'neko', m: 'gato' },
  { w: 'ネクタイ', r: 'ネクタイ', rom: 'nekutai', m: 'gravata' },
  { w: '二', r: 'に', rom: 'ni', m: 'dois; 2' },
  { w: '日曜日', r: 'にちようび', rom: 'nichiyoubi', m: 'domingo' },
  { w: '日記', r: 'にっき', rom: 'nikki', m: 'diário' },
  { w: '肉', r: 'にく', rom: 'niku', m: 'carne' },
  { w: '荷物', r: 'にもつ', rom: 'nimotsu', m: 'bagagem' },
  { w: '西', r: 'にし', rom: 'nishi', m: 'oeste' },
  { w: '庭', r: 'にわ', rom: 'niwa', m: 'jardim; quintal' },
  { w: '飲み物', r: 'のみもの', rom: 'nomimono', m: 'bebida' },
  { w: 'ノート', r: 'ノート', rom: 'nooto', m: 'caderno' },
  { w: 'ニュース', r: 'ニュース', rom: 'nyuusu', m: 'notícias' },
  { w: 'おばあさん', r: 'おばあさん', rom: 'obaasan', m: 'avó; senhora idosa' },
  { w: '伯母さん', r: 'おばさん', rom: 'obasan', m: 'tia; senhora de meia-idade' },
  { w: 'お弁当', r: 'おべんとう', rom: 'obentou', m: 'marmita; almoço em caixa' },
  { w: 'お茶', r: 'おちゃ', rom: 'ocha', m: 'chá' },
  { w: 'お風呂', r: 'おふろ', rom: 'ofuro', m: 'banho; banheira' },
  { w: '伯父さん', r: 'おじさん', rom: 'ojisan', m: 'tio; senhor' },
  { w: 'お母さん', r: 'おかあさん', rom: 'okaasan', m: 'mãe (sua mãe ou de alguém)' },
  { w: 'お金', r: 'おかね', rom: 'okane', m: 'dinheiro' },
  { w: 'お菓子', r: 'おかし', rom: 'okashi', m: 'doce; lanche' },
  { w: '奥さん', r: 'おくさん', rom: 'okusan', m: 'esposa (de outra pessoa)' },
  { w: 'お巡りさん', r: 'おまわりさん', rom: 'omawari san', m: 'policial (informal)' },
  { w: '同じ', r: 'おなじ', rom: 'onaji', m: 'mesmo; igual' },
  { w: 'お腹', r: 'おなか', rom: 'onaka', m: 'barriga; estômago' },
  { w: 'お姉さん', r: 'おねえさん', rom: 'oneesan', m: 'irmã mais velha (sua ou de outra pessoa)' },
  { w: '音楽', r: 'おんがく', rom: 'ongaku', m: 'música' },
  { w: 'お兄さん', r: 'おにいさん', rom: 'oniisan', m: 'irmão mais velho (seu ou de outra pessoa)' },
  { w: '女', r: 'おんな', rom: 'onna', m: 'mulher; fêmea' },
  { w: '女の子', r: 'おんなのこ', rom: 'onnanoko', m: 'menina' },
  { w: '大勢', r: 'おおぜい', rom: 'oozei', m: 'multidão; muitas pessoas' },
  { w: 'お酒', r: 'おさけ', rom: 'osake', m: 'álcool; saquê' },
  { w: 'お皿', r: 'おさら', rom: 'osara', m: 'prato' },
  { w: 'お手洗い', r: 'おてあらい', rom: 'otearai', m: 'banheiro; lavabo' },
  { w: '男', r: 'おとこ', rom: 'otoko', m: 'homem; macho' },
  { w: '男の子', r: 'おとこのこ', rom: 'otokonoko', m: 'menino' },
  { w: '大人', r: 'おとな', rom: 'otona', m: 'adulto' },
  { w: '一昨日', r: 'おととい', rom: 'ototoi', m: 'anteontem' },
  { w: '一昨年', r: 'おととし', rom: 'ototoshi', m: 'ano retrasado' },
  { w: 'お父さん', r: 'おとうさん', rom: 'otousan', m: 'pai (seu ou de outra pessoa)' },
  { w: '弟', r: 'おとうと', rom: 'otouto', m: 'irmão mais novo' },
  { w: 'パーティー', r: 'パーティー', rom: 'paatii', m: 'festa' },
  { w: 'パン', r: 'パン', rom: 'pan', m: 'pão' },
  { w: 'ページ', r: 'ページ', rom: 'peeji', m: 'página' },
  { w: 'ペン', r: 'ペン', rom: 'pen', m: 'caneta' },
  { w: 'ペット', r: 'ペット', rom: 'petto', m: 'animal de estimação' },
  { w: 'ポケット', r: 'ポケット', rom: 'poketto', m: 'bolso' },
  { w: 'ポスト', r: 'ポスト', rom: 'posuto', m: 'caixa de correio' }
];

const examples = {
  '黒': { jp: 'この靴は黒です。', r: 'この くつは くろです。', rom: 'kono kutsu wa kuro desu.', pt: 'Estes sapatos são pretos.' },
  '車': { jp: '新しい車を買いました。', r: 'あたらしい くるまを かいました。', rom: 'atarashii kuruma o kaimashita.', pt: 'Comprei um carro novo.' },
  '薬': { jp: '毎日薬を飲みます。', r: 'まいにち くすりを のみます。', rom: 'mainichi kusuri o nomimasu.', pt: 'Tomo remédio todos os dias.' },
  '靴': { jp: 'デパートで靴を買いました。', r: 'デパートで くつを かいました。', rom: 'depaato de kutsu o kaimashita.', pt: 'Comprei sapatos na loja de departamentos.' },
  '靴下': { jp: '白い靴下を履いています。', r: 'しろい くつしたを はいています。', rom: 'shiroi kutsushita o haiteimasu.', pt: 'Estou usando meias brancas.' },
  '去年': { jp: '去年、日本へ行きました。', r: 'きょねん、にほんへ いきました。', rom: 'kyonen, nihon e ikimashita.', pt: 'Ano passado fui para o Japão.' },
  '今日': { jp: '今日はいい天気ですね。', r: 'きょうは いい てんきですね。', rom: 'kyou wa ii tenki desu ne.', pt: 'Hoje o tempo está bom, né?' },
  '兄弟': { jp: 'あなたには兄弟がいますか。', r: 'あなたには きょうだいが いますか。', rom: 'anata ni wa kyoudai ga imasu ka.', pt: 'Você tem irmãos?' },
  '教室': { jp: '教室で勉強します。', r: 'きょうしつで べんきょうします。', rom: 'kyoushitsu de benkyoushimasu.', pt: 'Eu estudo na sala de aula.' },
  '九': { jp: 'ペンが九本あります。', r: 'ペンが きゅうほん あります。', rom: 'pen ga kyuuhon arimasu.', pt: 'Há nove canetas.' },
  'マッチ': { jp: 'マッチで火をつけます。', r: 'マッチで ひを つけます。', rom: 'macchi de hi o tsukemasu.', pt: 'Acendo o fogo com um fósforo.' },
  '町': { jp: 'この町は静かです。', r: 'この まちは しずかです。', rom: 'kono machi wa shizuka desu.', pt: 'Esta cidade é tranquila.' },
  '窓': { jp: '窓を開けてください。', r: 'まどを あけてください。', rom: 'mado o akete kudasai.', pt: 'Abra a janela, por favor.' },
  '前': { jp: '駅の前にいます。', r: 'えきの まえに います。', rom: 'eki no mae ni imasu.', pt: 'Estou na frente da estação.' },
  '毎朝': { jp: '毎朝コーヒーを飲みます。', r: 'まいあさ コーヒーを のみます。', rom: 'maiasa koohii o nomimasu.', pt: 'Toda manhã eu bebo café.' },
  '毎晩': { jp: '毎晩テレビを見ます。', r: 'まいばん テレビを みます。', rom: 'maiban terebi o mimasu.', pt: 'Toda noite eu assisto TV.' },
  '毎日': { jp: '毎日日本語を勉強します。', r: 'まいにち にほんごを べんきょうします。', rom: 'mainichi nihongo o benkyoushimasu.', pt: 'Todo dia eu estudo japonês.' },
  '毎週': { jp: '毎週日曜日にテニスをします。', r: 'まいしゅう にちようびに テニスを します。', rom: 'maishuu nichiyoubi ni tenisu o shimasu.', pt: 'Toda semana eu jogo tênis no domingo.' },
  '毎年': { jp: '毎年ハワイに行きます。', r: 'まいとし ハワイに いきます。', rom: 'maitoshi hawai ni ikimasu.', pt: 'Todo ano eu vou para o Havaí.' },
  '毎月': { jp: '毎月本を三冊読みます。', r: 'まいつき ほんを さんさつ よみます。', rom: 'maitsuki hon o sansatsu yomimasu.', pt: 'Todo mês eu leio três livros.' },
  '万': { jp: '一万円かかりました。', r: 'いちまんえん かかりました。', rom: 'ichimanen kakarimashita.', pt: 'Custou dez mil ienes.' },
  '万年筆': { jp: '父から万年筆をもらいました。', r: 'ちちから まんねんひつを もらいました。', rom: 'chichi kara mannenhitsu o moraimashita.', pt: 'Recebi uma caneta-tinteiro do meu pai.' },
  '真っ直ぐ': { jp: 'この道を真っ直ぐ行ってください。', r: 'この みちを まっすぐ いってください。', rom: 'kono michi o massugu itte kudasai.', pt: 'Vá direto nesta rua, por favor.' },
  '目': { jp: '彼女は目が大きいです。', r: 'かのじょは めが おおきいです。', rom: 'kanojo wa me ga ookii desu.', pt: 'Ela tem olhos grandes.' },
  'メートル': { jp: '百メートル走りました。', r: 'ひゃくメートル はしりました。', rom: 'hyakumeetoru hashirimashita.', pt: 'Corri cem metros.' },
  '眼鏡': { jp: '眼鏡をかけています。', r: 'めがねを かけています。', rom: 'megane o kaketeimasu.', pt: 'Estou usando óculos.' },
  '道': { jp: '道を教えてください。', r: 'みちを おしえてください。', rom: 'michi o oshiete kudasai.', pt: 'Por favor, me mostre o caminho.' },
  '緑': { jp: '緑のシャツを買いました。', r: 'みどりの シャツを かいました。', rom: 'midori no shatsu o kaimashita.', pt: 'Comprei uma camisa verde.' },
  '右': { jp: '右に曲がってください。', r: 'みぎに まがってください。', rom: 'migi ni magatte kudasai.', pt: 'Vire à direita, por favor.' },
  '三日': { jp: '三日間、雨が降っています。', r: 'みっかかん、あめが ふっています。', rom: 'mikkakan, ame ga futteimasu.', pt: 'Está chovendo por três dias.' },
  '耳': { jp: '耳が痛いです。', r: 'みみが いたいです。', rom: 'mimi ga itai desu.', pt: 'Meu ouvido está doendo.' },
  '南': { jp: '南の島へ行きたいです。', r: 'みなみの しまへ いきたいです。', rom: 'minami no shima e ikitai desu.', pt: 'Quero ir para uma ilha do sul.' },
  '皆さん': { jp: '皆さん、おはようございます。', r: 'みなさん、おはようございます。', rom: 'minasan, ohayou gozaimasu.', pt: 'Bom dia a todos.' },
  'みんな': { jp: 'みんなで歌いましょう。', r: 'みんなで うたいましょう。', rom: 'minna de utaimashou.', pt: 'Vamos cantar todos juntos.' },
  '店': { jp: 'この店は美味しいです。', r: 'この みせは おいしいです。', rom: 'kono mise wa oishii desu.', pt: 'Esta loja (restaurante) é deliciosa.' },
  '三つ': { jp: 'りんごを三つください。', r: 'りんごを みっつください。', rom: 'ringo o mittsu kudasai.', pt: 'Me dê três maçãs, por favor.' },
  '水': { jp: '水を一杯ください。', r: 'みずを いっぱいください。', rom: 'mizu o ippai kudasai.', pt: 'Me dê um copo d\'água, por favor.' },
  '木曜日': { jp: '木曜日は忙しいです。', r: 'もくようびは いそがしいです。', rom: 'mokuyoubi wa isogashii desu.', pt: 'Quinta-feira eu sou ocupado.' },
  '門': { jp: '学校の門の前にいます。', r: 'がっこうの もんの まえに います。', rom: 'gakkou no mon no mae ni imasu.', pt: 'Estou na frente do portão da escola.' },
  '問題': { jp: 'この問題は難しいです。', r: 'この もんだいは むずかしいです。', rom: 'kono mondai wa muzukashii desu.', pt: 'Este problema/questão é difícil.' },
  '物': { jp: 'カバンの中に何という物が入っていますか。', r: 'カバンの なかに なんという ものが はいっていますか。', rom: 'kaban no naka ni nan to iu mono ga haitteimasu ka.', pt: 'Que tipo de coisa tem dentro da bolsa?' },
  '六日': { jp: '来月の六日に出発します。', r: 'らいげつの むいかに しゅっぱつします。', rom: 'raigetsu no muika ni shuppatsushimasu.', pt: 'Partiremos no dia seis do mês que vem.' },
  '向こう': { jp: '向こうに山が見えます。', r: 'むこうに やまが みえます。', rom: 'mukou ni yama ga miemasu.', pt: 'Dá para ver a montanha lá longe.' },
  '村': { jp: '私の村は自然が豊かです。', r: 'わたしの むらは しぜんが ゆたかです。', rom: 'watashi no mura wa shizen ga yutaka desu.', pt: 'Minha aldeia tem natureza abundante.' },
  '六つ': { jp: '卵が六つあります。', r: 'たまごが むっつ あります。', rom: 'tamago ga muttsu arimasu.', pt: 'Há seis ovos.' },
  'ナイフ': { jp: 'ナイフでパンを切ります。', r: 'ナイフで パンを きります。', rom: 'naifu de pan o kirimasu.', pt: 'Corto o pão com uma faca.' },
  '中': { jp: '箱の中に何がありますか。', r: 'はこの なかに なにが ありますか。', rom: 'hako no naka ni nani ga arimasu ka.', pt: 'O que tem dentro da caixa?' },
  '名前': { jp: 'あなたの名前は何ですか。', r: 'あなたの なまえは なんですか。', rom: 'anata no namae wa nan desu ka.', pt: 'Qual é o seu nome?' },
  '七つ': { jp: 'みかんを七つ買いました。', r: 'みかんを ななつ かいました。', rom: 'mikan o nanatsu kaimashita.', pt: 'Comprei sete tangerinas.' },
  '七日': { jp: '五月七日は私の誕生日です。', r: 'ごがつ なのかは わたしの たんじょうびです。', rom: 'gogatsu nanoka wa watashi no tanjoubi desu.', pt: 'Sete de maio é meu aniversário.' },
  '夏': { jp: '夏は海に行きます。', r: 'なつは うみに いきます。', rom: 'natsu wa umi ni ikimasu.', pt: 'No verão eu vou para a praia.' },
  '夏休み': { jp: '夏休みに旅行へ行きます。', r: 'なつやすみに りょこうへ いきます。', rom: 'natsuyasumi ni ryokou e ikimasu.', pt: 'Vou viajar nas férias de verão.' },
  '猫': { jp: '白い猫を飼っています。', r: 'しろい ねこを かっています。', rom: 'shiroi neko o katteimasu.', pt: 'Crio um gato branco.' },
  'ネクタイ': { jp: 'ネクタイを締めます。', r: 'ネクタイを しめます。', rom: 'nekutai o shimemasu.', pt: 'Apertar a gravata (dar o nó).' },
  '二': { jp: 'ここに二つのりんごがあります。', r: 'ここに ふたつの りんごが あります。', rom: 'koko ni futatsu no ringo ga arimasu.', pt: 'Há duas maçãs aqui.' },
  '日曜日': { jp: '日曜日は映画を見ます。', r: 'にちようびは えいがを みます。', rom: 'nichiyoubi wa eiga o mimasu.', pt: 'No domingo eu assisto filmes.' },
  '日記': { jp: '毎日日記を書いています。', r: 'まいにち にっきを かいています。', rom: 'mainichi nikki o kaiteimasu.', pt: 'Escrevo um diário todos os dias.' },
  '肉': { jp: '肉を食べたいです。', r: 'にくを たべたいです。', rom: 'niku o tabetai desu.', pt: 'Quero comer carne.' },
  '荷物': { jp: '荷物が多いです。', r: 'にもつが おおいです。', rom: 'nimotsu ga ooi desu.', pt: 'Tenho muita bagagem.' },
  '西': { jp: '太陽は西に沈みます。', r: 'たいようは にしに しずみます。', rom: 'taiyou wa nishi ni shizumimasu.', pt: 'O sol se põe no oeste.' },
  '庭': { jp: '庭に花を植えました。', r: 'にわに はなを うえました。', rom: 'niwa ni hana o uemashita.', pt: 'Plantei flores no jardim.' },
  '飲み物': { jp: '冷たい飲み物が欲しいです。', r: 'つめたい のみものが ほしいです。', rom: 'tsumetai nomimono ga hoshii desu.', pt: 'Quero uma bebida gelada.' },
  'ノート': { jp: 'ノートにメモを書きます。', r: 'ノートに メモを かきます。', rom: 'nooto ni memo o kakimasu.', pt: 'Escrevo anotações no caderno.' },
  'ニュース': { jp: 'テレビでニュースを見ます。', r: 'テレビで ニュースを みます。', rom: 'terebi de nyuusu o mimasu.', pt: 'Vejo as notícias na televisão.' },
  'おばあさん': { jp: '私のおばあさんは元気です。', r: 'わたしの おばあさんは げんきです。', rom: 'watashi no obaasan wa genki desu.', pt: 'Minha avó está saudável.' },
  '伯母さん': { jp: 'おばさんにプレゼントをあげました。', r: 'おばさんに プレゼントを あげました。', rom: 'obasan ni purezento o agemashita.', pt: 'Dei um presente para minha tia.' },
  'お弁当': { jp: 'お弁当を作りました。', r: 'おべんとうを つくりました。', rom: 'obentou o tsukurimashita.', pt: 'Fiz a marmita.' },
  'お茶': { jp: 'お茶を飲みましょう。', r: 'おちゃを のみましょう。', rom: 'ocha o nomimashou.', pt: 'Vamos tomar chá.' },
  'お風呂': { jp: '夜にお風呂に入ります。', r: 'よるに おふろに はいります。', rom: 'yoru ni ofuro ni hairimasu.', pt: 'Tomo banho à noite.' },
  '伯父さん': { jp: 'おじさんは会社員です。', r: 'おじさんは かいしゃいんです。', rom: 'ojisan wa kaishain desu.', pt: 'Meu tio é funcionário de empresa.' },
  'お母さん': { jp: 'お母さん、ありがとう。', r: 'おかあさん、ありがとう。', rom: 'okaasan, arigatou.', pt: 'Mãe, obrigado(a).' },
  'お金': { jp: 'お金がありません。', r: 'おかねが ありません。', rom: 'okane ga arimasen.', pt: 'Não tenho dinheiro.' },
  'お菓子': { jp: '子供にお菓子を買いました。', r: 'こどもに おかしを かいました。', rom: 'kodomo ni okashi o kaimashita.', pt: 'Comprei doces para a criança.' },
  '奥さん': { jp: '奥さんはお元気ですか。', r: 'おくさんは おげんきですか。', rom: 'okusan wa ogenki desu ka.', pt: 'Como está sua esposa?' },
  'お巡りさん': { jp: 'お巡りさんに道を尋ねました。', r: 'おまわりさんに みちを たずねました。', rom: 'omawarisan ni michi o tazunemashita.', pt: 'Perguntei o caminho ao policial.' },
  '同じ': { jp: '私たちは同じ学校です。', r: 'わたしたちは おなじ がっこうです。', rom: 'watashitachi wa onaji gakkou desu.', pt: 'Nós somos da mesma escola.' },
  'お腹': { jp: 'お腹が空きました。', r: 'おなかが すきました。', rom: 'onaka ga sukimashita.', pt: 'Estou com fome.' },
  'お姉さん': { jp: 'お姉さんは綺麗ですね。', r: 'おねえさんは きれいですね。', rom: 'oneesan wa kirei desu ne.', pt: 'Sua irmã mais velha é bonita, né.' },
  '音楽': { jp: '音楽を聴くのが好きです。', r: 'おんがくを きくのが すきです。', rom: 'ongaku o kiku no ga suki desu.', pt: 'Gosto de ouvir música.' },
  'お兄さん': { jp: 'お兄さんは背が高いです。', r: 'おにいさんは せが たかいです。', rom: 'oniisan wa se ga takai desu.', pt: 'O irmão mais velho dele(a) é alto.' },
  '女': { jp: 'あの女の人は誰ですか。', r: 'あの おんなの ひと は だれですか。', rom: 'ano onna no hito wa dare desu ka.', pt: 'Quem é aquela mulher?' },
  '女の子': { jp: '可愛い女の子がいます。', r: 'かわいい おんなのこが います。', rom: 'kawaii onnanoko ga imasu.', pt: 'Tem uma menina bonita/fofa.' },
  '大勢': { jp: '公園に大勢の人がいます。', r: 'こうえんに おおぜいの ひとが います。', rom: 'kouen ni oozei no hito ga imasu.', pt: 'Há muita gente no parque.' },
  'お酒': { jp: 'お酒を飲みすぎないでください。', r: 'おさけを のみすぎないでください。', rom: 'osake o nomisuginaide kudasai.', pt: 'Não beba muito álcool, por favor.' },
  'お皿': { jp: 'お皿を洗います。', r: 'おさらを あらいます。', rom: 'osara o araimasu.', pt: 'Lavo os pratos.' },
  'お手洗い': { jp: 'お手洗いはどこですか。', r: 'おてあらいは どこですか。', rom: 'otearai wa doko desu ka.', pt: 'Onde fica o banheiro?' },
  '男': { jp: '彼はいい男です。', r: 'かれは いい おとこです。', rom: 'kare wa ii otoko desu.', pt: 'Ele é um bom homem.' },
  '男の子': { jp: '男の子が走っています。', r: 'おとこのこが はしっています。', rom: 'otokonoko ga hashitteimasu.', pt: 'Um menino está correndo.' },
  '大人': { jp: '大人の料金は千円です。', r: 'おとなの りょうきんは せんえんです。', rom: 'otona no ryoukin wa senen desu.', pt: 'A tarifa de adulto é mil ienes.' },
  '一昨日': { jp: '一昨日、映画を見に行きました。', r: 'おととい、えいがを みに いきました。', rom: 'ototoi, eiga o mini ikimashita.', pt: 'Anteontem eu fui ver um filme.' },
  '一昨年': { jp: '一昨年、日本に旅行しました。', r: 'おととし、にほんに りょこうしました。', rom: 'ototoshi, nihon ni ryokoushimashita.', pt: 'Ano retrasado, eu viajei para o Japão.' },
  'お父さん': { jp: 'お父さんの仕事は何ですか。', r: 'おとうさんの しごとは なんですか。', rom: 'otousan no shigoto wa nan desu ka.', pt: 'Qual é o trabalho do seu pai?' },
  '弟': { jp: '弟はゲームが好きです。', r: 'おとうとは ゲームが すきです。', rom: 'otouto wa geemu ga suki desu.', pt: 'Meu irmão mais novo gosta de videogame.' },
  'パーティー': { jp: '明日、パーティーをします。', r: 'あした、パーティーを します。', rom: 'ashita, paatii o shimasu.', pt: 'Amanhã vou dar uma festa.' },
  'パン': { jp: '朝ご飯にパンを食べます。', r: 'あさごはんに パンを たべます。', rom: 'asagohan ni pan o tabemasu.', pt: 'No café da manhã eu como pão.' },
  'ページ': { jp: '次のページを開いてください。', r: 'つぎの ページを ひらいてください。', rom: 'tsugi no peeji o hiraite kudasai.', pt: 'Abra na próxima página, por favor.' },
  'ペン': { jp: '黒いペンを貸してください。', r: 'くろい ペンを かしてください。', rom: 'kuroi pen o kashite kudasai.', pt: 'Me empreste uma caneta preta, por favor.' },
  'ペット': { jp: '何かペットを飼っていますか。', r: 'なにか ペットを かっていますか。', rom: 'nanika petto o katteimasu ka.', pt: 'Você tem algum animal de estimação?' },
  'ポケット': { jp: 'ポケットに鍵を入れました。', r: 'ポケットに かぎを いれました。', rom: 'poketto ni kagi o iremashita.', pt: 'Coloquei a chave no bolso.' },
  'ポスト': { jp: '手紙をポストに入れました。', r: 'てがみを ポストに いれました。', rom: 'tegami o posuto ni iremashita.', pt: 'Coloquei a carta na caixa de correio.' }
};

const filePath = path.join(process.cwd(), 'src/data/vocabN5.ts');
let fileContent = fs.readFileSync(filePath, 'utf8');

const newObjects = nouns.map((n, i) => {
  const ex = examples[n.w] || {
    jp: "Exemplo",
    reading: "...",
    rom: "...",
    pt: "..."
  };

  return "  {\n" +
    "    id: 'n5_noun_batch3_" + Date.now() + "_" + i + "',\n" +
    "    word: '" + n.w + "',\n" +
    "    reading: '" + n.r + "',\n" +
    "    romaji: '" + n.rom + "',\n" +
    "    meaningPt: '" + n.m + "',\n" +
    "    category: 'substantivo',\n" +
    "    jlpt: 'N5',\n" +
    "    categoryLabelPt: 'Substantivo N5',\n" +
    "    exampleSentence: {\n" +
    "      jp: '" + ex.jp + "',\n" +
    "      reading: '" + ex.r + "',\n" +
    "      romaji: '" + ex.rom + "',\n" +
    "      meaningPt: '" + ex.pt + "'\n" +
    "    }\n" +
    "  }";
}).join(',\n');

fileContent = fileContent.replace(
  /export const VOCAB_N5: VocabItem\[\] = \[/,
  "export const VOCAB_N5: VocabItem[] = [\n" + newObjects + ",\n"
);

fs.writeFileSync(filePath, fileContent, 'utf8');
console.log('Added 100 more N5 Nouns to vocabN5.ts successfully!');
