import fs from 'fs';
import path from 'path';

const items = [
  { w: '上がる', r: 'あがる', rom: 'agaru', m: 'subir; elevar-se', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '挨拶する', r: 'あいさつする', rom: 'aisatsusuru', m: 'cumprimentar', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '案内する', r: 'あんないする', rom: 'annaisuru', m: 'guiar; orientar', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '安心する', r: 'あんしんする', rom: 'anshinsuru', m: 'tranquilizar-se; sentir-se aliviado', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: 'アルバイトする', r: 'アルバイトする', rom: 'arubaitosuru', m: 'fazer trabalho de meio período', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '集まる', r: 'あつまる', rom: 'atsumaru', m: 'reunir-se; juntar-se (intransitivo)', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '集める', r: 'あつめる', rom: 'atsumeru', m: 'coletar; reunir; juntar', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '謝る', r: 'あやまる', rom: 'ayamaru', m: 'pedir desculpas', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '貿易する', r: 'ぼうえきする', rom: 'bouekisuru', m: 'fazer comércio exterior', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: 'チェックする', r: 'チェックする', rom: 'chekkusuru', m: 'verificar; checar', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '注意する', r: 'ちゅういする', rom: 'chuuisuru', m: 'tomar cuidado; prestar atenção', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '注射する', r: 'ちゅうしゃする', rom: 'chuushasuru', m: 'tomar injeção; aplicar injeção', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '暖房する', r: 'だんぼうする', rom: 'danbousuru', m: 'aquecer (ambiente)', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '遠慮する', r: 'えんりょする', rom: 'enryosuru', m: 'hesitar; abster-se', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '選ぶ', r: 'えらぶ', rom: 'erabu', m: 'escolher', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: 'ファックスする', r: 'ファックスする', rom: 'fakkususuru', m: 'enviar fax', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '増える', r: 'ふえる', rom: 'fueru', m: 'aumentar (intransitivo)', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '復習する', r: 'ふくしゅうする', rom: 'fukushuusuru', m: 'revisar (matéria de estudo)', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '踏む', r: 'ふむ', rom: 'fumu', m: 'pisar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '降り出す', r: 'ふりだす', rom: 'furidasu', m: 'começar a chover/nevar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '太る', r: 'ふとる', rom: 'futoru', m: 'engordar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '原因', r: 'げんいん', rom: 'genin', m: 'causa; origem', cat: 'substantivo', catLabel: 'Substantivo N4' },
  { w: '下宿する', r: 'げしゅくする', rom: 'geshukusuru', m: 'hospedar-se (pensão/alojamento)', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: 'ごちそうする', r: 'ごちそうする', rom: 'gochisousuru', m: 'oferecer um banquete; pagar a conta', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: 'ご覧になる', r: 'ごらんになる', rom: 'goran ni naru', m: 'ver (forma polida)', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '拝見する', r: 'はいけんする', rom: 'haikensuru', m: 'ver (forma humilde)', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '運ぶ', r: 'はこぶ', rom: 'hakobu', m: 'transportar; carregar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '花見する', r: 'はなみする', rom: 'hanamisuru', m: 'apreciar as flores (cerejeiras)', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '反対する', r: 'はんたいする', rom: 'hantaisuru', m: 'opor-se', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '払う', r: 'はらう', rom: 'harau', m: 'pagar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '発音する', r: 'はつおんする', rom: 'hatsuonsuru', m: 'pronunciar', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '返事する', r: 'へんじする', rom: 'henjisuru', m: 'responder', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '冷える', r: 'ひえる', rom: 'hieru', m: 'esfriar; gelar', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '光る', r: 'ひかる', rom: 'hikaru', m: 'brilhar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '引き出す', r: 'ひきだす', rom: 'hikidasu', m: 'retirar (dinheiro); sacar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '引っ越す', r: 'ひっこす', rom: 'hikkosu', m: 'mudar de casa', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '開く', r: 'ひらく', rom: 'hiraku', m: 'abrir; inaugurar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '拾う', r: 'ひろう', rom: 'hirou', m: 'pegar (algo do chão); recolher', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '褒める', r: 'ほめる', rom: 'homeru', m: 'elogiar; louvar', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '翻訳する', r: 'ほんやくする', rom: 'honyakusuru', m: 'traduzir', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '放送する', r: 'ほうそうする', rom: 'housousuru', m: 'transmitir (TV/rádio)', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: 'いじめる', r: 'いじめる', rom: 'ijimeru', m: 'intimidar; maltratar', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '意見する', r: 'いけんする', rom: 'ikensuru', m: 'dar opinião; comentar', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '生きる', r: 'いきる', rom: 'ikiru', m: 'viver', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '祈る', r: 'いのる', rom: 'inoru', m: 'rezar; orar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '急ぐ', r: 'いそぐ', rom: 'isogu', m: 'apressar-se; ter pressa', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '頂く', r: 'いただく', rom: 'itadaku', m: 'receber (forma humilde); comer/beber', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '致す', r: 'いたす', rom: 'itasu', m: 'fazer (forma humilde)', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '準備する', r: 'じゅんびする', rom: 'junbisuru', m: 'preparar', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '変える', r: 'かえる', rom: 'kaeru', m: 'mudar; alterar', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '会議する', r: 'かいぎする', rom: 'kaigisuru', m: 'fazer reunião', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '会話する', r: 'かいわする', rom: 'kaiwasuru', m: 'conversar', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '構う', r: 'かまう', rom: 'kamau', m: 'importar-se; ligar para', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '噛む', r: 'かむ', rom: 'kamu', m: 'morder; mastigar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '考える', r: 'かんがえる', rom: 'kangaeru', m: 'pensar; considerar', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '関係する', r: 'かんけいする', rom: 'kankeisuru', m: 'ter relação; relacionar-se', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '片付ける', r: 'かたづける', rom: 'katadzukeru', m: 'arrumar; organizar', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '勝つ', r: 'かつ', rom: 'katsu', m: 'ganhar; vencer', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '乾く', r: 'かわく', rom: 'kawaku', m: 'secar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '変わる', r: 'かわる', rom: 'kawaru', m: 'mudar (intransitivo)', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '通う', r: 'かよう', rom: 'kayou', m: 'frequentar; ir e vir', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '飾る', r: 'かざる', rom: 'kazaru', m: 'decorar; enfeitar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '怪我する', r: 'けがする', rom: 'kegasuru', m: 'machucar-se', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '計画する', r: 'けいかくする', rom: 'keikakusuru', m: 'planejar', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '経験する', r: 'けいけんする', rom: 'keikensuru', m: 'experienciar; passar por', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '見物する', r: 'けんぶつする', rom: 'kenbutsusuru', m: 'passear; ver os pontos turísticos', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '喧嘩する', r: 'けんかする', rom: 'kenkasuru', m: 'brigar; discutir', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '研究する', r: 'けんきゅうする', rom: 'kenkyuusuru', m: 'pesquisar; estudar a fundo', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '聞こえる', r: 'きこえる', rom: 'kikoeru', m: 'ser audível; ouvir-se', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '決まる', r: 'きまる', rom: 'kimaru', m: 'ser decidido', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '決める', r: 'きめる', rom: 'kimeru', m: 'decidir', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '込む', r: 'こむ', rom: 'komu', m: 'estar lotado/cheio', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '故障する', r: 'こしょうする', rom: 'koshousuru', m: 'quebrar (falha mecânica)', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '講義する', r: 'こうぎする', rom: 'kougisuru', m: 'dar palestra/aula', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '壊れる', r: 'こわれる', rom: 'kowareru', m: 'quebrar (intransitivo)', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '壊す', r: 'こわす', rom: 'kowasu', m: 'quebrar; destruir', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '下さる', r: 'くださる', rom: 'kudasaru', m: 'dar (forma polida)', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '比べる', r: 'くらべる', rom: 'kuraberu', m: 'comparar', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '暮れる', r: 'くれる', rom: 'kureru', m: 'escurecer; anoitecer', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '教育する', r: 'きょういくする', rom: 'kyouikusuru', m: 'educar', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '競争する', r: 'きょうそうする', rom: 'kyousousuru', m: 'competir', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '急行する', r: 'きゅうこうする', rom: 'kyuukousuru', m: 'apressar-se para ir; ir expresso', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '間違える', r: 'まちがえる', rom: 'machigaeru', m: 'errar; enganar-se', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '参る', r: 'まいる', rom: 'mairu', m: 'ir; vir (forma humilde)', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '負ける', r: 'まける', rom: 'makeru', m: 'perder (ser derrotado)', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '間に合う', r: 'まにあう', rom: 'maniau', m: 'chegar a tempo; servir', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '回る', r: 'まわる', rom: 'mawaru', m: 'girar; circular', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '召し上がる', r: 'めしあがる', rom: 'meshiagaru', m: 'comer; beber (forma polida)', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '見える', r: 'みえる', rom: 'mieru', m: 'poder ver; estar visível', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '見つかる', r: 'みつかる', rom: 'mitsukaru', m: 'ser encontrado', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '見つける', r: 'みつける', rom: 'mitsukeru', m: 'encontrar; descobrir', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '戻る', r: 'もどる', rom: 'modoru', m: 'voltar; retornar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '申し上げる', r: 'もうしあげる', rom: 'moushiageru', m: 'dizer (forma humilde)', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '申す', r: 'もうす', rom: 'mousu', m: 'chamar-se; dizer (forma humilde)', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '迎える', r: 'むかえる', rom: 'mukaeru', m: 'receber; ir buscar', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '向かう', r: 'むかう', rom: 'mukau', m: 'ir em direção a', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '無理する', r: 'むりする', rom: 'murisuru', m: 'esforçar-se demais; forçar', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '投げる', r: 'なげる', rom: 'nageru', m: 'jogar; arremessar', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '泣く', r: 'なく', rom: 'naku', m: 'chorar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '無くなる', r: 'なくなる', rom: 'naku naru', m: 'desaparecer; acabar; perder-se', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' }
];

const examples = {
  '上がる': { jp: '気温が上がります。', r: 'きおんが あがります。', rom: 'kion ga agarimasu.', pt: 'A temperatura sobe.' },
  '挨拶する': { jp: '近所の人に挨拶します。', r: 'きんじょの ひとに あいさつします。', rom: 'kinjo no hito ni aisatsushimasu.', pt: 'Cumprimento as pessoas da vizinhança.' },
  '案内する': { jp: '町を案内します。', r: 'まちを あんないします。', rom: 'machi o annaishimasu.', pt: 'Vou guiar pela cidade.' },
  '安心する': { jp: '彼の顔を見て安心しました。', r: 'かれの かおを みて あんしんしました。', rom: 'kare no kao o mite anshinshimashita.', pt: 'Fiquei aliviado ao ver o rosto dele.' },
  'アルバイトする': { jp: 'コンビニでアルバイトします。', r: 'コンビニで アルバイトします。', rom: 'konbini de arubaitoshimasu.', pt: 'Trabalho de meio período na loja de conveniência.' },
  '集まる': { jp: '広場に人が集まります。', r: 'ひろばに ひとが あつまります。', rom: 'hiroba ni hito ga atsumarimasu.', pt: 'As pessoas se reúnem na praça.' },
  '集める': { jp: '切手を集めています。', r: 'きってを あつめています。', rom: 'kitte o atsumeteimasu.', pt: 'Estou colecionando selos.' },
  '謝る': { jp: '彼に謝りました。', r: 'かれに あやまりました。', rom: 'kare ni ayamarimashita.', pt: 'Pedi desculpas a ele.' },
  '貿易する': { jp: '外国と貿易します。', r: 'がいこくと ぼうえきします。', rom: 'gaikoku to bouekishimasu.', pt: 'Fazemos comércio com países estrangeiros.' },
  'チェックする': { jp: '書類をチェックします。', r: 'しょるいを チェックします。', rom: 'shorui o chekkushimasu.', pt: 'Vou checar os documentos.' },
  '注意する': { jp: '車に注意してください。', r: 'くるまに ちゅういしてください。', rom: 'kuruma ni chuuishite kudasai.', pt: 'Por favor, tome cuidado com os carros.' },
  '注射する': { jp: '病院で注射しました。', r: 'びょういんで ちゅうしゃしました。', rom: 'byouin de chuushashimashita.', pt: 'Tomei uma injeção no hospital.' },
  '暖房する': { jp: '部屋を暖房します。', r: 'へやを だんぼうします。', rom: 'heya o danboushimasu.', pt: 'Vou aquecer o quarto.' },
  '遠慮する': { jp: '遠慮しないでください。', r: 'えんりょしないでください。', rom: 'enryo shinaide kudasai.', pt: 'Por favor, não hesite (sinta-se à vontade).' },
  '選ぶ': { jp: '好きな服を選びます。', r: 'すきな ふくを えらびます。', rom: 'suki na fuku o erabimasu.', pt: 'Escolho a roupa que eu gosto.' },
  'ファックスする': { jp: '書類をファックスします。', r: 'しょるいを ファックスします。', rom: 'shorui o fakkusushimasu.', pt: 'Vou enviar os documentos por fax.' },
  '増える': { jp: '人口が増えます。', r: 'じんこうが ふえます。', rom: 'jinkou ga fuemasu.', pt: 'A população aumenta.' },
  '復習する': { jp: '漢字を復習します。', r: 'かんじを ふくしゅうします。', rom: 'kanji o fukushuushimasu.', pt: 'Reviso os kanjis.' },
  '踏む': { jp: '足を踏まれました。', r: 'あしを ふまれました。', rom: 'ashi o fumaremashita.', pt: 'Pisaram no meu pé.' },
  '降り出す': { jp: '雨が降り出しました。', r: 'あめが ふりだしました。', rom: 'ame ga furidashimashita.', pt: 'Começou a chover.' },
  '太る': { jp: '最近、少し太りました。', r: 'さいきん、すこし ふとりました。', rom: 'saikin, sukoshi futorimashita.', pt: 'Recentemente, engordei um pouco.' },
  '原因': { jp: '事故の原因を調べます。', r: 'じこの げんいんを しらべます。', rom: 'jiko no genin o shirabemasu.', pt: 'Vou investigar a causa do acidente.' },
  '下宿する': { jp: '大学の近くに下宿します。', r: 'だいがくの ちかくに げしゅくします。', rom: 'daigaku no chikaku ni geshukushimasu.', pt: 'Vou hospedar-me perto da universidade.' },
  'ごちそうする': { jp: '今日は私がごちそうします。', r: 'きょうは わたしが ごちそうします。', rom: 'kyou wa watashi ga gochisoushimasu.', pt: 'Hoje eu pago (ofereço) a comida.' },
  'ご覧になる': { jp: '先生が写真をご覧になりました。', r: 'せんせいが しゃしんを ごらんになりました。', rom: 'sensei ga shashin o goran ni narimashita.', pt: 'O professor viu a foto.' },
  '拝見する': { jp: 'その手紙を拝見しました。', r: 'その てがみを はいけんしました。', rom: 'sono tegami o haikenshimashita.', pt: 'Eu vi aquela carta (forma humilde).' },
  '運ぶ': { jp: '荷物を部屋に運びます。', r: 'にもつを へやに はこびます。', rom: 'nimotsu o heya ni hakobimasu.', pt: 'Carrego a bagagem para o quarto.' },
  '花見する': { jp: '公園で花見をします。', r: 'こうえんで はなみを します。', rom: 'kouen de hanami o shimasu.', pt: 'Faço a apreciação das flores no parque.' },
  '反対する': { jp: 'その計画に反対します。', r: 'その けいかくに はんたいします。', rom: 'sono keikaku ni hantaishimasu.', pt: 'Oponho-me a esse plano.' },
  '払う': { jp: 'お金を払います。', r: 'おかねを はらいます。', rom: 'okane o haraimasu.', pt: 'Pago o dinheiro.' },
  '発音する': { jp: '正しく発音します。', r: 'ただしく はつおんします。', rom: 'tadashiku hatsuonshimasu.', pt: 'Pronuncio corretamente.' },
  '返事する': { jp: 'すぐに返事します。', r: 'すぐに へんじします。', rom: 'sugu ni henjishimasu.', pt: 'Responderei imediatamente.' },
  '冷える': { jp: 'ビールが冷えています。', r: 'ビールが ひえています。', rom: 'biiru ga hieteimasu.', pt: 'A cerveja está gelada.' },
  '光る': { jp: '星が光っています。', r: 'ほしが ひかっています。', rom: 'hoshi ga hikatteimasu.', pt: 'As estrelas estão brilhando.' },
  '引き出す': { jp: '銀行でお金を引き出します。', r: 'ぎんこうで おかねを ひきだします。', rom: 'ginkou de okane o hikidashimasu.', pt: 'Saco dinheiro no banco.' },
  '引っ越す': { jp: '新しい家に引っ越します。', r: 'あたらしい いえに ひっこします。', rom: 'atarashii ie ni hikkoshimasu.', pt: 'Mudo-me para uma casa nova.' },
  '開く': { jp: 'パーティーを開きます。', r: 'パーティーを ひらきます。', rom: 'paatii o hirakimasu.', pt: 'Dou (inauguro/realizo) uma festa.' },
  '拾う': { jp: '道で財布を拾いました。', r: 'みちで さいふを ひろいました。', rom: 'michi de saifu o hiroimashita.', pt: 'Peguei uma carteira na rua.' },
  '褒める': { jp: '先生が学生を褒めました。', r: 'せんせいが がくせいを ほめました。', rom: 'sensei ga gakusei o homemashita.', pt: 'O professor elogiou o aluno.' },
  '翻訳する': { jp: '本を日本語に翻訳します。', r: 'ほんを にほんごに ほんやくします。', rom: 'hon o nihongo ni honyakushimasu.', pt: 'Traduzo o livro para japonês.' },
  '放送する': { jp: 'ニュースを放送します。', r: 'ニュースを ほうそうします。', rom: 'nyuusu o housoushimasu.', pt: 'Transmite-se as notícias.' },
  'いじめる': { jp: '動物をいじめてはいけません。', r: 'どうぶつを いじめては いけません。', rom: 'doubutsu o ijimetewa ikemasen.', pt: 'Não se deve maltratar os animais.' },
  '意見する': { jp: '会議で意見を言います。', r: 'かいぎで いけんを いいます。', rom: 'kaigi de iken o iimasu.', pt: 'Dou a minha opinião na reunião.' },
  '生きる': { jp: '長く生きたいです。', r: 'ながく いきたいです。', rom: 'nagaku ikitai desu.', pt: 'Quero viver por muito tempo.' },
  '祈る': { jp: '平和を祈ります。', r: 'へいわを いのります。', rom: 'heiwa o inorimasu.', pt: 'Rezo pela paz.' },
  '急ぐ': { jp: '急いで学校へ行きます。', r: 'いそいで がっこうへ いきます。', rom: 'isoide gakkou e ikimasu.', pt: 'Vou apressado para a escola.' },
  '頂く': { jp: 'お土産を頂きました。', r: 'おみやげを いただきました。', rom: 'omiyage o itadakimashita.', pt: 'Recebi uma lembrancinha (forma humilde).' },
  '致す': { jp: '私がご案内致します。', r: 'わたしが ごあんない いたします。', rom: 'watashi ga goannai itashimasu.', pt: 'Eu lhe guiarei (forma humilde).' },
  '準備する': { jp: '旅行の準備をします。', r: 'りょこうの じゅんびを します。', rom: 'ryokou no junbi o shimasu.', pt: 'Vou preparar a viagem.' },
  '変える': { jp: '予定を変えます。', r: 'よていを かえます。', rom: 'yotei o kaemasu.', pt: 'Vou mudar os planos.' },
  '会議する': { jp: '明日、会議します。', r: 'あした、かいぎします。', rom: 'ashita, kaigishimasu.', pt: 'Amanhã faremos uma reunião.' },
  '会話する': { jp: '日本語で会話します。', r: 'にほんごで かいわします。', rom: 'nihongo de kaiwashimasu.', pt: 'Converto em japonês.' },
  '構う': { jp: 'お構いなく。', r: 'おかまいなく。', rom: 'okamai naku.', pt: 'Não se preocupe (comigo).' },
  '噛む': { jp: 'よく噛んで食べてください。', r: 'よく かんで たべてください。', rom: 'yoku kande tabete kudasai.', pt: 'Por favor, mastigue bem antes de comer.' },
  '考える': { jp: '将来について考えます。', r: 'しょうらいについて かんがえます。', rom: 'shourai ni tsuite kangaemasu.', pt: 'Penso sobre o futuro.' },
  '関係する': { jp: 'この仕事に関係しています。', r: 'この しごとに かんけいしています。', rom: 'kono shigoto ni kankeishiteimasu.', pt: 'Estou relacionado a este trabalho.' },
  '片付ける': { jp: '部屋を片付けます。', r: 'へやを かたづけます。', rom: 'heya o katadukemasu.', pt: 'Arrumo o quarto.' },
  '勝つ': { jp: '試合に勝ちました。', r: 'しあいに かちました。', rom: 'shiai ni kachimashita.', pt: 'Ganhei o jogo.' },
  '乾く': { jp: 'シャツが乾きました。', r: 'シャツが かわきました。', rom: 'shatsu ga kawakimashita.', pt: 'A camisa secou.' },
  '変わる': { jp: '予定が変わりました。', r: 'よていが かわりました。', rom: 'yotei ga kawarimashita.', pt: 'Os planos mudaram.' },
  '通う': { jp: '毎日、学校に通います。', r: 'まいにち、がっこうに かよいます。', rom: 'mainichi, gakkou ni kayoimasu.', pt: 'Frequento a escola todos os dias.' },
  '飾る': { jp: '花を飾ります。', r: 'はなを かざります。', rom: 'hana o kazarimasu.', pt: 'Decoro com flores.' },
  '怪我する': { jp: '足に怪我をしました。', r: 'あしに けがを しました。', rom: 'ashi ni kega o shimashita.', pt: 'Machuquei a perna.' },
  '計画する': { jp: '夏休みの旅行を計画します。', r: 'なつやすみの りょこうを けいかくします。', rom: 'natsuyasumi no ryokou o keikakushimasu.', pt: 'Vou planejar a viagem das férias de verão.' },
  '経験する': { jp: '色々なことを経験しました。', r: 'いろいろな ことを けいけんしました。', rom: 'iroiro na koto o keikenshimashita.', pt: 'Experienciei (vivi) várias coisas.' },
  '見物する': { jp: '京都を見物しました。', r: 'きょうとを けんぶつしました。', rom: 'kyouto o kenbutsushimashita.', pt: 'Fiz turismo em Quioto.' },
  '喧嘩する': { jp: '弟と喧嘩しました。', r: 'おとうとと けんかしました。', rom: 'otouto to kenkashimashita.', pt: 'Briguei com meu irmão mais novo.' },
  '研究する': { jp: '日本の歴史を研究しています。', r: 'にほんの れきしを けんきゅうしています。', rom: 'nihon no rekishi o kenkyuushiteimasu.', pt: 'Estou pesquisando a história do Japão.' },
  '聞こえる': { jp: '鳥の声が聞こえます。', r: 'とりの こえが きこえます。', rom: 'tori no koe ga kikoemasu.', pt: 'Consigo ouvir a voz dos pássaros.' },
  '決まる': { jp: '出発の日が決まりました。', r: 'しゅっぱつの ひが きまりました。', rom: 'shuppatsu no hi ga kimarimashita.', pt: 'O dia da partida foi decidido.' },
  '決める': { jp: 'メニューを決めます。', r: 'メニューを きめます。', rom: 'menyuu o kimemasu.', pt: 'Decido o menu.' },
  '込む': { jp: '電車が込んでいます。', r: 'でんしゃが こんでいます。', rom: 'densha ga kondeimasu.', pt: 'O trem está lotado.' },
  '故障する': { jp: '車が故障しました。', r: 'くるまが こしょうしました。', rom: 'kuruma ga koshoushimashita.', pt: 'O carro quebrou.' },
  '講義する': { jp: '大学で講義します。', r: 'だいがくで こうぎします。', rom: 'daigaku de kougishimasu.', pt: 'Dou aula (palestra) na universidade.' },
  '壊れる': { jp: 'パソコンが壊れました。', r: 'パソコンが こわれました。', rom: 'pasokon ga kowaremashita.', pt: 'O computador quebrou.' },
  '壊す': { jp: '時計を壊してしまいました。', r: 'とけいを こわしてしまいました。', rom: 'tokei o kowashite shimaimashita.', pt: 'Acabei quebrando o relógio.' },
  '下さる': { jp: '先生が本を下さいました。', r: 'せんせいが ほんを くださいました。', rom: 'sensei ga hon o kudasaimashita.', pt: 'O professor me deu um livro (forma polida).' },
  '比べる': { jp: '二つの車を比べます。', r: 'ふたつの くるまを くらべます。', rom: 'futatsu no kuruma o kurabemasu.', pt: 'Comparo os dois carros.' },
  '暮れる': { jp: '日が暮れました。', r: 'ひが くれました。', rom: 'hi ga kuremashita.', pt: 'O dia escureceu.' },
  '教育する': { jp: '子供を教育します。', r: 'こどもを きょういくします。', rom: 'kodomo o kyouikushimasu.', pt: 'Educo as crianças.' },
  '競争する': { jp: '友達と競争します。', r: 'ともだちと きょうそうします。', rom: 'tomodachi to kyousoushimasu.', pt: 'Compito com o amigo.' },
  '急行する': { jp: '現場に急行します。', r: 'げんばに きゅうこうします。', rom: 'genba ni kyuukoushimasu.', pt: 'Apresso-me para ir ao local.' },
  '間違える': { jp: '答えを間違えました。', r: 'こたえを まちがえました。', rom: 'kotae o machigaemashita.', pt: 'Errei a resposta.' },
  '参る': { jp: '明日、そちらへ参ります。', r: 'あした、そちらへ まいります。', rom: 'ashita, sochira e mairimasu.', pt: 'Irei aí amanhã (forma humilde).' },
  '負ける': { jp: '試合に負けました。', r: 'しあいに まけました。', rom: 'shiai ni makemashita.', pt: 'Perdi o jogo.' },
  '間に合う': { jp: '電車に間に合いました。', r: 'でんしゃに まにあいました。', rom: 'densha ni maniaimashita.', pt: 'Cheguei a tempo do trem.' },
  '回る': { jp: '地球は回っています。', r: 'ちきゅうは まわっています。', rom: 'chikyuu wa mawatteimasu.', pt: 'A Terra está girando.' },
  '召し上がる': { jp: 'どうぞ召し上がってください。', r: 'どうぞ めしあがってください。', rom: 'douzo meshiagatte kudasai.', pt: 'Por favor, coma/beba (sirva-se).' },
  '見える': { jp: '窓から山が見えます。', r: 'まどから やまが みえます。', rom: 'mado kara yama ga miemasu.', pt: 'Posso ver a montanha da janela.' },
  '見つかる': { jp: '無くした鍵が見つかりました。', r: 'なくした かぎが みつかりました。', rom: 'nakushita kagi ga mitsukarimashita.', pt: 'A chave perdida foi encontrada.' },
  '見つける': { jp: '良い本を見つけました。', r: 'いい ほんを みつけました。', rom: 'ii hon o mitsukemashita.', pt: 'Encontrei um bom livro.' },
  '戻る': { jp: 'すぐに戻ります。', r: 'すぐに もどります。', rom: 'sugu ni modorimasu.', pt: 'Voltarei logo.' },
  '申し上げる': { jp: 'お礼を申し上げます。', r: 'おれいを もうしあげます。', rom: 'orei o moushiagemasu.', pt: 'Expresso meus agradecimentos (forma humilde).' },
  '申す': { jp: '私は田中と申します。', r: 'わたしは たなかと もうします。', rom: 'watashi wa tanaka to moushimasu.', pt: 'Chamo-me Tanaka.' },
  '迎える': { jp: '駅まで友達を迎えに行きます。', r: 'えきまで ともだちを むかえに いきます。', rom: 'eki made tomodachi o mukae ni ikimasu.', pt: 'Vou buscar meu amigo na estação.' },
  '向かう': { jp: '駅に向かいます。', r: 'えきに むかいます。', rom: 'eki ni mukaimasu.', pt: 'Vou em direção à estação.' },
  '無理する': { jp: '無理しないでください。', r: 'むりしないでください。', rom: 'muri shinaide kudasai.', pt: 'Por favor, não se esforce demais.' },
  '投げる': { jp: 'ボールを投げます。', r: 'ボールを なげます。', rom: 'booru o nagemasu.', pt: 'Arremesso a bola.' },
  '泣く': { jp: '悲しくて泣きました。', r: 'かなしくて なきました。', rom: 'kanashikute nakimashita.', pt: 'Chorei por estar triste.' },
  '無くなる': { jp: 'お金が無くなりました。', r: 'おかねが なくなりました。', rom: 'okane ga nakunarimashita.', pt: 'O dinheiro acabou (desapareceu).' }
};

const filePath = path.join(process.cwd(), 'src/data/vocabN4.ts');
let fileContent = fs.readFileSync(filePath, 'utf8');

const newObjects = items.map((n, i) => {
  const ex = examples[n.w] || {
    jp: "Exemplo",
    reading: "...",
    rom: "...",
    pt: "..."
  };
  
  const safePt = ex.pt.replace(/'/g, "\\'");
  const safeRom = ex.rom.replace(/'/g, "\\'");

  return "  {\n" +
    "    id: 'n4_verb_batch1_" + Date.now() + "_" + i + "',\n" +
    "    word: '" + n.w + "',\n" +
    "    reading: '" + n.r.replace(/'/g, "\\'") + "',\n" +
    "    romaji: '" + n.rom.replace(/'/g, "\\'") + "',\n" +
    "    meaningPt: '" + n.m.replace(/'/g, "\\'") + "',\n" +
    "    category: '" + n.cat + "',\n" +
    "    jlpt: 'N4',\n" +
    "    categoryLabelPt: '" + n.catLabel + "',\n" +
    "    exampleSentence: {\n" +
    "      jp: '" + ex.jp + "',\n" +
    "      reading: '" + ex.r.replace(/'/g, "\\'") + "',\n" +
    "      romaji: '" + safeRom + "',\n" +
    "      meaningPt: '" + safePt + "'\n" +
    "    }\n" +
    "  }";
}).join(',\n');

fileContent = fileContent.replace(
  /export const VOCAB_N4: VocabItem\[\] = \[/,
  "export const VOCAB_N4: VocabItem[] = [\n" + newObjects + ",\n"
);

fs.writeFileSync(filePath, fileContent, 'utf8');
console.log('Added 100 N4 Verbs to vocabN4.ts successfully!');
