import fs from 'fs';
import path from 'path';

const nouns = [
  { w: '飛行機', r: 'ひこうき', rom: 'hikouki', m: 'avião' },
  { w: '暇', r: 'ひま', rom: 'hima', m: 'tempo livre; lazer' },
  { w: '昼', r: 'ひる', rom: 'hiru', m: 'meio-dia; dia' },
  { w: '昼ご飯', r: 'ひるごはん', rom: 'hirugohan', m: 'almoço' },
  { w: '人', r: 'ひと', rom: 'hito', m: 'pessoa; ser humano' },
  { w: '一人', r: 'ひとり', rom: 'hitori', m: 'uma pessoa; sozinho' },
  { w: '一つ', r: 'ひとつ', rom: 'hitotsu', m: 'uma coisa; apenas um' },
  { w: 'ほか', r: 'ほか', rom: 'hoka', m: 'outro (lugar, coisa, pessoa); o resto' },
  { w: '本', r: 'ほん', rom: 'hon', m: 'livro' },
  { w: '本棚', r: 'ほんだな', rom: 'hondana', m: 'estante de livros' },
  { w: '本当', r: 'ほんとう', rom: 'hontou', m: 'verdade; realidade' },
  { w: 'ホテル', r: 'ホテル', rom: 'hoteru', m: 'hotel' },
  { w: '百', r: 'ひゃく', rom: 'hyaku', m: 'cem; 100' },
  { w: '一', r: 'いち', rom: 'ichi', m: 'um; 1' },
  { w: '一番', r: 'いちばん', rom: 'ichiban', m: 'número um; o melhor; o mais' },
  { w: '一日', r: 'いちにち', rom: 'ichinichi', m: 'um dia; o dia todo' },
  { w: '家', r: 'いえ', rom: 'ie', m: 'casa; residência' },
  { w: '池', r: 'いけ', rom: 'ike', m: 'lago; tanque' },
  { w: 'いくら', r: 'いくら', rom: 'ikura', m: 'quanto? (preço)' },
  { w: '今', r: 'いま', rom: 'ima', m: 'agora' },
  { w: '意味', r: 'いみ', rom: 'imi', m: 'significado; sentido' },
  { w: '妹', r: 'いもうと', rom: 'imouto', m: 'irmã mais nova' },
  { w: '犬', r: 'いぬ', rom: 'inu', m: 'cachorro; cão' },
  { w: '入口', r: 'いりぐち', rom: 'iriguchi', m: 'entrada' },
  { w: '色', r: 'いろ', rom: 'iro', m: 'cor' },
  { w: '色々', r: 'いろいろ', rom: 'iroiro', m: 'vários' },
  { w: '医者', r: 'いしゃ', rom: 'isha', m: 'médico(a)' },
  { w: '一緒', r: 'いっしょ', rom: 'issho', m: 'juntos' },
  { w: '椅子', r: 'いす', rom: 'isu', m: 'cadeira' },
  { w: '五日', r: 'いつか', rom: 'itsuka', m: 'dia 5; cinco dias' },
  { w: '五つ', r: 'いつつ', rom: 'itsutsu', m: 'cinco (objetos)' },
  { w: '嫌', r: 'いや', rom: 'iya', m: 'desagradável; não gostar' },
  { w: '字引', r: 'じびき', rom: 'jibiki', m: 'dicionário' },
  { w: '自動車', r: 'じどうしゃ', rom: 'jidousha', m: 'automóvel; carro' },
  { w: '時間', r: 'じかん', rom: 'jikan', m: 'tempo; hora(s)' },
  { w: '辞書', r: 'じしょ', rom: 'jisho', m: 'dicionário' },
  { w: '自転車', r: 'じてんしゃ', rom: 'jitensha', m: 'bicicleta' },
  { w: '上手', r: 'じょうず', rom: 'jouzu', m: 'habilidoso; bom em algo' },
  { w: '授業', r: 'じゅぎょう', rom: 'jugyou', m: 'aula; classe' },
  { w: '十', r: 'じゅう', rom: 'juu', m: 'dez; 10' },
  { w: 'かばん', r: 'かばん', rom: 'kaban', m: 'bolsa; mochila; pasta' },
  { w: '花瓶', r: 'かびん', rom: 'kabin', m: 'vaso (de flor)' },
  { w: '角', r: 'かど', rom: 'kado', m: 'canto; esquina' },
  { w: '鍵', r: 'かぎ', rom: 'kagi', m: 'chave' },
  { w: '階段', r: 'かいだん', rom: 'kaidan', m: 'escada' },
  { w: '買い物', r: 'かいもの', rom: 'kaimono', m: 'compras' },
  { w: '会社', r: 'かいしゃ', rom: 'kaisha', m: 'empresa' },
  { w: 'カメラ', r: 'カメラ', rom: 'kamera', m: 'câmera' },
  { w: '紙', r: 'かみ', rom: 'kami', m: 'papel' },
  { w: '漢字', r: 'かんじ', rom: 'kanji', m: 'ideograma chinês; kanji' },
  { w: 'カップ', r: 'カップ', rom: 'kappu', m: 'xícara; copo' },
  { w: '体', r: 'からだ', rom: 'karada', m: 'corpo' },
  { w: 'カレー', r: 'カレー', rom: 'karee', m: 'curry' },
  { w: 'カレンダー', r: 'カレンダー', rom: 'karendaa', m: 'calendário' },
  { w: '傘', r: 'かさ', rom: 'kasa', m: 'guarda-chuva' },
  { w: '方', r: 'かた', rom: 'kata', m: 'modo de fazer; pessoa (polido)' },
  { w: '家庭', r: 'かてい', rom: 'katei', m: 'lar; família' },
  { w: '川', r: 'かわ', rom: 'kawa', m: 'rio' },
  { w: '火曜日', r: 'かようび', rom: 'kayoubi', m: 'terça-feira' },
  { w: '風', r: 'かぜ', rom: 'kaze', m: 'vento' },
  { w: '風邪', r: 'かぜ', rom: 'kaze_2', m: 'resfriado' },
  { w: '家族', r: 'かぞく', rom: 'kazoku', m: 'família' },
  { w: '警官', r: 'けいかん', rom: 'keikan', m: 'policial' },
  { w: '結婚', r: 'けっこん', rom: 'kekkon', m: 'casamento' },
  { w: '結構', r: 'けっこう', rom: 'kekkou', m: 'esplêndido; suficiente' },
  { w: '今朝', r: 'けさ', rom: 'kesa', m: 'esta manhã' },
  { w: '木', r: 'き', rom: 'ki', m: 'árvore; madeira' },
  { w: '昨日', r: 'きのう', rom: 'kinou', m: 'ontem' },
  { w: '金曜日', r: 'きんようび', rom: 'kinyoubi', m: 'sexta-feira' },
  { w: '切符', r: 'きっぷ', rom: 'kippu', m: 'passagem; bilhete' },
  { w: '嫌い', r: 'きらい', rom: 'kirai', m: 'odiar; não gostar' },
  { w: 'キログラム', r: 'キログラム', rom: 'kiroguramu', m: 'quilograma' },
  { w: 'キロメートル', r: 'キロメートル', rom: 'kiromeetoru', m: 'quilômetro' },
  { w: '喫茶店', r: 'きっさてん', rom: 'kissaten', m: 'cafeteria' },
  { w: '北', r: 'きた', rom: 'kita', m: 'norte' },
  { w: '切手', r: 'きって', rom: 'kitte', m: 'selo (postal)' },
  { w: 'こっち', r: 'こっち', rom: 'kocchi', m: 'por aqui; esta pessoa/direção' },
  { w: 'こちら', r: 'こちら', rom: 'kochira', m: 'por aqui; esta direção (polido)' },
  { w: '子供', r: 'こども', rom: 'kodomo', m: 'criança' },
  { w: '声', r: 'こえ', rom: 'koe', m: 'voz' },
  { w: '九日', r: 'ここのか', rom: 'kokonoka', m: 'dia 9; nove dias' },
  { w: '九つ', r: 'ここのつ', rom: 'kokonotsu', m: 'nove (objetos)' },
  { w: '今晩', r: 'こんばん', rom: 'konban', m: 'esta noite' },
  { w: '今月', r: 'こんげつ', rom: 'kongetsu', m: 'este mês' },
  { w: '今週', r: 'こんしゅう', rom: 'konshuu', m: 'esta semana' },
  { w: 'コーヒー', r: 'コーヒー', rom: 'koohii', m: 'café' },
  { w: 'コート', r: 'コート', rom: 'kooto', m: 'casaco' },
  { w: 'コピー', r: 'コピー', rom: 'kopii', m: 'cópia; xerox' },
  { w: 'コップ', r: 'コップ', rom: 'koppu', m: 'copo' },
  { w: '言葉', r: 'ことば', rom: 'kotoba', m: 'palavra(s); idioma' },
  { w: '今年', r: 'ことし', rom: 'kotoshi', m: 'este ano' },
  { w: '交番', r: 'こうばん', rom: 'kouban', m: 'posto policial' },
  { w: '紅茶', r: 'こうちゃ', rom: 'koucha', m: 'chá preto' },
  { w: '公園', r: 'こうえん', rom: 'kouen', m: 'parque' },
  { w: '交差点', r: 'こうさてん', rom: 'kousaten', m: 'cruzamento' },
  { w: '口', r: 'くち', rom: 'kuchi', m: 'boca; abertura' },
  { w: '果物', r: 'くだもの', rom: 'kudamono', m: 'fruta' },
  { w: '曇り', r: 'くもり', rom: 'kumori', m: 'nublado' },
  { w: '国', r: 'くに', rom: 'kuni', m: 'país' },
  { w: 'クラス', r: 'クラス', rom: 'kurasu', m: 'classe; turma' }
];

const examples = {
  '飛行機': { jp: '飛行機で旅行に行きます。', r: 'ひこうきで りょこうに いきます。', rom: 'hikouki de ryokou ni ikimasu.', pt: 'Vou viajar de avião.' },
  '暇': { jp: '明日は暇ですか。', r: 'あしたは ひまですか。', rom: 'ashita wa hima desu ka.', pt: 'Você está livre amanhã?' },
  '昼': { jp: '昼まで寝ていました。', r: 'ひるまで ねていました。', rom: 'hiru made neteimashita.', pt: 'Dormi até o meio-dia.' },
  '昼ご飯': { jp: '昼ご飯を食べましょう。', r: 'ひるごはんを たべましょう。', rom: 'hirugohan o tabemashou.', pt: 'Vamos almoçar.' },
  '人': { jp: 'あの人は誰ですか。', r: 'あの ひと は だれですか。', rom: 'ano hito wa dare desu ka.', pt: 'Quem é aquela pessoa?' },
  '一人': { jp: '一人で買い物をします。', r: 'ひとりで かいものを します。', rom: 'hitori de kaimono o shimasu.', pt: 'Faço compras sozinho.' },
  '一つ': { jp: 'みかんを一つください。', r: 'みかんを ひとつください。', rom: 'mikan o hitotsu kudasai.', pt: 'Me dê uma tangerina, por favor.' },
  'ほか': { jp: 'ほかの靴も見せてください。', r: 'ほかの くつも みせてください。', rom: 'hoka no kutsu mo misete kudasai.', pt: 'Por favor, mostre-me outros sapatos também.' },
  '本': { jp: '図書館で本を借ります。', r: 'としょかんで ほんを かります。', rom: 'toshokan de hon o karimasu.', pt: 'Pego um livro emprestado na biblioteca.' },
  '本棚': { jp: '本を本棚に片付けます。', r: 'ほんを ほんだなに かたづけます。', rom: 'hon o hondana ni katadukemasu.', pt: 'Guardo os livros na estante.' },
  '本当': { jp: 'それは本当の話ですか。', r: 'それは ほんとうの はなしですか。', rom: 'sore wa hontou no hanashi desu ka.', pt: 'Isso é uma história verdadeira?' },
  'ホテル': { jp: '駅前のホテルに泊まります。', r: 'えきまえの ホテルに とまります。', rom: 'ekimae no hoteru ni tomarimasu.', pt: 'Vou me hospedar no hotel em frente à estação.' },
  '百': { jp: '百円のペンを買いました。', r: 'ひゃくえんの ペンを かいました。', rom: 'hyakuen no pen o kaimashita.', pt: 'Comprei uma caneta de cem ienes.' },
  '一': { jp: '一から十まで数えます。', r: 'いちから じゅうまで かぞえます。', rom: 'ichi kara juu made kazoemasu.', pt: 'Eu conto de um a dez.' },
  '一番': { jp: 'これが一番美味しいです。', r: 'これが いちばん おいしいです。', rom: 'kore ga ichiban oishii desu.', pt: 'Isto é o mais delicioso.' },
  '一日': { jp: '一日中雨が降っていました。', r: 'いちにちじゅう あめが ふっていました。', rom: 'ichinichijuu ame ga futteimashita.', pt: 'Choveu o dia todo.' },
  '家': { jp: '私の家は駅から近いです。', r: 'わたしの いえは えきから ちかいです。', rom: 'watashi no ie wa eki kara chikai desu.', pt: 'Minha casa é perto da estação.' },
  '池': { jp: '公園に大きな池があります。', r: 'こうえんに おおきな いけが あります。', rom: 'kouen ni ookina ike ga arimasu.', pt: 'Há um grande lago no parque.' },
  'いくら': { jp: 'この本はいくらですか。', r: 'この ほんは いくらですか。', rom: 'kono hon wa ikura desu ka.', pt: 'Quanto custa este livro?' },
  '今': { jp: '今は何時ですか。', r: 'いまは なんじですか。', rom: 'ima wa nanji desu ka.', pt: 'Que horas são agora?' },
  '意味': { jp: 'この漢字の意味を教えてください。', r: 'この かんじの いみを おしえてください。', rom: 'kono kanji no imi o oshiete kudasai.', pt: 'Por favor, me ensine o significado deste kanji.' },
  '妹': { jp: '妹は中学生です。', r: 'いもうとは ちゅうがくせいです。', rom: 'imouto wa chuugakusei desu.', pt: 'Minha irmã mais nova está no ensino fundamental.' },
  '犬': { jp: '犬と散歩に行きます。', r: 'いぬと さんぽに いきます。', rom: 'inu to sanpo ni ikimasu.', pt: 'Vou passear com o cachorro.' },
  '入口': { jp: '建物の入口で待ちましょう。', r: 'たてものの いりぐちで まちましょう。', rom: 'tatemono no iriguchi de machimashou.', pt: 'Vamos esperar na entrada do prédio.' },
  '色': { jp: '何色が好きですか。', r: 'なにいろが すきですか。', rom: 'nani iro ga suki desu ka.', pt: 'De qual cor você gosta?' },
  '色々': { jp: '色々な料理を食べました。', r: 'いろいろな りょうりを たべました。', rom: 'iroiro na ryouri o tabemashita.', pt: 'Comi vários tipos de pratos.' },
  '医者': { jp: '医者に薬をもらいました。', r: 'いしゃに くすりを もらいました。', rom: 'isha ni kusuri o moraimashita.', pt: 'Recebi remédio do médico.' },
  '一緒': { jp: '一緒に映画を見に行きませんか。', r: 'いっしょに えいがを みに いきませんか。', rom: 'issho ni eiga o mini ikimasen ka.', pt: 'Gostaria de ir ver um filme juntos?' },
  '椅子': { jp: 'どうぞ椅子に座ってください。', r: 'どうぞ いすに すわってください。', rom: 'douzo isu ni suwatte kudasai.', pt: 'Por favor, sente-se na cadeira.' },
  '五日': { jp: '五日後に帰ります。', r: 'いつかごに かえります。', rom: 'itsukago ni kaerimasu.', pt: 'Voltarei daqui a cinco dias.' },
  '五つ': { jp: '卵を五つ買いました。', r: 'たまごを いつつ かいました。', rom: 'tamago o itsutsu kaimashita.', pt: 'Comprei cinco ovos.' },
  '嫌': { jp: '嫌な予感がします。', r: 'いやな よかんが します。', rom: 'iya na yokan ga shimasu.', pt: 'Tenho um mau pressentimento.' },
  '字引': { jp: 'わからない言葉は字引で調べます。', r: 'わからない ことばは じびきで しらべます。', rom: 'wakaranai kotoba wa jibiki de shirabemasu.', pt: 'Eu procuro palavras que não conheço no dicionário.' },
  '自動車': { jp: '自動車を作る工場を見学しました。', r: 'じどうしゃを つくる こうじょうを けんがくしました。', rom: 'jidousha o tsukuru koujou o kengakushimashita.', pt: 'Fiz uma visita a uma fábrica que produz automóveis.' },
  '時間': { jp: 'もう寝る時間ですよ。', r: 'もう ねる じかんですよ。', rom: 'mou neru jikan desu yo.', pt: 'Já é hora de dormir.' },
  '辞書': { jp: '英語の辞書を買いました。', r: 'えいごの じしょを かいました。', rom: 'eigo no jisho o kaimashita.', pt: 'Comprei um dicionário de inglês.' },
  '自転車': { jp: '自転車で買い物に行きます。', r: 'じてんしゃで かいものに いきます。', rom: 'jitensha de kaimono ni ikimasu.', pt: 'Vou fazer compras de bicicleta.' },
  '上手': { jp: '彼女はピアノがとても上手です。', r: 'かのじょは ピアノが とても じょうずです。', rom: 'kanojo wa piano ga totemo jouzu desu.', pt: 'Ela toca piano muito bem.' },
  '授業': { jp: '今日の授業はこれで終わります。', r: 'きょうの じゅぎょうは これで おわります。', rom: 'kyou no jugyou wa kore de owarimasu.', pt: 'A aula de hoje termina por aqui.' },
  '十': { jp: '一から十まで数えます。', r: 'いちから じゅうまで かぞえます。', rom: 'ichi kara juu made kazoemasu.', pt: 'Conto de um até dez.' },
  'かばん': { jp: 'このかばんはとても重いです。', r: 'この かばんは とても おもいです。', rom: 'kono kaban wa totemo omoi desu.', pt: 'Esta bolsa é muito pesada.' },
  '花瓶': { jp: '花瓶に花を飾りました。', r: 'かびんに はなを かざりました。', rom: 'kabin ni hana o kazarimashita.', pt: 'Decorei o vaso com flores.' },
  '角': { jp: '次の角を右に曲がってください。', r: 'つぎの かどを みぎに まがってください。', rom: 'tsugi no kado o migi ni magatte kudasai.', pt: 'Por favor, vire à direita na próxima esquina.' },
  '鍵': { jp: '部屋の鍵を忘れました。', r: 'へやの かぎを わすれました。', rom: 'heya no kagi o wasuremashita.', pt: 'Esqueci a chave do quarto.' },
  '階段': { jp: '階段を上って二階へ行きます。', r: 'かいだんを のぼって にかいへ いきます。', rom: 'kaidan o nobotte nikai e ikimasu.', pt: 'Suba as escadas e vá para o segundo andar.' },
  '買い物': { jp: '休日に買い物をしました。', r: 'きゅうじつに かいものを しました。', rom: 'kyuujitsu ni kaimono o shimashita.', pt: 'Fiz compras no feriado.' },
  '会社': { jp: '明日、会社を休みます。', r: 'あした、かいしゃを やすみます。', rom: 'ashita, kaisha o yasumimasu.', pt: 'Amanhã faltarei à empresa.' },
  'カメラ': { jp: '新しいカメラを買いました。', r: 'あたらしい カメラを かいました。', rom: 'atarashii kamera o kaimashita.', pt: 'Comprei uma câmera nova.' },
  '紙': { jp: 'この紙に名前を書いてください。', r: 'この かみに なまえを かいてください。', rom: 'kono kami ni namae o kaite kudasai.', pt: 'Por favor, escreva seu nome neste papel.' },
  '漢字': { jp: '毎日漢字を勉強します。', r: 'まいにち かんじを べんきょうします。', rom: 'mainichi kanji o benkyoushimasu.', pt: 'Estudo kanji todos os dias.' },
  'カップ': { jp: 'カップにコーヒーを注ぎました。', r: 'カップに コーヒーを そそぎました。', rom: 'kappu ni koohii o sosogimashita.', pt: 'Despejei café na xícara.' },
  '体': { jp: '体に気をつけてください。', r: 'からだに きをつけてください。', rom: 'karada ni ki o tsukete kudasai.', pt: 'Cuide da sua saúde (corpo).' },
  'カレー': { jp: '今日の晩ご飯はカレーです。', r: 'きょうの ばんごはんは カレーです。', rom: 'kyou no bangohan wa karee desu.', pt: 'O jantar de hoje é curry.' },
  'カレンダー': { jp: 'カレンダーに予定を書き込みました。', r: 'カレンダーに よていを かきこみました。', rom: 'karendaa ni yotei o kakikomimashita.', pt: 'Anotei os compromissos no calendário.' },
  '傘': { jp: '雨が降っているので傘をさします。', r: 'あめが ふっているので かさを さします。', rom: 'ame ga futteiru node kasa o sashimasu.', pt: 'Está chovendo, então vou abrir o guarda-chuva.' },
  '方': { jp: 'この料理の作り方を教えてください。', r: 'この りょうりの つくりかたを おしえてください。', rom: 'kono ryouri no tsukurikata o oshiete kudasai.', pt: 'Por favor, me ensine como fazer este prato.' },
  '家庭': { jp: '彼は温かい家庭を築きました。', r: 'かれは あたたかい かていを きずきました。', rom: 'kare wa atatakai katei o kizukimashita.', pt: 'Ele construiu uma família calorosa.' },
  '川': { jp: '川で魚を釣りました。', r: 'かわで さかなを つりました。', rom: 'kawa de sakana o tsurimashita.', pt: 'Pesquei peixes no rio.' },
  '火曜日': { jp: '火曜日にテストがあります。', r: 'かようびに テストが あります。', rom: 'kayoubi ni tesuto ga arimasu.', pt: 'Tenho um teste na terça-feira.' },
  '風': { jp: '今日は強い風が吹いています。', r: 'きょうは つよい かぜが ふいています。', rom: 'kyou wa tsuyoi kaze ga fuiteimasu.', pt: 'Hoje está ventando forte.' },
  '風邪': { jp: '風邪をひいて熱が出ました。', r: 'かぜを ひいて ねつが でました。', rom: 'kaze o hiite netsu ga demashita.', pt: 'Peguei um resfriado e tive febre.' },
  '家族': { jp: '家族と一緒に食事をします。', r: 'かぞくと いっしょに しょくじを します。', rom: 'kazoku to issho ni shokuji o shimasu.', pt: 'Faço refeições junto com minha família.' },
  '警官': { jp: '道に迷ったので警官に道を聞きました。', r: 'みちに まよったので けいかんに みちを ききました。', rom: 'michi ni mayotta node keikan ni michi o kikimashita.', pt: 'Me perdi e perguntei o caminho ao policial.' },
  '結婚': { jp: '来年、結婚する予定です。', r: 'らいねん、けっこんする よていです。', rom: 'rainen, kekkonsuru yotei desu.', pt: 'Planejo me casar no ano que vem.' },
  '結構': { jp: 'もう十分いただきました。結構です。', r: 'もう じゅうぶん いただきました。けっこうです。', rom: 'mou juubun itadakimashita. kekkou desu.', pt: 'Já comi o suficiente. Estou satisfeito.' },
  '今朝': { jp: '今朝は早く起きました。', r: 'けさは はやく おきました。', rom: 'kesa wa hayaku okimashita.', pt: 'Esta manhã acordei cedo.' },
  '木': { jp: '庭にりんごの木を植えました。', r: 'にわに りんごの きを うえました。', rom: 'niwa ni ringo no ki o uemashita.', pt: 'Plantei uma macieira no jardim.' },
  '昨日': { jp: '昨日は一日中雨でした。', r: 'きのうは いちにちじゅう あめでした。', rom: 'kinou wa ichinichijuu ame deshita.', pt: 'Ontem choveu o dia todo.' },
  '金曜日': { jp: '金曜日の夜は友達と飲みに行きます。', r: 'きんようびの よるは ともだちと のみに いきます。', rom: 'kinyoubi no yoru wa tomodachi to nomi ni ikimasu.', pt: 'Nas noites de sexta vou beber com amigos.' },
  '切符': { jp: '駅で電車の切符を買いました。', r: 'えきで でんしゃの きっぷを かいました。', rom: 'eki de densha no kippu o kaimashita.', pt: 'Comprei a passagem de trem na estação.' },
  '嫌い': { jp: '私はピーマンが嫌いです。', r: 'わたしは ピーマンが きらいです。', rom: 'watashi wa piiman ga kirai desu.', pt: 'Eu não gosto de pimentão.' },
  'キログラム': { jp: '私の体重は六十キログラムです。', r: 'わたしの たいじゅうは ろくじゅうキログラムです。', rom: 'watashi no taijuu wa rokujuu kiroguramu desu.', pt: 'Meu peso é sessenta quilogramas.' },
  'キロメートル': { jp: 'ここから駅まで二キロメートルあります。', r: 'ここから えきまで にキロメートルあります。', rom: 'koko kara eki made ni kiromeetoru arimasu.', pt: 'Daqui até a estação são dois quilômetros.' },
  '喫茶店': { jp: '喫茶店でコーヒーを飲みながら本を読みました。', r: 'きっさてんで コーヒーを のみながら ほんを よみました。', rom: 'kissaten de koohii o nominagara hon o yomimashita.', pt: 'Li um livro enquanto bebia café na cafeteria.' },
  '北': { jp: 'この窓は北を向いています。', r: 'この まどは きたを むいています。', rom: 'kono mado wa kita o muiteimasu.', pt: 'Esta janela está voltada para o norte.' },
  '切手': { jp: '手紙に切手を貼ってポストに出しました。', r: 'てがみに きってを はって ポストに だしました。', rom: 'tegami ni kitte o hatte posuto ni dashimashita.', pt: 'Colei um selo na carta e coloquei na caixa de correio.' },
  'こっち': { jp: 'こっちへ来てください。', r: 'こっちへ きてください。', rom: 'kocchi e kite kudasai.', pt: 'Venha para cá, por favor.' },
  'こちら': { jp: 'こちらが私の妻です。', r: 'こちらが わたしの つまです。', rom: 'kochira ga watashi no tsuma desu.', pt: 'Esta é a minha esposa.' },
  '子供': { jp: '公園で子供たちが遊んでいます。', r: 'こうえんで こどもたちが あそんでいます。', rom: 'kouen de kodomotachi ga asondeimasu.', pt: 'As crianças estão brincando no parque.' },
  '声': { jp: '大きな声で話してください。', r: 'おおきな こえで はなしてください。', rom: 'ookina koe de hanashite kudasai.', pt: 'Fale com uma voz alta, por favor.' },
  '九日': { jp: '来月の九日に出発します。', r: 'らいげつの ここのかに しゅっぱつします。', rom: 'raigetsu no kokonoka ni shuppatsushimasu.', pt: 'Partirei no dia nove do próximo mês.' },
  '九つ': { jp: 'みかんが九つあります。', r: 'みかんが ここのつ あります。', rom: 'mikan ga kokonotsu arimasu.', pt: 'Há nove tangerinas.' },
  '今晩': { jp: '今晩、一緒に映画を見に行きませんか。', r: 'こんばん、いっしょに えいがを みに いきませんか。', rom: 'konban, issho ni eiga o mini ikimasen ka.', pt: 'Gostaria de ir ver um filme juntos esta noite?' },
  '今月': { jp: '今月は仕事が忙しいです。', r: 'こんげつは しごとが いそがしいです。', rom: 'kongetsu wa shigoto ga isogashii desu.', pt: 'Este mês o trabalho está corrido.' },
  '今週': { jp: '今週の週末は海に行きます。', r: 'こんしゅうの しゅうまつは うみに いきます。', rom: 'konshuu no shuumatsu wa umi ni ikimasu.', pt: 'No final desta semana irei à praia.' },
  'コーヒー': { jp: '朝食にコーヒーを飲みます。', r: 'ちょうしょくに コーヒーを のみます。', rom: 'choushoku ni koohii o nomimasu.', pt: 'Bebo café no café da manhã.' },
  'コート': { jp: '外は寒いのでコートを着て出かけました。', r: 'そとは さむいので コートを きて でかけました。', rom: 'soto wa samui node kooto o kite dekakemashita.', pt: 'Como estava frio lá fora, vesti um casaco e saí.' },
  'コピー': { jp: 'この書類をコピーしてください。', r: 'この しょるいを コピーしてください。', rom: 'kono shorui o kopii shite kudasai.', pt: 'Por favor, tire uma cópia deste documento.' },
  'コップ': { jp: 'コップに水を入れます。', r: 'コップに みずを いれます。', rom: 'koppu ni mizu o iremasu.', pt: 'Colocar água no copo.' },
  '言葉': { jp: 'その言葉の意味がわかりません。', r: 'その ことばの いみが わかりません。', rom: 'sono kotoba no imi ga wakarimasen.', pt: 'Não entendo o significado dessa palavra.' },
  '今年': { jp: '今年はたくさん旅行に行きたいです。', r: 'ことしは たくさん りょこうに いきたいです。', rom: 'kotoshi wa takusan ryokou ni ikitai desu.', pt: 'Quero viajar muito este ano.' },
  '交番': { jp: '駅の前に交番があります。', r: 'えきの まえに こうばんが あります。', rom: 'eki no mae ni kouban ga arimasu.', pt: 'Há um posto policial em frente à estação.' },
  '紅茶': { jp: '午後の紅茶を楽しみます。', r: 'ごごの こうちゃを たのしみます。', rom: 'gogo no koucha o tanoshimimasu.', pt: 'Apreciar um chá preto da tarde.' },
  '公園': { jp: '休日はよく公園を散歩します。', r: 'きゅうじつは よく こうえんを さんぽします。', rom: 'kyuujitsu wa yoku kouen o sanposhimasu.', pt: 'Costumo passear no parque nos feriados.' },
  '交差点': { jp: '次の交差点を右に曲がります。', r: 'つぎの こうさてんを みぎに まがります。', rom: 'tsugi no kousaten o migi ni magarimasu.', pt: 'Vou virar à direita no próximo cruzamento.' },
  '口': { jp: '口を開けてください。', r: 'くちを あけてください。', rom: 'kuchi o akete kudasai.', pt: 'Por favor, abra a boca.' },
  '果物': { jp: '食後に果物を食べます。', r: 'しょくごに くだものを たべます。', rom: 'shokugo ni kudamono o tabemasu.', pt: 'Como frutas após as refeições.' },
  '曇り': { jp: '今日の天気は曇りです。', r: 'きょうの てんきは くもりです。', rom: 'kyou no tenki wa kumori desu.', pt: 'O tempo de hoje está nublado.' },
  '国': { jp: 'あなたのお国はどちらですか。', r: 'あなたの おくには どちらですか。', rom: 'anata no okuni wa dochira desu ka.', pt: 'De qual país você é?' },
  'クラス': { jp: '私のクラスには留学生がいます。', r: 'わたしの クラスには りゅうがくせいが います。', rom: 'watashi no kurasu ni wa ryuugakusei ga imasu.', pt: 'Na minha classe há estudantes estrangeiros.' },
};

const filePath = path.join(process.cwd(), 'src/data/vocabN5.ts');
let fileContent = fs.readFileSync(filePath, 'utf8');

const newObjects = nouns.map((n, i) => {
  const ex = examples[n.w] || {
    jp: "Exemplo",
    reading: "...",
    rom: "...",
    pt: "..."
  };

  return "  {\n" +
    "    id: 'n5_noun_batch2_" + Date.now() + "_" + i + "',\n" +
    "    word: '" + n.w + "',\n" +
    "    reading: '" + n.r + "',\n" +
    "    romaji: '" + n.rom + "',\n" +
    "    meaningPt: '" + n.m + "',\n" +
    "    category: 'substantivo',\n" +
    "    jlpt: 'N5',\n" +
    "    categoryLabelPt: 'Substantivo N5',\n" +
    "    exampleSentence: {\n" +
    "      jp: '" + ex.jp + "',\n" +
    "      reading: '" + ex.r + "',\n" +
    "      romaji: '" + ex.rom + "',\n" +
    "      meaningPt: '" + ex.pt + "'\n" +
    "    }\n" +
    "  }";
}).join(',\n');

fileContent = fileContent.replace(
  /export const VOCAB_N5: VocabItem\[\] = \[/,
  "export const VOCAB_N5: VocabItem[] = [\n" + newObjects + ",\n"
);

fs.writeFileSync(filePath, fileContent, 'utf8');
console.log('Added 100 more N5 Nouns to vocabN5.ts successfully!');
