import fs from 'fs';
import path from 'path';

const newKanjis = [
  { id: 'k_n2_add9_1', kanji: '総', onyomi: ['ソウ (sou)'], kunyomi: ['すべ.て (sube.te)'], meaningPt: 'Total, Geral', strokes: 14, radical: '糸 (fio)', jlpt: 'N2', examples: [ { word: '総合', reading: 'そうごう (sougou)', meaningPt: 'Síntese / Compreensivo' }, { word: '総理大臣', reading: 'そうりだいじん (souridaijin)', meaningPt: 'Primeiro Ministro' }, { word: '総じて', reading: 'そうじて (soujite)', meaningPt: 'No geral' } ] },
  { id: 'k_n2_add9_2', kanji: '窓', onyomi: ['ソウ (sou)'], kunyomi: ['まど (mado)'], meaningPt: 'Janela', strokes: 11, radical: '穴 (buraco)', jlpt: 'N2', examples: [ { word: '窓', reading: 'まど (mado)', meaningPt: 'Janela' }, { word: '窓口', reading: 'まどぐち (madoguchi)', meaningPt: 'Guichê / Balcão' }, { word: '同窓会', reading: 'どうそうかい (dousoukai)', meaningPt: 'Encontro de ex-alunos' } ] },
  { id: 'k_n2_add9_3', kanji: '相', onyomi: ['ソウ (sou)', 'ショウ (shou)'], kunyomi: ['あい (ai)'], meaningPt: 'Mútuo, Ministro, Face', strokes: 9, radical: '目 (olho)', jlpt: 'N2', examples: [ { word: '相手', reading: 'あいて (aite)', meaningPt: 'Companheiro / Oponente' }, { word: '相談', reading: 'そうだん (soudan)', meaningPt: 'Consulta / Discussão' }, { word: '首相', reading: 'しゅしょう (shushou)', meaningPt: 'Primeiro Ministro' } ] },
  { id: 'k_n2_add9_4', kanji: '争', onyomi: ['ソウ (sou)'], kunyomi: ['あらそ.う (araso.u)'], meaningPt: 'Disputa, Conflito', strokes: 6, radical: '亅 (gancho)', jlpt: 'N2', examples: [ { word: '争う', reading: 'あらそう (arasou)', meaningPt: 'Disputar / Lutar por' }, { word: '戦争', reading: 'せんそう (sensou)', meaningPt: 'Guerra' }, { word: '競争', reading: 'きょうそう (kyousou)', meaningPt: 'Competição' } ] },
  { id: 'k_n2_add9_5', kanji: '燥', onyomi: ['ソウ (sou)'], kunyomi: [], meaningPt: 'Seco', strokes: 17, radical: '火 (fogo)', jlpt: 'N2', examples: [ { word: '乾燥', reading: 'かんそう (kansou)', meaningPt: 'Secura / Árido' }, { word: '乾燥機', reading: 'かんそうき (kansouki)', meaningPt: 'Secadora (de roupas)' } ] },
  { id: 'k_n2_add9_6', kanji: '操', onyomi: ['ソウ (sou)'], kunyomi: ['あやつ.る (ayatsu.ru)', 'みさお (misao)'], meaningPt: 'Manobrar, Operar, Fidelidade', strokes: 16, radical: '手 (mão)', jlpt: 'N2', examples: [ { word: '操作', reading: 'そうさ (sousa)', meaningPt: 'Operação / Manuseio' }, { word: '体操', reading: 'たいそう (taisou)', meaningPt: 'Ginástica' }, { word: '操る', reading: 'あやつる (ayatsuru)', meaningPt: 'Manipular / Controlar (alguém/máquina)' } ] },
  { id: 'k_n2_add9_7', kanji: '掃', onyomi: ['ソウ (sou)'], kunyomi: ['は.く (ha.ku)'], meaningPt: 'Varrer', strokes: 11, radical: '手 (mão)', jlpt: 'N2', examples: [ { word: '掃除', reading: 'そうじ (souji)', meaningPt: 'Limpeza / Varrer' }, { word: '掃く', reading: 'はく (haku)', meaningPt: 'Varrer' }, { word: '清掃', reading: 'せいそう (seisou)', meaningPt: 'Limpeza (profunda)' } ] },
  { id: 'k_n2_add9_8', kanji: '捜', onyomi: ['ソウ (sou)'], kunyomi: ['さが.す (saga.su)'], meaningPt: 'Procurar, Investigar', strokes: 10, radical: '手 (mão)', jlpt: 'N2', examples: [ { word: '捜す', reading: 'さがす (sagasu)', meaningPt: 'Procurar (algo/alguém perdido)' }, { word: '捜査', reading: 'そうさ (sousa)', meaningPt: 'Investigação (policial)' }, { word: '捜索', reading: 'そうさく (sousaku)', meaningPt: 'Busca (por desaparecidos)' } ] },
  { id: 'k_n2_add9_9', kanji: '想', onyomi: ['ソウ (sou)', 'ソ (so)'], kunyomi: [], meaningPt: 'Pensamento, Imaginação', strokes: 13, radical: '心 (coração)', jlpt: 'N2', examples: [ { word: '想像', reading: 'そうぞう (souzou)', meaningPt: 'Imaginação' }, { word: '感想', reading: 'かんそう (kansou)', meaningPt: 'Impressão / Opinião' }, { word: '理想', reading: 'りそう (risou)', meaningPt: 'Ideal' } ] },
  { id: 'k_n2_add9_10', kanji: '層', onyomi: ['ソウ (sou)'], kunyomi: [], meaningPt: 'Camada, Estrato', strokes: 14, radical: '尸 (cadáver/bandeira)', jlpt: 'N2', examples: [ { word: '地層', reading: 'ちそう (chisou)', meaningPt: 'Camada geológica' }, { word: '階層', reading: 'かいそう (kaisou)', meaningPt: 'Classe social / Hierarquia' }, { word: '高層ビル', reading: 'こうそうびる (kousoubiru)', meaningPt: 'Arranha-céu' } ] },
  { id: 'k_n2_add9_11', kanji: '双', onyomi: ['ソウ (sou)'], kunyomi: ['ふた (futa)'], meaningPt: 'Par, Ambos', strokes: 4, radical: '又 (de novo)', jlpt: 'N2', examples: [ { word: '双子', reading: 'ふたご (futago)', meaningPt: 'Gêmeos' }, { word: '双方', reading: 'そうほう (souhou)', meaningPt: 'Ambas as partes' }, { word: '双眼鏡', reading: 'そうがんきょう (sougankyou)', meaningPt: 'Binóculos' } ] },
  { id: 'k_n2_add9_12', kanji: '組', onyomi: ['ソ (so)'], kunyomi: ['く.む (ku.mu)', 'くみ (kumi)'], meaningPt: 'Grupo, Associar, Montar', strokes: 11, radical: '糸 (fio)', jlpt: 'N2', examples: [ { word: '組む', reading: 'くむ (kumu)', meaningPt: 'Montar / Fazer parceria / Cruzar (braços)' }, { word: '番組', reading: 'ばんぐみ (bangumi)', meaningPt: 'Programa (de TV/rádio)' }, { word: '組織', reading: 'そしき (soshiki)', meaningPt: 'Organização' } ] },
  { id: 'k_n2_add9_13', kanji: '祖', onyomi: ['ソ (so)'], kunyomi: [], meaningPt: 'Ancestral, Fundador', strokes: 9, radical: '示 (mostrar)', jlpt: 'N2', examples: [ { word: '祖父', reading: 'そふ (sofu)', meaningPt: 'Avô' }, { word: '祖母', reading: 'そぼ (sobo)', meaningPt: 'Avó' }, { word: '先祖', reading: 'せんぞ (senzo)', meaningPt: 'Ancestrais' } ] },
  { id: 'k_n2_add9_14', kanji: '全', onyomi: ['ゼン (zen)'], kunyomi: ['まった.く (matta.ku)', 'すべ.て (sube.te)'], meaningPt: 'Tudo, Todo, Inteiro', strokes: 6, radical: '入 (entrar)', jlpt: 'N2', examples: [ { word: '全部', reading: 'ぜんぶ (zenbu)', meaningPt: 'Tudo / Todo' }, { word: '全然', reading: 'ぜんぜん (zenzen)', meaningPt: 'Absolutamente (não) / Nada' }, { word: '全国', reading: 'ぜんこく (zenkoku)', meaningPt: 'Todo o país / Nacional' } ] },
  { id: 'k_n2_add9_15', kanji: '然', onyomi: ['ゼン (zen)', 'ネン (nen)'], kunyomi: ['しか.り (shika.ri)'], meaningPt: 'Sufixo para "assim, desse jeito"', strokes: 12, radical: '火 (fogo)', jlpt: 'N2', examples: [ { word: '自然', reading: 'しぜん (shizen)', meaningPt: 'Natureza' }, { word: '突然', reading: 'とつぜん (totsuzen)', meaningPt: 'De repente' }, { word: '当然', reading: 'とうぜん (touzen)', meaningPt: 'Naturalmente / Como esperado' } ] },
  { id: 'k_n2_add9_16', kanji: '善', onyomi: ['ゼン (zen)'], kunyomi: ['よ.い (yo.i)', 'い.い (i.i)'], meaningPt: 'Bom, Bondade', strokes: 12, radical: '口 (boca)', jlpt: 'N2', examples: [ { word: '改善', reading: 'かいぜん (kaizen)', meaningPt: 'Melhoria' }, { word: '親善', reading: 'しんぜん (shinzen)', meaningPt: 'Boa vontade / Amizade' }, { word: '善良', reading: 'ぜんりょう (zenryou)', meaningPt: 'Bondade / Virtude' } ] },
  { id: 'k_n2_add9_17', kanji: '選', onyomi: ['セン (sen)'], kunyomi: ['えら.ぶ (era.bu)'], meaningPt: 'Escolher, Eleger', strokes: 15, radical: '辵 (caminhar)', jlpt: 'N2', examples: [ { word: '選ぶ', reading: 'えらぶ (erabu)', meaningPt: 'Escolher' }, { word: '選挙', reading: 'せんきょ (senkyo)', meaningPt: 'Eleição' }, { word: '選手', reading: 'せんしゅ (senshu)', meaningPt: 'Atleta / Jogador' } ] },
  { id: 'k_n2_add9_18', kanji: '船', onyomi: ['セン (sen)'], kunyomi: ['ふね (fune)', 'ふな (funa)'], meaningPt: 'Barco, Navio', strokes: 11, radical: '舟 (barco)', jlpt: 'N2', examples: [ { word: '船', reading: 'ふね (fune)', meaningPt: 'Barco / Navio' }, { word: '風船', reading: 'ふうせん (fuusen)', meaningPt: 'Balão' }, { word: '船長', reading: 'せんちょう (senchou)', meaningPt: 'Capitão (do navio)' } ] },
  { id: 'k_n2_add9_19', kanji: '線', onyomi: ['セン (sen)'], kunyomi: [], meaningPt: 'Linha, Fio', strokes: 15, radical: '糸 (fio)', jlpt: 'N2', examples: [ { word: '線', reading: 'せん (sen)', meaningPt: 'Linha' }, { word: '新幹線', reading: 'しんかんせん (shinkansen)', meaningPt: 'Trem-bala (Shinkansen)' }, { word: '脱線', reading: 'だっせん (dassen)', meaningPt: 'Descarrilamento / Fuga do assunto' } ] },
  { id: 'k_n2_add9_20', kanji: '浅', onyomi: ['セン (sen)'], kunyomi: ['あさ.い (asa.i)'], meaningPt: 'Raso, Superficial', strokes: 9, radical: '水 (água)', jlpt: 'N2', examples: [ { word: '浅い', reading: 'あさい (asai)', meaningPt: 'Raso / Superficial' }, { word: '浅草', reading: 'あさくさ (asakusa)', meaningPt: 'Asakusa (bairro de Tokyo)' }, { word: '浅黄', reading: 'あさぎ (asagi)', meaningPt: 'Amarelo claro' } ] },
  { id: 'k_n2_add9_21', kanji: '泉', onyomi: ['セン (sen)'], kunyomi: ['いずみ (izumi)'], meaningPt: 'Fonte, Nascente', strokes: 9, radical: '水 (água)', jlpt: 'N2', examples: [ { word: '温泉', reading: 'おんせん (onsen)', meaningPt: 'Fonte termal (Onsen)' }, { word: '泉', reading: 'いずみ (izumi)', meaningPt: 'Fonte de água' }, { word: '源泉', reading: 'げんせん (gensen)', meaningPt: 'Nascente / Origem' } ] },
  { id: 'k_n2_add9_22', kanji: '戦', onyomi: ['セン (sen)'], kunyomi: ['たたか.う (tataka.u)', 'いくさ (ikusa)'], meaningPt: 'Guerra, Batalha', strokes: 13, radical: '戈 (lança)', jlpt: 'N2', examples: [ { word: '戦う', reading: 'たたかう (tatakau)', meaningPt: 'Lutar / Batalhar' }, { word: '戦争', reading: 'せんそう (sensou)', meaningPt: 'Guerra' }, { word: '作戦', reading: 'さくせん (sakusen)', meaningPt: 'Tática / Estratégia' } ] },
  { id: 'k_n2_add9_23', kanji: '専', onyomi: ['セン (sen)'], kunyomi: ['もっぱ.ら (moppa.ra)'], meaningPt: 'Especialidade, Exclusivo', strokes: 9, radical: '寸 (medida)', jlpt: 'N2', examples: [ { word: '専門', reading: 'せんもん (senmon)', meaningPt: 'Especialidade / Campo de estudo' }, { word: '専用', reading: 'せんよう (senyou)', meaningPt: 'Uso exclusivo' }, { word: '専攻', reading: 'せんこう (senkou)', meaningPt: 'Especialização acadêmica' } ] },
  { id: 'k_n2_add9_24', kanji: '占', onyomi: ['セン (sen)'], kunyomi: ['うらな.う (urana.u)', 'し.める (shi.meru)'], meaningPt: 'Adivinhar, Ocupar', strokes: 5, radical: '卜 (adivinhação)', jlpt: 'N2', examples: [ { word: '占う', reading: 'うらなう (uranau)', meaningPt: 'Ler a sorte / Adivinhar' }, { word: '占める', reading: 'しめる (shimeru)', meaningPt: 'Ocupar (assento/posição)' }, { word: '星占い', reading: 'ほしうらない (hoshiuranai)', meaningPt: 'Astrologia / Horóscopo' } ] },
  { id: 'k_n2_add9_25', kanji: '絶', onyomi: ['ゼツ (zetsu)'], kunyomi: ['た.える (ta.eru)', 'た.つ (ta.tsu)'], meaningPt: 'Cortar, Acabar, Absoluto', strokes: 12, radical: '糸 (fio)', jlpt: 'N2', examples: [ { word: '絶対', reading: 'ぜったい (zettai)', meaningPt: 'Absolutamente / Com certeza' }, { word: '絶える', reading: 'たえる (taeru)', meaningPt: 'Extinguir-se / Acabar' }, { word: '絶望', reading: 'ぜつぼう (zetsubou)', meaningPt: 'Desespero' } ] },
  { id: 'k_n2_add9_26', kanji: '雪', onyomi: ['セツ (setsu)'], kunyomi: ['ゆき (yuki)'], meaningPt: 'Neve', strokes: 11, radical: '雨 (chuva)', jlpt: 'N2', examples: [ { word: '雪', reading: 'ゆき (yuki)', meaningPt: 'Neve' }, { word: '大雪', reading: 'おおゆき (ooyuki)', meaningPt: 'Nevasca / Muita neve' }, { word: '吹雪', reading: 'ふぶき (fubuki)', meaningPt: 'Tempestade de neve' } ] },
  { id: 'k_n2_add9_27', kanji: '節', onyomi: ['セツ (setsu)', 'セチ (sechi)'], kunyomi: ['ふし (fushi)'], meaningPt: 'Nó, Época, Moderação', strokes: 13, radical: '竹 (bambu)', jlpt: 'N2', examples: [ { word: '季節', reading: 'きせつ (kisetsu)', meaningPt: 'Estação do ano' }, { word: '節約', reading: 'せつやく (setsuyaku)', meaningPt: 'Economia (de dinheiro/recursos)' }, { word: '関節', reading: 'かんせつ (kansetsu)', meaningPt: 'Articulação (do corpo)' } ] },
  { id: 'k_n2_add9_28', kanji: '設', onyomi: ['セツ (setsu)'], kunyomi: ['もう.ける (mou.keru)'], meaningPt: 'Estabelecer, Preparar', strokes: 11, radical: '言 (palavra/falar)', jlpt: 'N2', examples: [ { word: '設定', reading: 'せってい (settei)', meaningPt: 'Configuração / Estabelecimento' }, { word: '設計', reading: 'せっけい (sekkei)', meaningPt: 'Design / Projeto' }, { word: '設備', reading: 'せつび (setsubi)', meaningPt: 'Equipamentos / Instalações' } ] },
  { id: 'k_n2_add9_29', kanji: '折', onyomi: ['セツ (setsu)'], kunyomi: ['お.る (o.ru)', 'お.れる (o.reru)', 'おり (ori)'], meaningPt: 'Dobrar, Quebrar', strokes: 7, radical: '手 (mão)', jlpt: 'N2', examples: [ { word: '折る', reading: 'おる (oru)', meaningPt: 'Dobrar / Quebrar' }, { word: '折り紙', reading: 'おりがみ (origami)', meaningPt: 'Origami (papel dobrado)' }, { word: '右折', reading: 'うせつ (usetsu)', meaningPt: 'Virar à direita' } ] },
  { id: 'k_n2_add9_30', kanji: '接', onyomi: ['セツ (setsu)'], kunyomi: ['つ.ぐ (tsu.gu)'], meaningPt: 'Tocar, Contatar', strokes: 11, radical: '手 (mão)', jlpt: 'N2', examples: [ { word: '直接', reading: 'ちょくせつ (chokusetsu)', meaningPt: 'Diretamente' }, { word: '面接', reading: 'めんせつ (mensetsu)', meaningPt: 'Entrevista' }, { word: '接近', reading: 'せっきん (sekkin)', meaningPt: 'Aproximação' } ] },
  { id: 'k_n2_add9_31', kanji: '責', onyomi: ['セキ (seki)'], kunyomi: ['せ.める (se.meru)'], meaningPt: 'Culpar, Responsabilidade', strokes: 11, radical: '貝 (concha/moeda)', jlpt: 'N2', examples: [ { word: '責任', reading: 'せきにん (sekinin)', meaningPt: 'Responsabilidade' }, { word: '責める', reading: 'せめる (semeru)', meaningPt: 'Culpar / Condenar' }, { word: '無責任', reading: 'むせきにん (musekinin)', meaningPt: 'Irresponsável' } ] },
  { id: 'k_n2_add9_32', kanji: '績', onyomi: ['セキ (seki)'], kunyomi: [], meaningPt: 'Resultados, Conquistas', strokes: 17, radical: '糸 (fio)', jlpt: 'N2', examples: [ { word: '成績', reading: 'せいせき (seiseki)', meaningPt: 'Notas (escolares) / Desempenho' }, { word: '実績', reading: 'じっせき (jisseki)', meaningPt: 'Conquistas / Resultados reais' }, { word: '業績', reading: 'ぎょうせき (gyouseki)', meaningPt: 'Desempenho nos negócios' } ] },
  { id: 'k_n2_add9_33', kanji: '積', onyomi: ['セキ (seki)'], kunyomi: ['つ.む (tsu.mu)', 'つ.もる (tsu.moru)'], meaningPt: 'Acumular, Empilhar', strokes: 16, radical: '禾 (cereal/grão)', jlpt: 'N2', examples: [ { word: '積む', reading: 'つむ (tsumu)', meaningPt: 'Empilhar / Acumular' }, { word: '積もる', reading: 'つもる (tsumoru)', meaningPt: 'Acumular-se (ex: neve)' }, { word: '面積', reading: 'めんせき (menseki)', meaningPt: 'Área' } ] },
  { id: 'k_n2_add9_34', kanji: '石', onyomi: ['セキ (seki)', 'シャク (shaku)', 'コク (koku)'], kunyomi: ['いし (ishi)'], meaningPt: 'Pedra', strokes: 5, radical: '石 (pedra)', jlpt: 'N2', examples: [ { word: '石', reading: 'いし (ishi)', meaningPt: 'Pedra' }, { word: '宝石', reading: 'ほうせき (houseki)', meaningPt: 'Joia' }, { word: '化石', reading: 'かせき (kaseki)', meaningPt: 'Fóssil' } ] },
  { id: 'k_n2_add9_35', kanji: '昔', onyomi: ['セキ (seki)', 'シャク (shaku)'], kunyomi: ['むかし (mukashi)'], meaningPt: 'Antigamente, Era uma vez', strokes: 8, radical: '日 (sol/dia)', jlpt: 'N2', examples: [ { word: '昔', reading: 'むかし (mukashi)', meaningPt: 'Antigamente' }, { word: '昔話', reading: 'むかしばなし (mukashibanashi)', meaningPt: 'Conto antigo / Lenda' }, { word: '大昔', reading: 'おおむかし (oomukashi)', meaningPt: 'Há muito tempo atrás' } ] },
  { id: 'k_n2_add9_36', kanji: '席', onyomi: ['セキ (seki)'], kunyomi: [], meaningPt: 'Assento', strokes: 10, radical: '巾 (tecido/toalha)', jlpt: 'N2', examples: [ { word: '席', reading: 'せき (seki)', meaningPt: 'Assento' }, { word: '出席', reading: 'しゅっせき (shusseki)', meaningPt: 'Presença / Comparecimento' }, { word: '座席', reading: 'ざせき (zaseki)', meaningPt: 'Assento (em veículos/teatros)' } ] },
  { id: 'k_n2_add9_37', kanji: '税', onyomi: ['ゼイ (zei)'], kunyomi: [], meaningPt: 'Imposto', strokes: 12, radical: '禾 (cereal/grão)', jlpt: 'N2', examples: [ { word: '税金', reading: 'ぜいきん (zeikin)', meaningPt: 'Imposto' }, { word: '消費税', reading: 'しょうひぜい (shouhizei)', meaningPt: 'Imposto sobre o consumo' }, { word: '税関', reading: 'ぜいかん (zeikan)', meaningPt: 'Alfândega' } ] },
  { id: 'k_n2_add9_38', kanji: '静', onyomi: ['セイ (sei)', 'ジョウ (jou)'], kunyomi: ['しず.か (shizu.ka)', 'しず.まる (shizu.maru)'], meaningPt: 'Silencioso, Calmo', strokes: 14, radical: '青 (azul)', jlpt: 'N2', examples: [ { word: '静か', reading: 'しずか (shizuka)', meaningPt: 'Silencioso / Calmo' }, { word: '冷静', reading: 'れいせい (reisei)', meaningPt: 'Calmo / Com frieza' }, { word: '安静', reading: 'あんせい (ansei)', meaningPt: 'Repouso (médico)' } ] },
  { id: 'k_n2_add9_39', kanji: '製', onyomi: ['セイ (sei)'], kunyomi: [], meaningPt: 'Fabricação, Produzido em', strokes: 14, radical: '衣 (roupa)', jlpt: 'N2', examples: [ { word: '製品', reading: 'せいひん (seihin)', meaningPt: 'Produto (manufaturado)' }, { word: '日本製', reading: 'にほんせい (nihonsei)', meaningPt: 'Fabricado no Japão' }, { word: '製造', reading: 'せいぞう (seizou)', meaningPt: 'Fabricação' } ] },
  { id: 'k_n2_add9_40', kanji: '精', onyomi: ['セイ (sei)', 'ショウ (shou)'], kunyomi: [], meaningPt: 'Energia, Refinado, Fada', strokes: 14, radical: '米 (arroz)', jlpt: 'N2', examples: [ { word: '精神', reading: 'せいしん (seishin)', meaningPt: 'Espírito / Mente' }, { word: '妖精', reading: 'ようせい (yousei)', meaningPt: 'Fada' }, { word: '精一杯', reading: 'せいいっぱい (seiippai)', meaningPt: 'Com todo o esforço' } ] },
  { id: 'k_n2_add9_41', kanji: '清', onyomi: ['セイ (sei)', 'ショウ (shou)'], kunyomi: ['きよ.い (kiyo.i)', 'きよ.める (kiyo.meru)'], meaningPt: 'Puro, Limpar', strokes: 11, radical: '水 (água)', jlpt: 'N2', examples: [ { word: '清潔', reading: 'せいけつ (seiketsu)', meaningPt: 'Limpo / Higiênico' }, { word: '清い', reading: 'きよい (kiyoi)', meaningPt: 'Puro / Limpo (coração/água)' }, { word: '清掃', reading: 'せいそう (seisou)', meaningPt: 'Limpeza' } ] },
  { id: 'k_n2_add9_42', kanji: '晴', onyomi: ['セイ (sei)'], kunyomi: ['は.れる (ha.reru)', 'は.れ (ha.re)'], meaningPt: 'Ensolarado, Limpar-se (céu)', strokes: 12, radical: '日 (sol/dia)', jlpt: 'N2', examples: [ { word: '晴れ', reading: 'はれ (hare)', meaningPt: 'Tempo bom / Ensolarado' }, { word: '晴れる', reading: 'はれる (hareru)', meaningPt: 'O tempo limpar' }, { word: '素晴らしい', reading: 'すばらしい (subarashii)', meaningPt: 'Maravilhoso' } ] },
  { id: 'k_n2_add9_43', kanji: '星', onyomi: ['セイ (sei)', 'ショウ (shou)'], kunyomi: ['ほし (hoshi)'], meaningPt: 'Estrela', strokes: 9, radical: '日 (sol/dia)', jlpt: 'N2', examples: [ { word: '星', reading: 'ほし (hoshi)', meaningPt: 'Estrela' }, { word: '流れ星', reading: 'ながれぼし (nagareboshi)', meaningPt: 'Estrela cadente' }, { word: '星座', reading: 'せいざ (seiza)', meaningPt: 'Constelação / Signo do zodíaco' } ] },
  { id: 'k_n2_add9_44', kanji: '整', onyomi: ['セイ (sei)'], kunyomi: ['ととの.える (totono.eru)', 'ととの.う (totono.u)'], meaningPt: 'Arrumar, Organizar', strokes: 16, radical: '攴 (bater)', jlpt: 'N2', examples: [ { word: '整理', reading: 'せいり (seiri)', meaningPt: 'Organização / Arrumação' }, { word: '整える', reading: 'ととのえる (totonoeru)', meaningPt: 'Arrumar / Preparar' }, { word: '調整', reading: 'ちょうせい (chousei)', meaningPt: 'Ajuste / Regulagem' } ] },
  { id: 'k_n2_add9_45', kanji: '政', onyomi: ['セイ (sei)', 'ショウ (shou)'], kunyomi: ['まつりごと (matsurigoto)'], meaningPt: 'Política, Governo', strokes: 9, radical: '攴 (bater)', jlpt: 'N2', examples: [ { word: '政治', reading: 'せいじ (seiji)', meaningPt: 'Política' }, { word: '政府', reading: 'せいふ (seifu)', meaningPt: 'Governo' }, { word: '政党', reading: 'せいとう (seitou)', meaningPt: 'Partido político' } ] },
  { id: 'k_n2_add9_46', kanji: '成', onyomi: ['セイ (sei)', 'ジョウ (jou)'], kunyomi: ['な.る (na.ru)', 'な.す (na.su)'], meaningPt: 'Tornar-se, Formar, Crescer', strokes: 6, radical: '戈 (lança)', jlpt: 'N2', examples: [ { word: '成功', reading: 'せいこう (seikou)', meaningPt: 'Sucesso' }, { word: '成長', reading: 'せいちょう (seichou)', meaningPt: 'Crescimento' }, { word: '成る', reading: 'なる (naru)', meaningPt: 'Tornar-se' } ] },
  { id: 'k_n2_add9_47', kanji: '性', onyomi: ['セイ (sei)', 'ショウ (shou)'], kunyomi: [], meaningPt: 'Sexo, Natureza, Propriedade', strokes: 8, radical: '心 (coração)', jlpt: 'N2', examples: [ { word: '性格', reading: 'せいかく (seikaku)', meaningPt: 'Personalidade' }, { word: '男性', reading: 'だんせい (dansei)', meaningPt: 'Sexo masculino / Homem' }, { word: '女性', reading: 'じょせい (josei)', meaningPt: 'Sexo feminino / Mulher' } ] },
  { id: 'k_n2_add9_48', kanji: '姓', onyomi: ['セイ (sei)', 'ショウ (shou)'], kunyomi: [], meaningPt: 'Sobrenome', strokes: 8, radical: '女 (mulher)', jlpt: 'N2', examples: [ { word: '姓名', reading: 'せいめい (seimei)', meaningPt: 'Nome completo' }, { word: '旧姓', reading: 'きゅうせい (kyuusei)', meaningPt: 'Nome de solteira' }, { word: '同姓同名', reading: 'どうせいどうめい (douseidoumei)', meaningPt: 'Mesmo nome e sobrenome' } ] },
  { id: 'k_n2_add9_49', kanji: '勢', onyomi: ['セイ (sei)'], kunyomi: ['いきお.い (ikio.i)'], meaningPt: 'Força, Vigor', strokes: 13, radical: '力 (força)', jlpt: 'N2', examples: [ { word: '勢い', reading: 'いきおい (ikioi)', meaningPt: 'Força / Ímpeto / Vigor' }, { word: '大勢', reading: 'おおぜい (oozei)', meaningPt: 'Multidão / Muita gente' }, { word: '姿勢', reading: 'しせい (shisei)', meaningPt: 'Postura / Atitude' } ] },
  { id: 'k_n2_add9_50', kanji: '制', onyomi: ['セイ (sei)'], kunyomi: [], meaningPt: 'Sistema, Controle', strokes: 8, radical: '刀 (espada)', jlpt: 'N2', examples: [ { word: '制度', reading: 'せいど (seido)', meaningPt: 'Sistema / Instituição' }, { word: '制服', reading: 'せいふく (seifuku)', meaningPt: 'Uniforme' }, { word: '制限', reading: 'せいげん (seigen)', meaningPt: 'Restrição / Limite' } ] },
  { id: 'k_n2_add9_51', kanji: '数', onyomi: ['スウ (suu)', 'ス (su)'], kunyomi: ['かず (kazu)', 'かぞ.える (kazoe.ru)'], meaningPt: 'Número, Contar', strokes: 13, radical: '攴 (bater)', jlpt: 'N2', examples: [ { word: '数', reading: 'かず (kazu)', meaningPt: 'Número' }, { word: '数える', reading: 'かぞえる (kazoeru)', meaningPt: 'Contar' }, { word: '数字', reading: 'すうじ (suuji)', meaningPt: 'Número / Algarismo' } ] },
  { id: 'k_n2_add9_52', kanji: '吹', onyomi: ['スイ (sui)'], kunyomi: ['ふ.く (fu.ku)'], meaningPt: 'Soprar', strokes: 7, radical: '口 (boca)', jlpt: 'N2', examples: [ { word: '吹く', reading: 'ふく (fuku)', meaningPt: 'Soprar / Ventar' }, { word: '吹雪', reading: 'ふぶき (fubuki)', meaningPt: 'Nevasca' }, { word: '吹き飛ぶ', reading: 'ふきとぶ (fukitobu)', meaningPt: 'Ser levado pelo vento' } ] },
  { id: 'k_n2_add9_53', kanji: '震', onyomi: ['シン (shin)'], kunyomi: ['ふる.える (furue.ru)', 'ふる.う (furu.u)'], meaningPt: 'Tremor, Tremer', strokes: 15, radical: '雨 (chuva)', jlpt: 'N2', examples: [ { word: '地震', reading: 'じしん (jishin)', meaningPt: 'Terremoto' }, { word: '震える', reading: 'ふるえる (furueru)', meaningPt: 'Tremer (de frio/medo)' }, { word: '震度', reading: 'しんど (shindo)', meaningPt: 'Escala de tremor sísmico' } ] }
];

const dataPathN2 = path.join(process.cwd(), 'src/data/kanjiN2N1.ts');

let n2Content = fs.readFileSync(dataPathN2, 'utf-8');

let addedCount = 0;
let blocksStr = '';

for (const k of newKanjis) {
  if (n2Content.includes(`kanji: '${k.kanji}'`)) {
    console.log(`Skipping duplicate: ${k.kanji}`);
    continue;
  }

  const objStr = `  {
    id: '${k.id}',
    kanji: '${k.kanji}',
    onyomi: ${JSON.stringify(k.onyomi)},
    kunyomi: ${JSON.stringify(k.kunyomi)},
    meaningPt: '${k.meaningPt}',
    strokes: ${k.strokes},
    radical: '${k.radical}',
    jlpt: '${k.jlpt}',
    examples: ${JSON.stringify(k.examples, null, 6).replace(/"([^"]+)":/g, '$1:')}
  }`;

  blocksStr += (addedCount === 0 ? '' : ',\n') + objStr;
  addedCount++;
}

if (addedCount > 0) {
  const lastBracketIndex = n2Content.lastIndexOf('];');
  n2Content = n2Content.slice(0, lastBracketIndex) + ',\n' + blocksStr + '\n];\n';
  fs.writeFileSync(dataPathN2, n2Content, 'utf-8');
}

console.log(`Successfully added ${addedCount} new Kanjis to N2!`);
