import fs from 'fs';
import path from 'path';

const items = [
  { w: '亡くなる', r: 'なくなる', rom: 'nakunaru', m: 'falecer; morrer', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '直る', r: 'なおる', rom: 'naoru', m: 'ser consertado; ser reparado', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '治る', r: 'なおる', rom: 'naoru', m: 'curar-se; sarar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '慣れる', r: 'なれる', rom: 'nareru', m: 'acostumar-se', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '鳴る', r: 'なる', rom: 'naru', m: 'tocar; soar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '寝坊する', r: 'ねぼうする', rom: 'nebousuru', m: 'dormir demais', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '眠る', r: 'ねむる', rom: 'nemuru', m: 'dormir', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '逃げる', r: 'にげる', rom: 'nigeru', m: 'fugir; escapar', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '似る', r: 'にる', rom: 'niru', m: 'parecer-se com', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '残る', r: 'のこる', rom: 'nokoru', m: 'sobrar; restar; permanecer', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '乗り換える', r: 'のりかえる', rom: 'norikaeru', m: 'fazer baldeação; trocar de veículo', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '濡れる', r: 'ぬれる', rom: 'nureru', m: 'molhar-se', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '塗る', r: 'ぬる', rom: 'nuru', m: 'pintar; passar (creme/tinta)', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '盗む', r: 'ぬすむ', rom: 'nusumu', m: 'roubar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '入学する', r: 'にゅうがくする', rom: 'nyuugakusuru', m: 'ingressar (na escola/universidade)', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '入院する', r: 'にゅういんする', rom: 'nyuuinsuru', m: 'ser internado (hospital)', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '落ちる', r: 'おちる', rom: 'ochiru', m: 'cair; reprovar', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '驚く', r: 'おどろく', rom: 'odoroku', m: 'surpreender-se; assustar-se', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '踊る', r: 'おどる', rom: 'odoru', m: 'dançar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: 'お出でになる', r: 'おいでになる', rom: 'oide ni naru', m: 'ir; vir; estar (forma respeitosa)', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: 'お祝いする', r: 'おいわいする', rom: 'oiwaisuru', m: 'comemorar; parabenizar', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '行う', r: 'おこなう', rom: 'okonau', m: 'realizar; executar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '怒る', r: 'おこる', rom: 'okoru', m: 'ficar bravo; zangar-se', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '起こす', r: 'おこす', rom: 'okosu', m: 'acordar (alguém); causar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '遅れる', r: 'おくれる', rom: 'okureru', m: 'atrasar-se', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '送る', r: 'おくる', rom: 'okuru', m: 'enviar; mandar; acompanhar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '思い出す', r: 'おもいだす', rom: 'omoidasu', m: 'lembrar-se; recordar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '折れる', r: 'おれる', rom: 'oreru', m: 'quebrar-se; dobrar-se (intransitivo)', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '下りる', r: 'おりる', rom: 'oriru', m: 'descer', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '折る', r: 'おる', rom: 'oru', m: 'quebrar; dobrar (transitivo)', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '仰る', r: 'おっしゃる', rom: 'ossharu', m: 'dizer (forma respeitosa)', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '落とす', r: 'おとす', rom: 'otosu', m: 'derrubar; deixar cair', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '冷房する', r: 'れいぼうする', rom: 'reibousuru', m: 'ligar o ar-condicionado (esfriar ambiente)', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '連絡する', r: 'れんらくする', rom: 'renrakusuru', m: 'entrar em contato', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '利用する', r: 'りようする', rom: 'riyousuru', m: 'usar; utilizar', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '留守にする', r: 'るすにする', rom: 'rusu ni suru', m: 'ausentar-se; não estar em casa', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '下がる', r: 'さがる', rom: 'sagaru', m: 'descer; abaixar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '探す', r: 'さがす', rom: 'sagasu', m: 'procurar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '下げる', r: 'さげる', rom: 'sageru', m: 'abaixar (algo); retirar', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '差し上げる', r: 'さしあげる', rom: 'sashiageru', m: 'dar (forma humilde)', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '騒ぐ', r: 'さわぐ', rom: 'sawagu', m: 'fazer barulho; alvoroçar-se', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '触る', r: 'さわる', rom: 'sawaru', m: 'tocar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '生活する', r: 'せいかつする', rom: 'seikatsusuru', m: 'viver; levar a vida', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '生産する', r: 'せいさんする', rom: 'seisansuru', m: 'produzir', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '戦争する', r: 'せんそうする', rom: 'sensousuru', m: 'fazer guerra', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '説明する', r: 'せつめいする', rom: 'setsumeisuru', m: 'explicar', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '試合する', r: 'しあいする', rom: 'shiaisuru', m: 'jogar (uma partida)', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '叱る', r: 'しかる', rom: 'shikaru', m: 'dar bronca; repreender', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '試験する', r: 'しけんする', rom: 'shikensuru', m: 'fazer exame; testar', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '失敗する', r: 'しっぱいする', rom: 'shippaisuru', m: 'falhar; fracassar', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '調べる', r: 'しらべる', rom: 'shiraberu', m: 'investigar; pesquisar', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '知らせる', r: 'しらせる', rom: 'shiraseru', m: 'notificar; informar', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '生じる', r: 'しょうじる', rom: 'shoujiru', m: 'produzir; ocorrer', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '紹介する', r: 'しょうかいする', rom: 'shoukaisuru', m: 'apresentar (alguém/algo)', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '育てる', r: 'そだてる', rom: 'sodateru', m: 'criar (filhos/plantas); educar', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '卒業する', r: 'そつぎょうする', rom: 'sotsugyousuru', m: 'formar-se; graduar-se', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '相談する', r: 'そうだんする', rom: 'soudansuru', m: 'consultar; discutir', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '滑る', r: 'すべる', rom: 'suberu', m: 'escorregar; deslizar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '水泳する', r: 'すいえいする', rom: 'suieisuru', m: 'nadar (praticar natação)', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '空く', r: 'すく', rom: 'suku', m: 'ficar vazio; ter fome (onaka ga suku)', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '済む', r: 'すむ', rom: 'sumu', m: 'terminar; resolver-se', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '進む', r: 'すすむ', rom: 'susumu', m: 'avançar; progredir', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '捨てる', r: 'すてる', rom: 'suteru', m: 'jogar fora; descartar', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '退院する', r: 'たいいんする', rom: 'taiinsuru', m: 'ter alta (do hospital)', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '誕生する', r: 'たんじょうする', rom: 'tanjousuru', m: 'nascer; ser criado', cat: 'verbo_irregular', catLabel: 'Verbo Irregular' },
  { w: '倒れる', r: 'たおれる', rom: 'taoreru', m: 'cair; desmaiar', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '足りる', r: 'たりる', rom: 'tariru', m: 'ser suficiente; bastar', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '足す', r: 'たす', rom: 'tasu', m: 'somar; adicionar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '建てる', r: 'たてる', rom: 'tateru', m: 'construir', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '尋ねる', r: 'たずねる', rom: 'tazuneru', m: 'perguntar', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '訪ねる', r: 'たずねる', rom: 'tazuneru', m: 'visitar', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '手伝う', r: 'てつだう', rom: 'tetsudau', m: 'ajudar; auxiliar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '届ける', r: 'とどける', rom: 'todokeru', m: 'entregar (no destino)', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '泊まる', r: 'とまる', rom: 'tomaru', m: 'hospedar-se; passar a noite', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '止める', r: 'とめる', rom: 'tomeru', m: 'parar (algo)', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '通る', r: 'とおる', rom: 'tooru', m: 'passar (por)', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '取り替える', r: 'とりかえる', rom: 'torikaeru', m: 'trocar; substituir', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '続ける', r: 'つづける', rom: 'tsudzukeru', m: 'continuar (algo)', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '続く', r: 'つづく', rom: 'tsudzuku', m: 'continuar (intransitivo)', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '捕まえる', r: 'つかまえる', rom: 'tsukamaeru', m: 'pegar; capturar', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '漬ける', r: 'つける', rom: 'tsukeru', m: 'mergulhar; conservar (em líquido)', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '付く', r: 'つく', rom: 'tsuku', m: 'estar anexado/grudado', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '連れる', r: 'つれる', rom: 'tsureru', m: 'levar (alguém) junto', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '釣る', r: 'つる', rom: 'tsuru', m: 'pescar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '伝える', r: 'つたえる', rom: 'tsutaeru', m: 'transmitir; relatar', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '包む', r: 'つつむ', rom: 'tsutsumu', m: 'embrulhar; envolver', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '植える', r: 'うえる', rom: 'ueru', m: 'plantar', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '動く', r: 'うごく', rom: 'ugoku', m: 'mover-se; funcionar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '伺う', r: 'うかがう', rom: 'ukagau', m: 'visitar; perguntar (forma humilde)', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '受ける', r: 'うける', rom: 'ukeru', m: 'fazer (exame); receber', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '打つ', r: 'うつ', rom: 'utsu', m: 'bater; digitar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '移る', r: 'うつる', rom: 'utsuru', m: 'mudar-se; transferir-se', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '写す', r: 'うつす', rom: 'utsusu', m: 'copiar; fotografar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '別れる', r: 'わかれる', rom: 'wakareru', m: 'separar-se; despedir-se', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '沸かす', r: 'わかす', rom: 'wakasu', m: 'ferver (água)', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '沸く', r: 'わく', rom: 'waku', m: 'ferver (intransitivo)', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '笑う', r: 'わらう', rom: 'warau', m: 'rir; sorrir', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' },
  { w: '割れる', r: 'われる', rom: 'wareru', m: 'quebrar; rachar', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '焼ける', r: 'やける', rom: 'yakeru', m: 'queimar; assar (intransitivo)', cat: 'verbo_ichidan', catLabel: 'Verbo Tipo 2 (Ichidan)' },
  { w: '焼く', r: 'やく', rom: 'yaku', m: 'assar; grelhar; queimar', cat: 'verbo_godan', catLabel: 'Verbo Tipo 1 (Godan)' }
];

const examples = {
  '亡くなる': { jp: '祖父が亡くなりました。', r: 'そふが なくなりました。', rom: 'sofu ga nakunarimashita.', pt: 'Meu avô faleceu.' },
  '直る': { jp: 'パソコンが直りました。', r: 'パソコンが なおるりました。', rom: 'pasokon ga naorimashita.', pt: 'O computador foi consertado.' },
  '治る': { jp: '風邪が治りました。', r: 'かぜが なおるりました。', rom: 'kaze ga naorimashita.', pt: 'Curei-me do resfriado.' },
  '慣れる': { jp: '日本の生活に慣れました。', r: 'にほんの せいかつに なれました。', rom: 'nihon no seikatsu ni naremashita.', pt: 'Acostumei-me com a vida no Japão.' },
  '鳴る': { jp: '電話が鳴っています。', r: 'でんわが なっています。', rom: 'denwa ga natteimasu.', pt: 'O telefone está tocando.' },
  '寝坊する': { jp: '今朝は寝坊しました。', r: 'けさは ねぼうしました。', rom: 'kesa wa neboushimashita.', pt: 'Esta manhã dormi demais.' },
  '眠る': { jp: '静かに眠ります。', r: 'しずかに ねむります。', rom: 'shizuka ni nemurimasu.', pt: 'Durmo tranquilamente.' },
  '逃げる': { jp: '犬が逃げました。', r: 'いぬが にげました。', rom: 'inu ga nigemashita.', pt: 'O cachorro fugiu.' },
  '似る': { jp: '母に似ています。', r: 'ははに にています。', rom: 'haha ni niteimasu.', pt: 'Pareço com a minha mãe.' },
  '残る': { jp: 'ご飯が残っています。', r: 'ごはんが のこっています。', rom: 'gohan ga nokotteimasu.', pt: 'Restou (sobrou) comida.' },
  '乗り換える': { jp: '東京駅で乗り換えます。', r: 'とうきょうえきで のりかえます。', rom: 'toukyou eki de norikaemasu.', pt: 'Faço a baldeação na estação de Tóquio.' },
  '濡れる': { jp: '雨で濡れました。', r: 'あめで ぬれました。', rom: 'ame de nuremashita.', pt: 'Molhei-me com a chuva.' },
  '塗る': { jp: 'パンにバターを塗ります。', r: 'パンに バターを ぬります。', rom: 'pan ni bataa o nurimasu.', pt: 'Passo manteiga no pão.' },
  '盗む': { jp: '泥棒にお金を盗まれました。', r: 'どろぼうに おかねを ぬすまれました。', rom: 'dorobou ni okane o nusumaremashita.', pt: 'Tive meu dinheiro roubado por um ladrão.' },
  '入学する': { jp: '大学に入学します。', r: 'だいがくに にゅうがくします。', rom: 'daigaku ni nyuugakushimasu.', pt: 'Ingressarei na universidade.' },
  '入院する': { jp: '病気で入院しました。', r: 'びょうきで にゅういんしました。', rom: 'byouki de nyuuishimashita.', pt: 'Fui internado devido à doença.' },
  '落ちる': { jp: 'りんごが落ちました。', r: 'りんごが おちました。', rom: 'ringo ga ochimashita.', pt: 'A maçã caiu.' },
  '驚く': { jp: 'ニュースに驚きました。', r: 'ニュースに おどろきました。', rom: 'nyuusu ni odorokimashita.', pt: 'Surpreendi-me com as notícias.' },
  '踊る': { jp: '音楽に合わせて踊ります。', r: 'おんがくに あわせて おどります。', rom: 'ongaku ni awasete odorimasu.', pt: 'Danço acompanhando a música.' },
  'お出でになる': { jp: '先生がお出でになります。', r: 'せんせいが おいでになります。', rom: 'sensei ga oide ni narimasu.', pt: 'O professor virá (respeitoso).' },
  'お祝いする': { jp: '誕生日をお祝いします。', r: 'たんじょうびを おいわいします。', rom: 'tanjoubi o oiwaishimasu.', pt: 'Comemoro o aniversário.' },
  '行う': { jp: '会議を行います。', r: 'かいぎを おこないます。', rom: 'kaigi o okonaimasu.', pt: 'Realizarei uma reunião.' },
  '怒る': { jp: '父が怒っています。', r: 'ちちが おこっています。', rom: 'chichi ga okotteimasu.', pt: 'Meu pai está bravo.' },
  '起こす': { jp: '子供を起こします。', r: 'こどもを おこします。', rom: 'kodomo o okoshimasu.', pt: 'Vou acordar a criança.' },
  '遅れる': { jp: '電車が遅れています。', r: 'でんしゃが おくれています。', rom: 'densha ga okureteimasu.', pt: 'O trem está atrasado.' },
  '送る': { jp: '荷物を送ります。', r: 'にもつを おくります。', rom: 'nimotsu o okurimasu.', pt: 'Enviarei a bagagem.' },
  '思い出す': { jp: '子供の頃を思い出します。', r: 'こどもの ころを おもいだします。', rom: 'kodomo no koro o omoidashimasu.', pt: 'Lembro-me da minha infância.' },
  '折れる': { jp: '木の枝が折れました。', r: 'きの えだが おれました。', rom: 'ki no eda ga oremashita.', pt: 'O galho da árvore quebrou-se.' },
  '下りる': { jp: '階段を下りります。', r: 'かいだんを おりります。', rom: 'kaidan o oririmasu.', pt: 'Desço as escadas.' },
  '折る': { jp: '紙を折ります。', r: 'かみを おります。', rom: 'kami o orimasu.', pt: 'Dobro o papel.' },
  '仰る': { jp: '社長がそう仰いました。', r: 'しゃちょうが そう おっしゃいました。', rom: 'shachou ga sou osshaimashita.', pt: 'O presidente da empresa disse isso.' },
  '落とす': { jp: '財布を落としました。', r: 'さいふを おとしました。', rom: 'saifu o otoshimashita.', pt: 'Deixei cair a carteira.' },
  '冷房する': { jp: '部屋を冷房します。', r: 'へやを れいぼうします。', rom: 'heya o reiboushimasu.', pt: 'Ligo o ar-condicionado do quarto.' },
  '連絡する': { jp: '後で連絡します。', r: 'あとで れんらくします。', rom: 'ato de renrakushimasu.', pt: 'Entrarei em contato mais tarde.' },
  '利用する': { jp: '図書館を利用します。', r: 'としょかんを りようします。', rom: 'toshokan o riyoushimasu.', pt: 'Utilizo a biblioteca.' },
  '留守にする': { jp: '家を留守にします。', r: 'いえを るすにします。', rom: 'ie o rusu ni shimasu.', pt: 'Estarei ausente de casa.' },
  '下がる': { jp: '熱が下がりました。', r: 'ねつが さがりました。', rom: 'netsu ga sagarimashita.', pt: 'A febre baixou.' },
  '探す': { jp: '時計を探しています。', r: 'とけいを さがしています。', rom: 'tokei o sagashiteimasu.', pt: 'Estou procurando o relógio.' },
  '下げる': { jp: '値段を下げます。', r: 'ねだんを さげます。', rom: 'nedan o sagemasu.', pt: 'Abaixo o preço.' },
  '差し上げる': { jp: '先生に花を差し上げました。', r: 'せんせいに はなを さしあげました。', rom: 'sensei ni hana o sashiagemashita.', pt: 'Dei flores ao professor (forma humilde).' },
  '騒ぐ': { jp: '教室で騒いではいけません。', r: 'きょうしつで さわいでは いけません。', rom: 'kyoushitsu de sawaidewa ikemasen.', pt: 'Não deve fazer barulho na sala de aula.' },
  '触る': { jp: '絵に触らないでください。', r: 'えに さわらないでください。', rom: 'e ni sawaranaide kudasai.', pt: 'Por favor, não toque na pintura.' },
  '生活する': { jp: '日本で生活しています。', r: 'にほんで せいかつしています。', rom: 'nihon de seikatsushiteimasu.', pt: 'Levo minha vida no Japão.' },
  '生産する': { jp: '車を生産します。', r: 'くるまを せいさんします。', rom: 'kuruma o seisanshimasu.', pt: 'Produzo carros.' },
  '戦争する': { jp: '国と国が戦争します。', r: 'くにと くにが せんそうします。', rom: 'kuni to kuni ga sensoushimasu.', pt: 'País e país entram em guerra.' },
  '説明する': { jp: '理由を説明します。', r: 'りゆうを せつめいします。', rom: 'riyuu o setsumeishimasu.', pt: 'Explicarei o motivo.' },
  '試合する': { jp: '明日、野球の試合をします。', r: 'あした、やきゅうの しあいを します。', rom: 'ashita, yakyuu no shiai o shimasu.', pt: 'Amanhã jogarei uma partida de beisebol.' },
  '叱る': { jp: '母に叱られました。', r: 'ははに しかられました。', rom: 'haha ni shikararemashita.', pt: 'Levei bronca da minha mãe.' },
  '試験する': { jp: '機械を試験します。', r: 'きかいを しけんします。', rom: 'kikai o shikenshimasu.', pt: 'Testarei as máquinas.' },
  '失敗する': { jp: 'テストに失敗しました。', r: 'テストに しっぱいしました。', rom: 'tesuto ni shippaishimashita.', pt: 'Falhei no teste.' },
  '調べる': { jp: '言葉の意味を調べます。', r: 'ことばの いみを しらべます。', rom: 'kotoba no imi o shirabemasu.', pt: 'Vou pesquisar o significado da palavra.' },
  '知らせる': { jp: '結果を知らせます。', r: 'けっかを しらせます。', rom: 'kekka o shirasemasu.', pt: 'Notificarei os resultados.' },
  '生じる': { jp: '問題が生じました。', r: 'もんだいが しょうじました。', rom: 'mondai ga shoujimashita.', pt: 'Ocorreu um problema.' },
  '紹介する': { jp: '友達を紹介します。', r: 'ともだちを しょうかいします。', rom: 'tomodachi o shoukaishimasu.', pt: 'Vou apresentar o amigo.' },
  '育てる': { jp: '花を育てています。', r: 'はなを そだてています。', rom: 'hana o sodateteimasu.', pt: 'Estou cultivando flores.' },
  '卒業する': { jp: '高校を卒業します。', r: 'こうこうを そつぎょうします。', rom: 'koukou o sotsugyoushimasu.', pt: 'Vou me formar no ensino médio.' },
  '相談する': { jp: '先生に相談します。', r: 'せんせいに そうだんします。', rom: 'sensei ni soudanshimasu.', pt: 'Vou consultar o professor.' },
  '滑る': { jp: '雪で道が滑ります。', r: 'ゆきで みちが すべります。', rom: 'yuki de michi ga suberimasu.', pt: 'A rua escorrega por causa da neve.' },
  '水泳する': { jp: 'プールで水泳します。', r: 'プールで すいえいします。', rom: 'puuru de suieishimasu.', pt: 'Pratico natação na piscina.' },
  '空く': { jp: 'お腹が空きました。', r: 'おなかが すきました。', rom: 'onaka ga sukimashita.', pt: 'Fiquei com fome (a barriga ficou vazia).' },
  '済む': { jp: '仕事が済みました。', r: 'しごとが すみました。', rom: 'shigoto ga sumimashita.', pt: 'O trabalho terminou.' },
  '進む': { jp: '前へ進んでください。', r: 'まえへ すすんでください。', rom: 'mae e susunde kudasai.', pt: 'Avance, por favor.' },
  '捨てる': { jp: 'ゴミを捨てます。', r: 'ゴミを すてます。', rom: 'gomi o sutemasu.', pt: 'Jogo o lixo fora.' },
  '退院する': { jp: '明日、退院します。', r: 'あした、たいいんします。', rom: 'ashita, taiinshimasu.', pt: 'Amanhã terei alta do hospital.' },
  '誕生する': { jp: '新しい国が誕生しました。', r: 'あたらしい くにが たんじょうしました。', rom: 'atarashii kuni ga tanjoushimashita.', pt: 'Uma nova nação nasceu.' },
  '倒れる': { jp: '強い風で木が倒れました。', r: 'つよい かぜで きが たおれました。', rom: 'tsuyoi kaze de ki ga taoremashita.', pt: 'A árvore caiu devido ao vento forte.' },
  '足りる': { jp: 'お金が足りません。', r: 'おかねが たりません。', rom: 'okane ga tarimasen.', pt: 'O dinheiro não é suficiente.' },
  '足す': { jp: '塩を少し足します。', r: 'しおを すこし たします。', rom: 'shio o sukoshi tashimasu.', pt: 'Adiciono um pouco de sal.' },
  '建てる': { jp: '家を建てます。', r: 'いえを たてます。', rom: 'ie o tatemasu.', pt: 'Vou construir uma casa.' },
  '尋ねる': { jp: '道を尋ねました。', r: 'みちを たずねました。', rom: 'michi o tazunemashita.', pt: 'Perguntei o caminho.' },
  '訪ねる': { jp: '友達の家を訪ねます。', r: 'ともだちの いえを たずねます。', rom: 'tomodachi no ie o tazunemasu.', pt: 'Visitarei a casa de um amigo.' },
  '手伝う': { jp: '母の仕事を手伝います。', r: 'ははの しごとを てつだいます。', rom: 'haha no shigoto o tetsudaimasu.', pt: 'Ajudo no trabalho da minha mãe.' },
  '届ける': { jp: '荷物を届けます。', r: 'にもつを とどけます。', rom: 'nimotsu o todokemasu.', pt: 'Entregarei a encomenda.' },
  '泊まる': { jp: 'ホテルに泊まります。', r: 'ホテルに とまります。', rom: 'hoteru ni tomarimasu.', pt: 'Hospedo-me no hotel.' },
  '止める': { jp: '車を止めます。', r: 'くるまを とめます。', rom: 'kuruma o tomemasu.', pt: 'Paro o carro.' },
  '通る': { jp: 'この道を通ります。', r: 'この みちを とおります。', rom: 'kono michi o toorimasu.', pt: 'Passarei por esta rua.' },
  '取り替える': { jp: '新しいのと取り替えます。', r: 'あたらしいのと とりかえます。', rom: 'atarashii no to torikaemasu.', pt: 'Substituirei por um novo.' },
  '続ける': { jp: '勉強を続けます。', r: 'べんきょうを つづけます。', rom: 'benkyou o tsudzukemasu.', pt: 'Vou continuar os estudos.' },
  '続く': { jp: '雨が続いています。', r: 'あめが つづいています。', rom: 'ame ga tsudzukuiteimasu.', pt: 'A chuva está continuando.' },
  '捕まえる': { jp: '泥棒を捕まえました。', r: 'どろぼうを つかまえました。', rom: 'dorobou o tsukamaemashita.', pt: 'Capturei o ladrão.' },
  '漬ける': { jp: '野菜を漬けます。', r: 'やさいを つけます。', rom: 'yasai o tsukemasu.', pt: 'Faço a conserva de legumes.' },
  '付く': { jp: '服に汚れが付いています。', r: 'ふくに よごれが ついています。', rom: 'fuku ni yogore ga tsuiteimasu.', pt: 'Tem sujeira grudada na roupa.' },
  '連れる': { jp: '犬を連れて散歩します。', r: 'いぬを つれて さんぽします。', rom: 'inu o tsurete sanposhimasu.', pt: 'Passeio levando o cachorro.' },
  '釣る': { jp: '川で魚を釣ります。', r: 'かわで さかなを つります。', rom: 'kawa de sakana o tsurimasu.', pt: 'Pesco peixes no rio.' },
  '伝える': { jp: '彼によろしく伝えてください。', r: 'かれに よろしく つたえてください。', rom: 'kare ni yoroshiku tsutaete kudasai.', pt: 'Por favor, mande lembranças a ele.' },
  '包む': { jp: 'プレゼントを紙で包みます。', r: 'プレゼントを かみで つつみます。', rom: 'purezento o kami de tsutsumimasu.', pt: 'Embrulho o presente com papel.' },
  '植える': { jp: '庭に木を植えます。', r: 'にわに きを うえます。', rom: 'niwa ni ki o uemasu.', pt: 'Planto uma árvore no jardim.' },
  '動く': { jp: '時計が動いていません。', r: 'とけいが うごいていません。', rom: 'tokei ga ugoiteimasen.', pt: 'O relógio não está funcionando (se movendo).' },
  '伺う': { jp: 'お話を伺います。', r: 'おはなしを うかがいます。', rom: 'ohanashi o ukagaimasu.', pt: 'Ouvirei o que tem a dizer (forma humilde).' },
  '受ける': { jp: '試験を受けます。', r: 'しけんを うけます。', rom: 'shiken o ukemasu.', pt: 'Prestarei um exame.' },
  '打つ': { jp: 'ボールを打ちます。', r: 'ボールを うちます。', rom: 'booru o uchimasu.', pt: 'Bato na bola.' },
  '移る': { jp: '新しい家に移ります。', r: 'あたらしい いえに うつります。', rom: 'atarashii ie ni utsurimasu.', pt: 'Mudo-me para uma casa nova.' },
  '写す': { jp: '黒板の字をノートに写します。', r: 'こくばんの じを ノートに うつします。', rom: 'kokuban no ji o nooto ni utsusimasu.', pt: 'Copio as letras da lousa no caderno.' },
  '別れる': { jp: '彼女と別れました。', r: 'かのじょと わかれました。', rom: 'kanojo to wakaremashita.', pt: 'Terminei (separei-me) com ela.' },
  '沸かす': { jp: 'お湯を沸かします。', r: 'おゆを わかします。', rom: 'oyu o wakashimasu.', pt: 'Fervo a água.' },
  '沸く': { jp: 'お湯が沸きました。', r: 'おゆが わきました。', rom: 'oyu ga wakimashita.', pt: 'A água ferveu.' },
  '笑う': { jp: 'みんなで笑いました。', r: 'みんなで わらいました。', rom: 'minna de waraimashita.', pt: 'Todos nós rimos.' },
  '割れる': { jp: '窓ガラスが割れました。', r: 'まどガラスが われました。', rom: 'mado garasu ga waremashita.', pt: 'O vidro da janela quebrou.' },
  '焼ける': { jp: '肉が焼けました。', r: 'にくが やけました。', rom: 'niku ga yakemashita.', pt: 'A carne está assada.' },
  '焼く': { jp: 'パンを焼きます。', r: 'パンを やきます。', rom: 'pan o yakimasu.', pt: 'Asso (torro) pão.' }
};

const filePath = path.join(process.cwd(), 'src/data/vocabN4.ts');
let fileContent = fs.readFileSync(filePath, 'utf8');

const newObjects = items.map((n, i) => {
  const ex = examples[n.w] || {
    jp: "Exemplo",
    reading: "...",
    rom: "...",
    pt: "..."
  };
  
  const safePt = ex.pt.replace(/'/g, "\\'");
  const safeRom = ex.rom.replace(/'/g, "\\'");

  return "  {\n" +
    "    id: 'n4_verb_batch2_" + Date.now() + "_" + i + "',\n" +
    "    word: '" + n.w + "',\n" +
    "    reading: '" + n.r.replace(/'/g, "\\'") + "',\n" +
    "    romaji: '" + n.rom.replace(/'/g, "\\'") + "',\n" +
    "    meaningPt: '" + n.m.replace(/'/g, "\\'") + "',\n" +
    "    category: '" + n.cat + "',\n" +
    "    jlpt: 'N4',\n" +
    "    categoryLabelPt: '" + n.catLabel + "',\n" +
    "    exampleSentence: {\n" +
    "      jp: '" + ex.jp + "',\n" +
    "      reading: '" + ex.r.replace(/'/g, "\\'") + "',\n" +
    "      romaji: '" + safeRom + "',\n" +
    "      meaningPt: '" + safePt + "'\n" +
    "    }\n" +
    "  }";
}).join(',\n');

fileContent = fileContent.replace(
  /export const VOCAB_N4: VocabItem\[\] = \[/,
  "export const VOCAB_N4: VocabItem[] = [\n" + newObjects + ",\n"
);

fs.writeFileSync(filePath, fileContent, 'utf8');
console.log('Added 100 more N4 Verbs to vocabN4.ts successfully!');
